// Package centrysecrets reads and rewrites the encrypted vault representation
// used by the current Centry database secret engine.
//
// It deliberately has no environment, database, filesystem, HTTP, or durable
// storage capability. Persistence and authorization belong to its callers.
package centrysecrets

import (
	"bytes"
	"crypto/aes"
	"crypto/cipher"
	"crypto/hmac"
	"crypto/sha256"
	"encoding/base64"
	"encoding/json"
	"errors"
	"io"
	"math"
	"strconv"
	"strings"
)

const (
	fernetKeyBytes    = 32
	fernetEncodedKey  = 44
	fernetVersion     = 0x80
	fernetHeaderBytes = 1 + 8 + aes.BlockSize
	fernetMACBytes    = sha256.Size
	fernetMinimumRaw  = fernetHeaderBytes + aes.BlockSize + fernetMACBytes
	maxProjectIDBytes = 10
	maxProjectIDJSON  = 64
)

var (
	ErrInvalidMasterKey  = errors.New("centrysecrets: invalid master key")
	ErrInvalidProjectKey = errors.New("centrysecrets: invalid project key")
	ErrInvalidVault      = errors.New("centrysecrets: invalid encrypted vault")
	ErrSecretNotFound    = errors.New("centrysecrets: secret not found")
	ErrInvalidSecret     = errors.New("centrysecrets: secret value is not a string")
)

// Secret is one exact-name lookup result. Hidden reports which current vault
// collection supplied the value.
type Secret struct {
	Value  string
	Hidden bool
}

// Vault is an immutable, read-only snapshot. Concurrent exact-name lookups are
// safe. It exposes no enumeration or mutation API.
type Vault struct {
	regular map[string]json.RawMessage
	hidden  map[string]json.RawMessage
}

// OpenUnwrapped opens a vault whose centry.secrets_key data is the 44-byte
// URL-safe base64 Fernet key generated by cryptography.Fernet.generate_key.
func OpenUnwrapped(storedProjectKey, encryptedVault []byte) (*Vault, error) {
	projectKey, ok := decodeFernetKey(storedProjectKey)
	if !ok {
		return nil, ErrInvalidProjectKey
	}
	defer clearKey(&projectKey)

	return open(projectKey, encryptedVault)
}

// OpenWrapped opens a vault whose stored project key was encrypted by the
// explicitly supplied current-baseline master Fernet key. No key source is
// inferred and no environment variable is read.
func OpenWrapped(masterKey, encryptedProjectKey, encryptedVault []byte) (*Vault, error) {
	decodedMasterKey, ok := decodeFernetKey(masterKey)
	if !ok {
		return nil, ErrInvalidMasterKey
	}
	defer clearKey(&decodedMasterKey)

	storedProjectKey, ok := decryptFernet(decodedMasterKey, encryptedProjectKey)
	if !ok {
		return nil, ErrInvalidProjectKey
	}
	defer clearBytes(storedProjectKey)

	projectKey, ok := decodeFernetKey(storedProjectKey)
	if !ok {
		return nil, ErrInvalidProjectKey
	}
	defer clearKey(&projectKey)

	return open(projectKey, encryptedVault)
}

// Lookup returns only an exact key match. If a malformed vault contains the
// same name in both collections, the regular secret wins. That is the current
// EngineBase.get_all_secrets and project secret GET precedence.
func (v *Vault) Lookup(name string) (Secret, error) {
	if v == nil {
		return Secret{}, ErrInvalidVault
	}

	secret, err := v.LookupRegular(name)
	if err == nil || !errors.Is(err, ErrSecretNotFound) {
		return secret, err
	}
	if raw, ok := v.hidden[name]; ok {
		value, ok := decodeSecretString(raw)
		if !ok {
			return Secret{}, ErrInvalidSecret
		}
		return Secret{Value: value, Hidden: true}, nil
	}

	return Secret{}, ErrSecretNotFound
}

// LookupRegular returns only an exact regular-secret match. The current
// EngineBase exposes regular admin secrets as shared fallbacks but does not
// expose hidden admin secrets across projects, so callers must use this method
// for that compatibility boundary.
func (v *Vault) LookupRegular(name string) (Secret, error) {
	if v == nil {
		return Secret{}, ErrInvalidVault
	}
	if raw, ok := v.regular[name]; ok {
		value, ok := decodeSecretString(raw)
		if !ok {
			return Secret{}, ErrInvalidSecret
		}
		return Secret{Value: value}, nil
	}
	return Secret{}, ErrSecretNotFound
}

// LookupProjectID is the narrow compatibility accessor for current default-
// model project IDs. Those values have been persisted as either JSON strings
// or JSON integers. It returns canonical positive int32 decimal text while
// preserving regular-over-hidden precedence. Ordinary credential reads must
// continue to use Lookup so a numeric value cannot become a credential.
func (v *Vault) LookupProjectID(name string) (Secret, error) {
	if v == nil {
		return Secret{}, ErrInvalidVault
	}

	secret, err := v.LookupRegularProjectID(name)
	if err == nil || !errors.Is(err, ErrSecretNotFound) {
		return secret, err
	}
	if raw, ok := v.hidden[name]; ok {
		value, ok := decodeProjectID(raw)
		if !ok {
			return Secret{}, ErrInvalidSecret
		}
		return Secret{Value: value, Hidden: true}, nil
	}
	return Secret{}, ErrSecretNotFound
}

// LookupRegularProjectID is LookupProjectID without hidden-secret fallback.
func (v *Vault) LookupRegularProjectID(name string) (Secret, error) {
	if v == nil {
		return Secret{}, ErrInvalidVault
	}
	if raw, ok := v.regular[name]; ok {
		value, ok := decodeProjectID(raw)
		if !ok {
			return Secret{}, ErrInvalidSecret
		}
		return Secret{Value: value}, nil
	}
	return Secret{}, ErrSecretNotFound
}

// LookupRegularInteger is the narrow compatibility accessor for current vault
// settings whose Python consumers call int(value). It accepts regular-secret
// JSON strings and JSON numbers, returns canonical base-10 text, and never
// falls back to hidden secrets. Credential reads must continue to use
// LookupRegular so numeric values cannot become credentials accidentally.
func (v *Vault) LookupRegularInteger(name string) (Secret, error) {
	if v == nil {
		return Secret{}, ErrInvalidVault
	}
	if raw, ok := v.regular[name]; ok {
		value, ok := decodeInteger(raw)
		if !ok {
			return Secret{}, ErrInvalidSecret
		}
		return Secret{Value: value}, nil
	}
	return Secret{}, ErrSecretNotFound
}

func open(projectKey [fernetKeyBytes]byte, encryptedVault []byte) (*Vault, error) {
	defer clearKey(&projectKey)

	plaintext, ok := decryptFernet(projectKey, encryptedVault)
	if !ok {
		return nil, ErrInvalidVault
	}
	defer clearBytes(plaintext)

	vault, ok := parseVault(plaintext)
	if !ok {
		return nil, ErrInvalidVault
	}
	return vault, nil
}

type storedVault struct {
	Secrets       *map[string]json.RawMessage `json:"secrets"`
	HiddenSecrets *map[string]json.RawMessage `json:"hidden_secrets"`
}

func parseVault(plaintext []byte) (*Vault, bool) {
	var stored storedVault
	decoder := json.NewDecoder(bytes.NewReader(plaintext))
	decoder.DisallowUnknownFields()
	if err := decoder.Decode(&stored); err != nil {
		clearStoredVault(&stored)
		return nil, false
	}
	if err := expectJSONEnd(decoder); err != nil {
		clearStoredVault(&stored)
		return nil, false
	}
	if stored.Secrets == nil || stored.HiddenSecrets == nil {
		clearStoredVault(&stored)
		return nil, false
	}

	return &Vault{
		regular: *stored.Secrets,
		hidden:  *stored.HiddenSecrets,
	}, true
}

func expectJSONEnd(decoder *json.Decoder) error {
	var trailing struct{}
	err := decoder.Decode(&trailing)
	if errors.Is(err, io.EOF) {
		return nil
	}
	return ErrInvalidVault
}

func decodeSecretString(raw json.RawMessage) (string, bool) {
	trimmed := bytes.TrimSpace(raw)
	if len(trimmed) < 2 || trimmed[0] != '"' {
		return "", false
	}
	var value string
	if err := json.Unmarshal(trimmed, &value); err != nil {
		return "", false
	}
	return value, true
}

func decodeProjectID(raw json.RawMessage) (string, bool) {
	trimmed := bytes.TrimSpace(raw)
	if len(trimmed) == 0 || len(trimmed) > maxProjectIDJSON {
		return "", false
	}

	value := string(trimmed)
	if trimmed[0] == '"' {
		if err := json.Unmarshal(trimmed, &value); err != nil {
			return "", false
		}
		if value == "" {
			return "", true
		}
	}
	if len(value) == 0 || len(value) > maxProjectIDBytes {
		return "", false
	}
	for index := 0; index < len(value); index++ {
		if value[index] < '0' || value[index] > '9' {
			return "", false
		}
	}
	parsed, err := strconv.ParseInt(value, 10, 32)
	if err != nil || parsed <= 0 {
		return "", false
	}
	return strconv.FormatInt(parsed, 10), true
}

func decodeInteger(raw json.RawMessage) (string, bool) {
	trimmed := bytes.TrimSpace(raw)
	if len(trimmed) == 0 || len(trimmed) > maxProjectIDJSON {
		return "", false
	}
	value := string(trimmed)
	if trimmed[0] == '"' {
		if err := json.Unmarshal(trimmed, &value); err != nil {
			return "", false
		}
		value = strings.TrimSpace(value)
	}
	if parsed, err := strconv.ParseInt(value, 10, 64); err == nil {
		return strconv.FormatInt(parsed, 10), true
	}
	// Python int(JSON-number) also accepts an integral floating-point value.
	// Keep that compatibility narrow and reject NaN, infinities, fractions, and
	// values outside int64.
	parsedFloat, err := strconv.ParseFloat(value, 64)
	if err != nil || math.IsNaN(parsedFloat) || math.IsInf(parsedFloat, 0) ||
		math.Trunc(parsedFloat) != parsedFloat || parsedFloat < math.MinInt64 || parsedFloat >= float64(math.MaxInt64) {
		return "", false
	}
	return strconv.FormatInt(int64(parsedFloat), 10), true
}

func decodeFernetKey(encoded []byte) ([fernetKeyBytes]byte, bool) {
	var key [fernetKeyBytes]byte
	if len(encoded) != fernetEncodedKey {
		return key, false
	}

	var decoded [fernetEncodedKey]byte
	n, err := base64.URLEncoding.Decode(decoded[:], encoded)
	if err != nil || n != fernetKeyBytes {
		clearBytes(decoded[:])
		return key, false
	}
	copy(key[:], decoded[:n])
	clearBytes(decoded[:])
	return key, true
}

func decryptFernet(key [fernetKeyBytes]byte, token []byte) ([]byte, bool) {
	defer clearKey(&key)
	if len(token) == 0 {
		return nil, false
	}

	decoded := make([]byte, base64.URLEncoding.DecodedLen(len(token)))
	n, err := base64.URLEncoding.Decode(decoded, token)
	if err != nil {
		clearBytes(decoded)
		return nil, false
	}
	raw := decoded[:n]
	defer clearBytes(decoded)

	if len(raw) < fernetMinimumRaw || raw[0] != fernetVersion {
		return nil, false
	}
	ciphertext := raw[fernetHeaderBytes : len(raw)-fernetMACBytes]
	if len(ciphertext) == 0 || len(ciphertext)%aes.BlockSize != 0 {
		return nil, false
	}

	mac := hmac.New(sha256.New, key[:fernetKeyBytes/2])
	_, _ = mac.Write(raw[:len(raw)-fernetMACBytes])
	var signature [fernetMACBytes]byte
	mac.Sum(signature[:0])
	validSignature := hmac.Equal(signature[:], raw[len(raw)-fernetMACBytes:])
	clearBytes(signature[:])
	if !validSignature {
		return nil, false
	}

	block, err := aes.NewCipher(key[fernetKeyBytes/2:])
	if err != nil {
		return nil, false
	}
	plaintext := make([]byte, len(ciphertext))
	cipher.NewCBCDecrypter(block, raw[1+8:fernetHeaderBytes]).CryptBlocks(plaintext, ciphertext)
	unpadded, ok := removePKCS7Padding(plaintext)
	if !ok {
		clearBytes(plaintext)
		return nil, false
	}

	result := append([]byte(nil), unpadded...)
	clearBytes(plaintext)
	return result, true
}

func removePKCS7Padding(plaintext []byte) ([]byte, bool) {
	if len(plaintext) == 0 {
		return nil, false
	}
	padding := int(plaintext[len(plaintext)-1])
	if padding == 0 || padding > aes.BlockSize || padding > len(plaintext) {
		return nil, false
	}
	for _, value := range plaintext[len(plaintext)-padding:] {
		if int(value) != padding {
			return nil, false
		}
	}
	return plaintext[:len(plaintext)-padding], true
}

func clearStoredVault(stored *storedVault) {
	if stored == nil {
		return
	}
	clearRawMap(stored.Secrets)
	clearRawMap(stored.HiddenSecrets)
}

func clearRawMap(values *map[string]json.RawMessage) {
	if values == nil {
		return
	}
	for name, raw := range *values {
		clearBytes(raw)
		delete(*values, name)
	}
}

func clearKey(key *[fernetKeyBytes]byte) {
	if key != nil {
		clearBytes(key[:])
	}
}

func clearBytes(value []byte) {
	for index := range value {
		value[index] = 0
	}
}
