apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "elitea-main.fullname" . }}-config
  labels:
    {{- include "elitea-main.labels" . | nindent 4 }}
data:
  DATABASE_URL: {{ .Values.env.DATABASE_URL | quote }}
