#!/usr/bin/env python3
"""Regenerate testdata/centry/vault-key-format.json.

The fixture is a project vault written by the *real* Python implementation —
`cryptography.fernet`, driven exactly the way centry's secret engine drives it
(legacy/centry/pylon_main/plugins/shared/tools/secret_engines/database.py,
`_write_key` / `_write`):

    key    = Fernet.generate_key()                      # 44-byte base64 of 32 bytes
    row    = key                                        # no master key
    row    = Fernet(master).encrypt(key)                # with a master key
    data   = Fernet(key).encrypt(json.dumps(vault))

Two Go implementations in separate modules read these rows and must agree:
`services/elitea-main/internal/api/v2/secrets` (which also writes them) and
`services/elitea-llm-gateway/internal/account`. Each previously hard-coded its
own idea of the stored key format, and a test that round-tripped within one
implementation passed against the bug (see issues #194, #197). This fixture is
the shared ground truth neither of them authors.

Run from the repository root:

    python3 testdata/centry/generate-vault-key-format.py

Regenerating produces different bytes every time — Fernet tokens carry a random
IV and the current timestamp — so only regenerate when the *contract* changes,
not to refresh the file. The checked-in bytes are the point: they were produced
by Python, not by the Go code that consumes them.

The keys and secret values here are throwaway values generated for this fixture.
They protect nothing and are not used by any deployment.
"""

import base64
import json
import pathlib

from cryptography.fernet import Fernet

VAULT = {
    "secrets": {
        "OPENAI_API_KEY": "sk-fixture-not-a-real-credential",
        "chat_max_file_upload_size_mb": "25",
    },
    "hidden_secrets": {
        "HIDDEN_TOKEN": "hidden-fixture-not-a-real-credential",
    },
}

project_key = Fernet.generate_key()  # the secrets_key row when no master key is set
master_key = Fernet.generate_key()  # the SECRETS_MASTER_KEY env value, verbatim

plaintext = json.dumps(VAULT)

fixture = {
    "_comment": (
        "Generated by testdata/centry/generate-vault-key-format.py using Python "
        "cryptography.fernet, mirroring centry's secret engine. Values are "
        "throwaway. Every field below is the literal content of a database row "
        "or env var, ASCII as stored — except *_raw_bytes_b64std, which is "
        "standard base64 used only to carry raw bytes through JSON."
    ),
    "vault_plaintext": plaintext,
    "secrets_key_row_unwrapped": project_key.decode(),
    "secrets_key_row_wrapped": Fernet(master_key).encrypt(project_key).decode(),
    "secrets_data_row": Fernet(project_key).encrypt(plaintext.encode()).decode(),
    "master_key_env_value": master_key.decode(),
    "project_key_raw_bytes_b64std": base64.b64encode(
        base64.urlsafe_b64decode(project_key)
    ).decode(),
}

out = pathlib.Path(__file__).with_name("vault-key-format.json")
out.write_text(json.dumps(fixture, indent=2) + "\n")
print(f"wrote {out}")
