CREATE SCHEMA IF NOT EXISTS elitea_storage;

CREATE TABLE elitea_storage.buckets (
    id              BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    project_id      BIGINT      NOT NULL,
    name            TEXT        NOT NULL,
    display_name    TEXT        NOT NULL DEFAULT '',
    bucket_type     TEXT        NOT NULL DEFAULT 'local',
    is_pinned       BOOLEAN     NOT NULL DEFAULT FALSE,
    tags            JSONB       NOT NULL DEFAULT '{}'::jsonb,
    retention_days  INTEGER,
    expires_at      TIMESTAMPTZ,
    notified_at     TIMESTAMPTZ,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at      TIMESTAMPTZ,
    CONSTRAINT buckets_name_valid CHECK (name ~ '^[a-z][a-z0-9-]{1,62}$'),
    CONSTRAINT buckets_type_valid CHECK (bucket_type IN ('system','autogenerated','local'))
);
CREATE UNIQUE INDEX buckets_project_name_uniq
    ON elitea_storage.buckets (project_id, name) WHERE deleted_at IS NULL;

CREATE TABLE elitea_storage.objects (
    id             BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    bucket_id      BIGINT      NOT NULL REFERENCES elitea_storage.buckets(id) ON DELETE CASCADE,
    key            TEXT        NOT NULL,
    byte_length    BIGINT      NOT NULL,
    media_type     TEXT        NOT NULL DEFAULT 'application/octet-stream',
    digest_alg     TEXT,
    digest         BYTEA,
    classification TEXT        NOT NULL DEFAULT 'internal',
    scan_state     TEXT        NOT NULL DEFAULT 'not_scanned',
    expires_at     TIMESTAMPTZ,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT objects_key_len CHECK (octet_length(key) BETWEEN 1 AND 1024)
);
CREATE UNIQUE INDEX objects_bucket_key_uniq ON elitea_storage.objects (bucket_id, key);
CREATE INDEX objects_expiry ON elitea_storage.objects (expires_at) WHERE expires_at IS NOT NULL;

-- Required by S12 (quota) and S20a (attachment bucket name).
-- retention_default_days and retention_max_days are deliberately distinct:
-- the first is what a bucket gets when the caller omits a value, the second
-- is the ceiling S8's PATCH validates a caller-supplied value against. They
-- are not interchangeable — see S8.
CREATE TABLE elitea_storage.project_storage_policy (
    project_id             BIGINT PRIMARY KEY,
    max_object_bytes       BIGINT,
    max_total_bytes        BIGINT,
    retention_default_days INTEGER,
    retention_max_days     INTEGER, -- null means unlimited
    attachment_bucket      TEXT,
    updated_at             TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Required by S15 (presigned grants) and S20c (attestation commit).
CREATE TABLE elitea_storage.transfer_grants (
    id           UUID        PRIMARY KEY,
    project_id   BIGINT      NOT NULL,
    bucket_id    BIGINT      NOT NULL REFERENCES elitea_storage.buckets(id) ON DELETE CASCADE,
    key          TEXT        NOT NULL,
    method       TEXT        NOT NULL,
    content_type TEXT        NOT NULL DEFAULT '',
    max_bytes    BIGINT      NOT NULL,
    digest_alg   TEXT,
    digest       BYTEA,
    expires_at   TIMESTAMPTZ NOT NULL,
    consumed_at  TIMESTAMPTZ,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT grants_method_valid CHECK (method IN ('GET','PUT'))
);
CREATE INDEX grants_expiry ON elitea_storage.transfer_grants (expires_at);
