-- 0097_scim_group_bindings.sql — the tables SCIM 2.0 GROUP provisioning needs:
-- the authored binding of one identity provider group to one project role, and
-- the ledger of what a push granted.
--
-- WHAT THIS REVERSES. 0096 shipped `/Users` and REFUSED `/Groups` with 501, and
-- ADR-0020 decision 8 recorded the refusal. The reason given was true about the
-- data: a SCIM group carries a flat name and a member list, this platform's
-- membership is always (user, PROJECT, ROLE), and nothing in the group says
-- which project or which role. The refusal was the right answer while the
-- missing half was unknown.
--
-- The missing half is now authored HERE, by an administrator, before any push
-- arrives. A SCIM group maps to a project, its members are that project's
-- users, and the role they receive is the one on the binding row. The identity
-- provider supplies the membership; it never supplies the project or the role,
-- and it can never invent either. ADR-0020's decision 8 is superseded by
-- ADR-0021, which records this.
--
-- WHY A PUSH CANNOT CREATE A PROJECT. Provisioning a project is the multi-step
-- act in internal/application/projectprovisioning: a tenant schema, four roles,
-- a machine identity and its token, secrets, buckets, a vhost and quotas, any
-- step of which can fail halfway. An unbound group is REFUSED and named, so an
-- operator sees which group has no binding, rather than the push quietly
-- building infrastructure nobody asked for.
--
-- WHY A PUSH CANNOT DELETE A PROJECT. The same reason `/Users` deactivates
-- rather than deletes: a project holds everyone's work. `DELETE /Groups/{id}`
-- withdraws the access this group granted and removes the binding. The project,
-- its members added by hand, and its content are untouched.
--
-- NO FOREIGN KEY TO `auth_core__*` OR `centry.*`, and this is the rule 0094,
-- 0095 and 0096 all state. It is not a preference. `migrate.ApplyShared` runs
-- this corpus against a database that may hold nothing else — every `dbtest`
-- template does exactly that — and those tables belong to a DIFFERENT corpus
-- (internal/infra/db/migrations/001_initial.sql) or to pylon's own migrations.
-- 0096's header records the 42P01 that a `REFERENCES auth_core__user(id)`
-- caused, and the six unrelated suites it took down with it.
--
-- The foreign key BETWEEN THE TWO TABLES BELOW is present, because both are
-- created by this file. It carries the cascade that keeps the ledger from
-- outliving the binding it describes.
--
-- IDEMPOTENT throughout. No BEGIN/COMMIT: the ledgered runner executes each file
-- inside one transaction with its ledger row (migrate/runner.go apply).

CREATE SCHEMA IF NOT EXISTS elitea_auth;

CREATE TABLE IF NOT EXISTS elitea_auth.scim_group_bindings (
    -- id is the SCIM Group resource id, which is why it is generated here and
    -- not taken from the identity provider. A SCIM client stores the id the
    -- service provider returns and addresses `/Groups/{id}` with it forever
    -- after, so the id must belong to the row an administrator authored — not
    -- to a name the provider can rename.
    id           bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- display_name is the SCIM `displayName`, and it is the MATCH KEY for the
    -- first push. An administrator types the group name their identity provider
    -- sends; the push finds the binding by that name and then remembers the id.
    display_name text        NOT NULL,
    -- external_id is the identity provider's own identifier for the group. It
    -- is empty until a push arrives, and it is the preferred match once set: a
    -- group renamed at the provider keeps its external id, and matching on it
    -- means the rename lands on the binding it belongs to instead of failing as
    -- an unknown group.
    external_id  text        NOT NULL DEFAULT '',
    -- project_id names the project the group's members join. NOT a foreign key;
    -- see the header. It is validated at the write, where `centry.project` is
    -- readable, and the admin surface refuses an id that names no project.
    project_id   integer     NOT NULL,
    -- role_name is the project role every member of this group receives, by
    -- NAME rather than by `auth_core__project_role.id`. The id is per project
    -- and is re-created when a project is re-provisioned; the name (`admin`,
    -- `editor`, `viewer`, `system`) is what an operator authors and what
    -- projectprovisioning creates. The id is resolved at each write, and a role
    -- that no longer exists on the project is a refusal that names both.
    role_name    text        NOT NULL,
    created_at   timestamptz NOT NULL DEFAULT now(),
    updated_at   timestamptz NOT NULL DEFAULT now()
);

-- One binding per group name, case-insensitively. Two bindings for one name
-- would make the first push's lookup ambiguous, and it would resolve to
-- whichever row the database returned first — that is, to a project chosen at
-- random from two.
CREATE UNIQUE INDEX IF NOT EXISTS scim_group_bindings_display_name_uniq
    ON elitea_auth.scim_group_bindings (lower(display_name));

-- One binding per external id, for the same reason. An empty external id is not
-- constrained: it means "no push has arrived yet", and every unpushed binding
-- would otherwise collide with every other.
CREATE UNIQUE INDEX IF NOT EXISTS scim_group_bindings_external_id_uniq
    ON elitea_auth.scim_group_bindings (external_id)
    WHERE external_id <> '';

CREATE TABLE IF NOT EXISTS elitea_auth.scim_group_members (
    -- WHAT THIS TABLE IS FOR. It is the ledger of what the identity provider
    -- granted, and it exists so that a sync can remove what the provider gave
    -- and NOTHING ELSE. Without it the only way to apply a member removal would
    -- be to delete every `auth_core__project_user_role` row for the bound role,
    -- which would evict the people an administrator added by hand on the
    -- project's own members screen — silently, on a routine push.
    binding_id bigint      NOT NULL
                           REFERENCES elitea_auth.scim_group_bindings (id) ON DELETE CASCADE,
    user_id    integer     NOT NULL,
    -- role_id is the `auth_core__project_role` row that was actually granted,
    -- recorded as it was at grant time. A revoke deletes the membership row it
    -- created, and it must delete THAT row rather than re-resolve the name — a
    -- binding edited between the grant and the revoke would otherwise leave the
    -- old grant standing forever.
    role_id    integer     NOT NULL,
    -- granted records whether this push CREATED the membership row. False means
    -- the person already held that role on that project when the push arrived,
    -- by an invitation or an administrator's edit. A revoke leaves such a row
    -- alone: the provider is authoritative over what it gave, not over what it
    -- found.
    granted    boolean     NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (binding_id, user_id)
);

-- The revoke path asks "does another binding still claim this membership?"
-- before it deletes a membership row, so that two groups bound to the same
-- project role do not take each other's members away.
CREATE INDEX IF NOT EXISTS scim_group_members_claim_idx
    ON elitea_auth.scim_group_members (user_id, role_id);
