#!/usr/bin/env python3
"""Re-copy the engine from the legacy checkout and record its digests.

The engine under ``src/elitea_deepwiki/engine/`` is a plain copy of
``deepwiki_plugin/plugin_implementation/``. This tool performs that copy and
writes ``COPY_MANIFEST.json`` beside it, which
``tests/engine/test_copy_is_verbatim.py`` then enforces.

Two modes:

    python tools/refresh_engine_copy.py            re-copy and rewrite the manifest
    python tools/refresh_engine_copy.py --check    verify the copy against the manifest

``--check`` needs no legacy checkout — it hashes what is committed here — so it
is what CI runs. The default mode needs the legacy tree and is how a deliberate
re-sync is performed.

``__init__.py`` is never copied: the legacy one was empty and ours installs the
``plugin_implementation`` compatibility alias. It is excluded from the manifest
for the same reason.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import shutil
import subprocess
import sys
from pathlib import Path

SERVICE_ROOT = Path(__file__).resolve().parents[1]
ENGINE_DIR = SERVICE_ROOT / "src" / "elitea_deepwiki" / "engine"
MANIFEST = ENGINE_DIR / "COPY_MANIFEST.json"

#: ``methods/tool_operations.py`` is the tool layer: the real ``generate_wiki``
#: / ``ask`` / ``deep_research`` implementations, the subprocess and Job launch
#: paths, and the worker-slot accounting. It lives under ``methods/`` in the
#: legacy tree, so it looked like part of the Pylon shim — but it is not. It
#: needs exactly five things from the Pylon module (``invocation_thinking``,
#: ``invocation_stop_checkpoint``, ``invocation_process_add/remove``,
#: ``runtime_config``) and this service supplies all five.
#:
#: It cannot be copied byte for byte, because it imports Pylon at module scope
#: and decorates seven methods with ``@web.method()``. ADR-0022 decision 1 says
#: nothing of Pylon survives into the service, so rather than shipping a fake
#: ``pylon`` package to keep the copy literal, the two constructs are removed
#: by the declared substitutions below. They are mechanical and reproducible:
#: re-running this tool against the legacy source regenerates the file byte for
#: byte, and ``--check`` verifies both the transformed result AND the digest of
#: the source it was derived from.
TOOLS_SOURCE = "methods/tool_operations.py"
TOOLS_TARGET = SERVICE_ROOT / "src" / "elitea_deepwiki" / "tool_operations.py"

TOOLS_HEADER = '''# Copied from deepwiki_plugin methods/tool_operations.py.
#
# Generated by tools/refresh_engine_copy.py — do not edit by hand. Two declared
# substitutions are applied to the legacy source and nothing else:
#
#   1. `from pylon.core.tools import log, web` becomes a stdlib logger.
#   2. The seven `@web.method()` decorators are removed.
#   3. `from ..plugin_implementation.` becomes `from .engine.` (5 sites).
#   4. The three subprocess worker module names become their real dotted
#      names in this package (3 sites).
#
# Both exist because ADR-0022 decision 1 keeps Pylon out of the service. The
# class below is otherwise the legacy `Method` mixin unchanged, and it binds to
# any host object providing runtime_config(), invocation_thinking(),
# invocation_stop_checkpoint() and invocation_process_add/remove() —
# see elitea_deepwiki.legacy_runner.ToolHost.
'''

#: Files transformed IN PLACE inside the engine tree. Unlike tool_operations.py
#: these cannot move: engine modules import them relatively
#: (``from .artifacts_platform_client import ...``), so relocating one would
#: break the copy. They are excluded from the verbatim digest set and recorded
#: under ``transformed_files`` instead, with the substitutions that produced
#: them, so the edit is auditable rather than invisible.
#:
#: ADR-0022 decision 6 is why this one is here: "the legacy X-SECRET
#: shared-string header is retired; no surface of the ported service sends or
#: honours it" and "TLS verification is mandatory on every outbound call.
#: verify=False does not appear in the ported code." Both were still true of
#: the copied client, which is a violation of the ADR in shipped code — found
#: by grepping the copy for the claim the README was making about it.
IN_PLACE_TRANSFORMS = {
    "artifacts_platform_client.py": (
        # The X-SECRET header, gone from every outbound artifact call. The
        # value it carried defaulted to the literal string "secret".
        (
            '        return {\n'
            '            "Authorization": f"Bearer {self.api_key}",\n'
            '            "X-SECRET": self.x_secret,\n'
            '        }',
            '        return {\n'
            '            "Authorization": f"Bearer {self.api_key}",\n'
            '        }',
        ),
        # TLS verification, on. _TLS_VERIFY is True by default and takes a CA
        # bundle path from the environment, because an internal mTLS mesh
        # signs with a private CA that the system trust store does not carry.
        (
            'DEFAULT_BUCKET = "wiki-artifacts"',
            'def _tls_verify():\n'
            '    """CA bundle path, or True for the system trust store."""\n'
            '    return os.environ.get("ELITEA_DEEPWIKI_TLS_CA_FILE") or True\n'
            '\n'
            '\n'
            'DEFAULT_BUCKET = "wiki-artifacts"',
        ),
        ("verify=False", "verify=_tls_verify()"),
    ),
}

TOOLS_SUBSTITUTIONS = (
    (
        "from pylon.core.tools import log, web",
        "import logging\n\nlog = logging.getLogger(__name__)",
    ),
    ("    @web.method()\n", ""),
    # The legacy file sat at deepwiki_plugin/methods/, so `..` reached the
    # plugin root and `..plugin_implementation` was the engine. Here it sits at
    # elitea_deepwiki/, one level higher, and `..` escapes the package. Found
    # by running generate_wiki, not by reading: the import is inside a function
    # a third of the way through the tool.
    ("from ..plugin_implementation.", "from .engine."),
    # The subprocess launcher picks a worker module name by trying to import
    # each candidate IN THE PARENT, then hands the winner to a child that only
    # gets the parent's sys.path. In the parent, "plugin_implementation.X"
    # imports fine — the engine package installs that alias — but the child
    # never imports the engine package, so the alias does not exist there and
    # the name is unresolvable. Naming the real module makes the child import
    # something sys.path can actually find, and importing it installs the alias
    # for the engine's own absolute imports. Diagnosed by running the
    # subprocess path and reading the worker log:
    #   ModuleNotFoundError: No module named 'plugin_implementation'
    ('"plugin_implementation.wiki_subprocess_worker"', '"elitea_deepwiki.engine.wiki_subprocess_worker"'),
    ('"plugin_implementation.ask_subprocess_worker"', '"elitea_deepwiki.engine.ask_subprocess_worker"'),
    ('"plugin_implementation.deep_research_subprocess_worker"', '"elitea_deepwiki.engine.deep_research_subprocess_worker"'),
)

#: Owned by this repository, not copied. These are RELATIVE PATHS, not bare
#: names: the engine has eight subpackage ``__init__.py`` files that ARE part
#: of the copy, and matching on the name alone would silently drop every one of
#: them from the manifest — leaving them unguarded while the count still looked
#: plausible.
NOT_COPIED = {"__init__.py", "COPY_MANIFEST.json"}

LEGACY_ENV_VAR = "DEEPWIKI_LEGACY_ROOT"
_DEFAULT_CANDIDATES = (
    "projects/eliteaai/legacy/plugins/deepwiki_plugin",
    "eliteaai/legacy/plugins/deepwiki_plugin",
)


def legacy_root() -> Path:
    import os

    override = os.environ.get(LEGACY_ENV_VAR)
    if override:
        path = Path(override).expanduser().resolve()
        if (path / "plugin_implementation").is_dir():
            return path
        raise SystemExit(f"{LEGACY_ENV_VAR}={path} is not a deepwiki_plugin checkout")

    for candidate in _DEFAULT_CANDIDATES:
        path = (Path.home() / candidate).resolve()
        if (path / "plugin_implementation").is_dir():
            return path

    raise SystemExit(
        f"deepwiki_plugin checkout not found; set {LEGACY_ENV_VAR} "
        "(read-only access is enough)"
    )


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(65536), b""):
            digest.update(block)
    return digest.hexdigest()


def copied_files() -> list[Path]:
    """Every file the manifest covers, relative to the engine directory."""
    return sorted(
        path
        for path in ENGINE_DIR.rglob("*")
        if path.is_file()
        and "__pycache__" not in path.parts
        and path.relative_to(ENGINE_DIR).as_posix() not in NOT_COPIED
        and path.relative_to(ENGINE_DIR).as_posix() not in IN_PLACE_TRANSFORMS
    )


def transform_tools(source_text: str) -> str:
    """Apply the declared substitutions to the tool layer's source."""
    text = source_text
    for needle, replacement in TOOLS_SUBSTITUTIONS:
        if needle not in text:
            raise SystemExit(
                f"tool_operations.py no longer contains {needle!r}; the "
                "declared substitutions are stale and must be reviewed"
            )
        text = text.replace(needle, replacement)
    return TOOLS_HEADER + text


def build_manifest(revision: str | None) -> dict:
    entries = {}
    for path in copied_files():
        relative = path.relative_to(ENGINE_DIR).as_posix()
        entries[relative] = {"bytes": path.stat().st_size, "sha256": sha256(path)}

    transformed = {}
    for relative, substitutions in IN_PLACE_TRANSFORMS.items():
        target = ENGINE_DIR / relative
        if not target.is_file():
            continue
        transformed[f"plugin_implementation/{relative}"] = {
            "target": target.relative_to(SERVICE_ROOT).as_posix(),
            "bytes": target.stat().st_size,
            "sha256": sha256(target),
            "in_place": True,
            "substitutions": [
                {"from": needle, "to": replacement}
                for needle, replacement in substitutions
            ],
        }

    if TOOLS_TARGET.is_file():
        transformed[TOOLS_SOURCE] = {
            "target": TOOLS_TARGET.relative_to(SERVICE_ROOT).as_posix(),
            "bytes": TOOLS_TARGET.stat().st_size,
            "sha256": sha256(TOOLS_TARGET),
            "substitutions": [
                {"from": needle, "to": replacement}
                for needle, replacement in TOOLS_SUBSTITUTIONS
            ],
        }

    return {
        "source_repository": "deepwiki_plugin",
        "source_path": "plugin_implementation",
        "source_revision": revision,
        "file_count": len(entries),
        "total_bytes": sum(entry["bytes"] for entry in entries.values()),
        "not_copied": sorted(NOT_COPIED),
        "files": entries,
        "transformed_files": transformed,
    }


def do_copy() -> str | None:
    root = legacy_root()
    source = root / "plugin_implementation"

    try:
        revision = subprocess.run(
            ["git", "-C", str(root), "rev-parse", "HEAD"],
            capture_output=True,
            text=True,
            check=True,
        ).stdout.strip()
    except (OSError, subprocess.CalledProcessError):
        revision = None

    keep = {}
    for name in NOT_COPIED:
        path = ENGINE_DIR / name
        if path.is_file():
            keep[name] = path.read_bytes()

    if ENGINE_DIR.exists():
        shutil.rmtree(ENGINE_DIR)
    shutil.copytree(
        source, ENGINE_DIR, ignore=shutil.ignore_patterns("__pycache__", "*.pyc")
    )

    for name in NOT_COPIED:
        target = ENGINE_DIR / name
        if name in keep:
            target.write_bytes(keep[name])
        elif target.is_file():
            target.unlink()

    TOOLS_TARGET.write_text(
        transform_tools((root / TOOLS_SOURCE).read_text(encoding="utf-8")),
        encoding="utf-8",
    )

    for relative, substitutions in IN_PLACE_TRANSFORMS.items():
        target = ENGINE_DIR / relative
        text = target.read_text(encoding="utf-8")
        for needle, replacement in substitutions:
            if needle not in text:
                raise SystemExit(
                    f"{relative} no longer contains {needle!r}; the declared "
                    "in-place substitutions are stale and must be reviewed"
                )
            text = text.replace(needle, replacement)
        target.write_text(text, encoding="utf-8")

    return revision


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify the committed copy against the manifest (no legacy checkout needed)",
    )
    args = parser.parse_args()

    if args.check:
        if not MANIFEST.is_file():
            print(f"{MANIFEST} is missing", file=sys.stderr)
            return 1
        manifest = json.loads(MANIFEST.read_text(encoding="utf-8"))
        current = build_manifest(manifest.get("source_revision"))

        if current.get("transformed_files") != manifest.get("transformed_files"):
            print(
                "  modified: the transformed tool layer no longer matches its "
                "manifest entry",
                file=sys.stderr,
            )
            return 1

        if current["files"] == manifest["files"]:
            print(f"engine copy is verbatim ({current['file_count']} files)")
            return 0

        expected = set(manifest["files"])
        present = set(current["files"])
        for name in sorted(present - expected):
            print(f"  extra:    {name}", file=sys.stderr)
        for name in sorted(expected - present):
            print(f"  missing:  {name}", file=sys.stderr)
        for name in sorted(expected & present):
            if manifest["files"][name] != current["files"][name]:
                print(f"  modified: {name}", file=sys.stderr)
        return 1

    revision = do_copy()
    manifest = build_manifest(revision)
    MANIFEST.write_text(
        json.dumps(manifest, indent=2, ensure_ascii=False) + "\n", encoding="utf-8"
    )
    print(
        f"copied {manifest['file_count']} files "
        f"({manifest['total_bytes']} bytes) from {revision}, "
        f"plus {len(manifest['transformed_files'])} transformed"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
