// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: artifact_storage.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countArtifactBucketObjects = `-- name: CountArtifactBucketObjects :one
SELECT COUNT(*)::bigint
FROM elitea_storage.objects o
JOIN elitea_storage.buckets b ON b.id = o.bucket_id
WHERE o.bucket_id = $1 AND b.deleted_at IS NULL
`

func (q *Queries) CountArtifactBucketObjects(ctx context.Context, bucketID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countArtifactBucketObjects, bucketID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createArtifactBucket = `-- name: CreateArtifactBucket :one
INSERT INTO elitea_storage.buckets (
    project_id, name, display_name, bucket_type, retention_days, expires_at
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, project_id, name, display_name, bucket_type, is_pinned, tags,
    retention_days, expires_at, notified_at, created_at, updated_at, deleted_at
`

type CreateArtifactBucketParams struct {
	ProjectID     int64              `db:"project_id" json:"project_id"`
	Name          string             `db:"name" json:"name"`
	DisplayName   string             `db:"display_name" json:"display_name"`
	BucketType    string             `db:"bucket_type" json:"bucket_type"`
	RetentionDays *int32             `db:"retention_days" json:"retention_days"`
	ExpiresAt     pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
}

func (q *Queries) CreateArtifactBucket(ctx context.Context, arg CreateArtifactBucketParams) (EliteaStorageBucket, error) {
	row := q.db.QueryRow(ctx, createArtifactBucket,
		arg.ProjectID,
		arg.Name,
		arg.DisplayName,
		arg.BucketType,
		arg.RetentionDays,
		arg.ExpiresAt,
	)
	var i EliteaStorageBucket
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.DisplayName,
		&i.BucketType,
		&i.IsPinned,
		&i.Tags,
		&i.RetentionDays,
		&i.ExpiresAt,
		&i.NotifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteArtifactObjectRows = `-- name: DeleteArtifactObjectRows :execrows
DELETE FROM elitea_storage.objects WHERE id = ANY($1::bigint[])
`

func (q *Queries) DeleteArtifactObjectRows(ctx context.Context, ids []int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteArtifactObjectRows, ids)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteArtifactObjects = `-- name: DeleteArtifactObjects :execrows
DELETE FROM elitea_storage.objects
WHERE bucket_id = $1 AND key = ANY($2::text[])
`

type DeleteArtifactObjectsParams struct {
	BucketID int64    `db:"bucket_id" json:"bucket_id"`
	Keys     []string `db:"keys" json:"keys"`
}

func (q *Queries) DeleteArtifactObjects(ctx context.Context, arg DeleteArtifactObjectsParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteArtifactObjects, arg.BucketID, arg.Keys)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getArtifactBucket = `-- name: GetArtifactBucket :one
SELECT id, project_id, name, display_name, bucket_type, is_pinned, tags,
       retention_days, expires_at, notified_at, created_at, updated_at, deleted_at
FROM elitea_storage.buckets
WHERE project_id = $1 AND name = $2 AND deleted_at IS NULL
`

type GetArtifactBucketParams struct {
	ProjectID int64  `db:"project_id" json:"project_id"`
	Name      string `db:"name" json:"name"`
}

func (q *Queries) GetArtifactBucket(ctx context.Context, arg GetArtifactBucketParams) (EliteaStorageBucket, error) {
	row := q.db.QueryRow(ctx, getArtifactBucket, arg.ProjectID, arg.Name)
	var i EliteaStorageBucket
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.DisplayName,
		&i.BucketType,
		&i.IsPinned,
		&i.Tags,
		&i.RetentionDays,
		&i.ExpiresAt,
		&i.NotifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getArtifactProjectStoragePolicy = `-- name: GetArtifactProjectStoragePolicy :one
SELECT project_id, max_object_bytes, max_total_bytes, retention_default_days,
       retention_max_days, attachment_bucket, updated_at
FROM elitea_storage.project_storage_policy
WHERE project_id = $1
`

func (q *Queries) GetArtifactProjectStoragePolicy(ctx context.Context, projectID int64) (EliteaStorageProjectStoragePolicy, error) {
	row := q.db.QueryRow(ctx, getArtifactProjectStoragePolicy, projectID)
	var i EliteaStorageProjectStoragePolicy
	err := row.Scan(
		&i.ProjectID,
		&i.MaxObjectBytes,
		&i.MaxTotalBytes,
		&i.RetentionDefaultDays,
		&i.RetentionMaxDays,
		&i.AttachmentBucket,
		&i.UpdatedAt,
	)
	return i, err
}

const listArtifactBuckets = `-- name: ListArtifactBuckets :many
SELECT id, project_id, name, display_name, bucket_type, is_pinned, tags,
       retention_days, expires_at, notified_at, created_at, updated_at, deleted_at
FROM elitea_storage.buckets
WHERE project_id = $1 AND deleted_at IS NULL
ORDER BY name
`

func (q *Queries) ListArtifactBuckets(ctx context.Context, projectID int64) ([]EliteaStorageBucket, error) {
	rows, err := q.db.Query(ctx, listArtifactBuckets, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EliteaStorageBucket{}
	for rows.Next() {
		var i EliteaStorageBucket
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.DisplayName,
			&i.BucketType,
			&i.IsPinned,
			&i.Tags,
			&i.RetentionDays,
			&i.ExpiresAt,
			&i.NotifiedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArtifactBucketsNeedingExpiryNotice = `-- name: ListArtifactBucketsNeedingExpiryNotice :many
SELECT id, project_id, name, display_name, bucket_type, is_pinned, tags,
       retention_days, expires_at, notified_at, created_at, updated_at, deleted_at
FROM elitea_storage.buckets
WHERE deleted_at IS NULL
  AND expires_at IS NOT NULL
  AND expires_at <= $1
  AND notified_at IS NULL
ORDER BY expires_at
LIMIT $2
`

type ListArtifactBucketsNeedingExpiryNoticeParams struct {
	ExpiresAt pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	Limit     int32              `db:"limit" json:"limit"`
}

func (q *Queries) ListArtifactBucketsNeedingExpiryNotice(ctx context.Context, arg ListArtifactBucketsNeedingExpiryNoticeParams) ([]EliteaStorageBucket, error) {
	rows, err := q.db.Query(ctx, listArtifactBucketsNeedingExpiryNotice, arg.ExpiresAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EliteaStorageBucket{}
	for rows.Next() {
		var i EliteaStorageBucket
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.DisplayName,
			&i.BucketType,
			&i.IsPinned,
			&i.Tags,
			&i.RetentionDays,
			&i.ExpiresAt,
			&i.NotifiedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArtifactObjects = `-- name: ListArtifactObjects :many
SELECT id, bucket_id, key, byte_length, media_type, digest_alg, digest,
       classification, scan_state, expires_at, created_at, updated_at
FROM elitea_storage.objects
WHERE bucket_id = $1
  AND ($2::text = '' OR key LIKE $2::text || '%')
ORDER BY key
`

type ListArtifactObjectsParams struct {
	BucketID  int64  `db:"bucket_id" json:"bucket_id"`
	KeyPrefix string `db:"key_prefix" json:"key_prefix"`
}

func (q *Queries) ListArtifactObjects(ctx context.Context, arg ListArtifactObjectsParams) ([]EliteaStorageObject, error) {
	rows, err := q.db.Query(ctx, listArtifactObjects, arg.BucketID, arg.KeyPrefix)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EliteaStorageObject{}
	for rows.Next() {
		var i EliteaStorageObject
		if err := rows.Scan(
			&i.ID,
			&i.BucketID,
			&i.Key,
			&i.ByteLength,
			&i.MediaType,
			&i.DigestAlg,
			&i.Digest,
			&i.Classification,
			&i.ScanState,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpiredArtifactObjects = `-- name: ListExpiredArtifactObjects :many
SELECT id, bucket_id, key, byte_length, media_type, digest_alg, digest,
       classification, scan_state, expires_at, created_at, updated_at
FROM elitea_storage.objects
WHERE expires_at IS NOT NULL AND expires_at < $1
ORDER BY expires_at
LIMIT $2
`

type ListExpiredArtifactObjectsParams struct {
	ExpiresAt pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	Limit     int32              `db:"limit" json:"limit"`
}

func (q *Queries) ListExpiredArtifactObjects(ctx context.Context, arg ListExpiredArtifactObjectsParams) ([]EliteaStorageObject, error) {
	rows, err := q.db.Query(ctx, listExpiredArtifactObjects, arg.ExpiresAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EliteaStorageObject{}
	for rows.Next() {
		var i EliteaStorageObject
		if err := rows.Scan(
			&i.ID,
			&i.BucketID,
			&i.Key,
			&i.ByteLength,
			&i.MediaType,
			&i.DigestAlg,
			&i.Digest,
			&i.Classification,
			&i.ScanState,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markArtifactBucketNotified = `-- name: MarkArtifactBucketNotified :execrows
UPDATE elitea_storage.buckets
SET notified_at = now()
WHERE id = $1
`

func (q *Queries) MarkArtifactBucketNotified(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, markArtifactBucketNotified, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setArtifactBucketPinned = `-- name: SetArtifactBucketPinned :one
UPDATE elitea_storage.buckets
SET is_pinned = $2, updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, project_id, name, display_name, bucket_type, is_pinned, tags,
    retention_days, expires_at, notified_at, created_at, updated_at, deleted_at
`

type SetArtifactBucketPinnedParams struct {
	ID       int64 `db:"id" json:"id"`
	IsPinned bool  `db:"is_pinned" json:"is_pinned"`
}

func (q *Queries) SetArtifactBucketPinned(ctx context.Context, arg SetArtifactBucketPinnedParams) (EliteaStorageBucket, error) {
	row := q.db.QueryRow(ctx, setArtifactBucketPinned, arg.ID, arg.IsPinned)
	var i EliteaStorageBucket
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.DisplayName,
		&i.BucketType,
		&i.IsPinned,
		&i.Tags,
		&i.RetentionDays,
		&i.ExpiresAt,
		&i.NotifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const softDeleteArtifactBucket = `-- name: SoftDeleteArtifactBucket :execrows
UPDATE elitea_storage.buckets
SET deleted_at = now(), updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteArtifactBucket(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteArtifactBucket, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const sumArtifactBucketBytes = `-- name: SumArtifactBucketBytes :one
SELECT COALESCE(SUM(o.byte_length), 0)::bigint
FROM elitea_storage.objects o
JOIN elitea_storage.buckets b ON b.id = o.bucket_id
WHERE o.bucket_id = $1 AND b.deleted_at IS NULL
`

func (q *Queries) SumArtifactBucketBytes(ctx context.Context, bucketID int64) (int64, error) {
	row := q.db.QueryRow(ctx, sumArtifactBucketBytes, bucketID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const sumArtifactProjectBytes = `-- name: SumArtifactProjectBytes :one
SELECT COALESCE(SUM(o.byte_length), 0)::bigint
FROM elitea_storage.objects o
JOIN elitea_storage.buckets b ON b.id = o.bucket_id
WHERE b.project_id = $1 AND b.deleted_at IS NULL
`

func (q *Queries) SumArtifactProjectBytes(ctx context.Context, projectID int64) (int64, error) {
	row := q.db.QueryRow(ctx, sumArtifactProjectBytes, projectID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const updateArtifactBucketRetention = `-- name: UpdateArtifactBucketRetention :one
UPDATE elitea_storage.buckets
SET retention_days = $2, expires_at = $3, updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, project_id, name, display_name, bucket_type, is_pinned, tags,
    retention_days, expires_at, notified_at, created_at, updated_at, deleted_at
`

type UpdateArtifactBucketRetentionParams struct {
	ID            int64              `db:"id" json:"id"`
	RetentionDays *int32             `db:"retention_days" json:"retention_days"`
	ExpiresAt     pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
}

func (q *Queries) UpdateArtifactBucketRetention(ctx context.Context, arg UpdateArtifactBucketRetentionParams) (EliteaStorageBucket, error) {
	row := q.db.QueryRow(ctx, updateArtifactBucketRetention, arg.ID, arg.RetentionDays, arg.ExpiresAt)
	var i EliteaStorageBucket
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.DisplayName,
		&i.BucketType,
		&i.IsPinned,
		&i.Tags,
		&i.RetentionDays,
		&i.ExpiresAt,
		&i.NotifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateArtifactBucketTags = `-- name: UpdateArtifactBucketTags :one
UPDATE elitea_storage.buckets
SET tags = $2, updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, project_id, name, display_name, bucket_type, is_pinned, tags,
    retention_days, expires_at, notified_at, created_at, updated_at, deleted_at
`

type UpdateArtifactBucketTagsParams struct {
	ID   int64  `db:"id" json:"id"`
	Tags []byte `db:"tags" json:"tags"`
}

func (q *Queries) UpdateArtifactBucketTags(ctx context.Context, arg UpdateArtifactBucketTagsParams) (EliteaStorageBucket, error) {
	row := q.db.QueryRow(ctx, updateArtifactBucketTags, arg.ID, arg.Tags)
	var i EliteaStorageBucket
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.DisplayName,
		&i.BucketType,
		&i.IsPinned,
		&i.Tags,
		&i.RetentionDays,
		&i.ExpiresAt,
		&i.NotifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const upsertArtifactObject = `-- name: UpsertArtifactObject :one
INSERT INTO elitea_storage.objects (
    bucket_id, key, byte_length, media_type, digest_alg, digest,
    classification, scan_state, expires_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
ON CONFLICT (bucket_id, key) DO UPDATE SET
    byte_length = EXCLUDED.byte_length,
    media_type = EXCLUDED.media_type,
    digest_alg = EXCLUDED.digest_alg,
    digest = EXCLUDED.digest,
    classification = EXCLUDED.classification,
    scan_state = EXCLUDED.scan_state,
    expires_at = EXCLUDED.expires_at,
    updated_at = now()
RETURNING id, bucket_id, key, byte_length, media_type, digest_alg, digest,
    classification, scan_state, expires_at, created_at, updated_at
`

type UpsertArtifactObjectParams struct {
	BucketID       int64              `db:"bucket_id" json:"bucket_id"`
	Key            string             `db:"key" json:"key"`
	ByteLength     int64              `db:"byte_length" json:"byte_length"`
	MediaType      string             `db:"media_type" json:"media_type"`
	DigestAlg      *string            `db:"digest_alg" json:"digest_alg"`
	Digest         []byte             `db:"digest" json:"digest"`
	Classification string             `db:"classification" json:"classification"`
	ScanState      string             `db:"scan_state" json:"scan_state"`
	ExpiresAt      pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
}

func (q *Queries) UpsertArtifactObject(ctx context.Context, arg UpsertArtifactObjectParams) (EliteaStorageObject, error) {
	row := q.db.QueryRow(ctx, upsertArtifactObject,
		arg.BucketID,
		arg.Key,
		arg.ByteLength,
		arg.MediaType,
		arg.DigestAlg,
		arg.Digest,
		arg.Classification,
		arg.ScanState,
		arg.ExpiresAt,
	)
	var i EliteaStorageObject
	err := row.Scan(
		&i.ID,
		&i.BucketID,
		&i.Key,
		&i.ByteLength,
		&i.MediaType,
		&i.DigestAlg,
		&i.Digest,
		&i.Classification,
		&i.ScanState,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
