// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: artifact_transfer_grants.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimExpiredArtifactTransferGrants = `-- name: ClaimExpiredArtifactTransferGrants :many
UPDATE elitea_storage.transfer_grants
SET consumed_at = now()
WHERE id IN (
    SELECT id FROM elitea_storage.transfer_grants
    WHERE consumed_at IS NULL AND expires_at < $1::timestamptz
    ORDER BY expires_at
    LIMIT $2::int
    FOR UPDATE SKIP LOCKED
)
RETURNING id::text AS id, project_id, bucket_id, key, method, upload_id, expires_at
`

type ClaimExpiredArtifactTransferGrantsParams struct {
	OlderThan pgtype.Timestamptz `db:"older_than" json:"older_than"`
	RowLimit  int32              `db:"row_limit" json:"row_limit"`
}

type ClaimExpiredArtifactTransferGrantsRow struct {
	ID        string             `db:"id" json:"id"`
	ProjectID int64              `db:"project_id" json:"project_id"`
	BucketID  int64              `db:"bucket_id" json:"bucket_id"`
	Key       string             `db:"key" json:"key"`
	Method    string             `db:"method" json:"method"`
	UploadID  *string            `db:"upload_id" json:"upload_id"`
	ExpiresAt pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
}

// Claims a bounded batch of expired, unconsumed grants for the retention
// sweeper, and returns what it needs to reclaim the bytes.
//
// WHY THIS EXISTS. CreateArtifactTransferGrant hands out a presigned PUT and
// writes only this row. The elitea_storage.objects row appears at commit and
// nowhere else. A caller who uploads to the signed URL and never commits
// therefore leaves bytes with no metadata row: SumArtifactProjectBytes cannot
// count them against max_total_bytes, and ListExpiredArtifactObjects cannot
// see them, because both read only the objects table. Nothing time-driven
// reclaimed them.
//
// WHY IT CLAIMS INSTEAD OF SELECTING. Setting consumed_at in the same
// statement that selects the row is what makes the sweep safe against a
// commit in flight. MarkArtifactTransferGrantConsumed already carries
// `AND consumed_at IS NULL`, so a commit that races a claimed grant loses the
// mark and answers 409. A plain SELECT followed by a delete has the opposite
// outcome. The commit writes a metadata row. The sweeper then deletes the
// bytes underneath it. The project is charged for an object that no longer
// exists, and no later sweep can heal that.
//
// FOR UPDATE SKIP LOCKED lets two replicas sweep at the same time without
// either waiting on the other. The row itself is kept, not deleted, so a late
// commit still sees the 409 rather than a 404.
func (q *Queries) ClaimExpiredArtifactTransferGrants(ctx context.Context, arg ClaimExpiredArtifactTransferGrantsParams) ([]ClaimExpiredArtifactTransferGrantsRow, error) {
	rows, err := q.db.Query(ctx, claimExpiredArtifactTransferGrants, arg.OlderThan, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClaimExpiredArtifactTransferGrantsRow{}
	for rows.Next() {
		var i ClaimExpiredArtifactTransferGrantsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.BucketID,
			&i.Key,
			&i.Method,
			&i.UploadID,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createArtifactTransferGrant = `-- name: CreateArtifactTransferGrant :one
INSERT INTO elitea_storage.transfer_grants (
    id, project_id, bucket_id, key, method, content_type, max_bytes,
    digest_alg, digest, upload_id, expires_at
) VALUES (
    $1::text::uuid, $2::bigint, $3::bigint,
    $4::text, $5::text, $6::text,
    $7::bigint, $8::text, $9::bytea,
    $10::text, $11::timestamptz
)
RETURNING id::text AS id, project_id, bucket_id, key, method, content_type, max_bytes,
    digest_alg, digest, upload_id, expires_at, consumed_at, created_at
`

type CreateArtifactTransferGrantParams struct {
	ID          string             `db:"id" json:"id"`
	ProjectID   int64              `db:"project_id" json:"project_id"`
	BucketID    int64              `db:"bucket_id" json:"bucket_id"`
	Key         string             `db:"key" json:"key"`
	Method      string             `db:"method" json:"method"`
	ContentType string             `db:"content_type" json:"content_type"`
	MaxBytes    int64              `db:"max_bytes" json:"max_bytes"`
	DigestAlg   *string            `db:"digest_alg" json:"digest_alg"`
	Digest      []byte             `db:"digest" json:"digest"`
	UploadID    *string            `db:"upload_id" json:"upload_id"`
	ExpiresAt   pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
}

type CreateArtifactTransferGrantRow struct {
	ID          string             `db:"id" json:"id"`
	ProjectID   int64              `db:"project_id" json:"project_id"`
	BucketID    int64              `db:"bucket_id" json:"bucket_id"`
	Key         string             `db:"key" json:"key"`
	Method      string             `db:"method" json:"method"`
	ContentType string             `db:"content_type" json:"content_type"`
	MaxBytes    int64              `db:"max_bytes" json:"max_bytes"`
	DigestAlg   *string            `db:"digest_alg" json:"digest_alg"`
	Digest      []byte             `db:"digest" json:"digest"`
	UploadID    *string            `db:"upload_id" json:"upload_id"`
	ExpiresAt   pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	ConsumedAt  pgtype.Timestamptz `db:"consumed_at" json:"consumed_at"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

// id::text/RETURNING id::text: transfer_grants.id is a native uuid column;
// casting to text on both sides keeps the Go-side type a plain string,
// matching this codebase's established convention (e.g.
// InsertArtifactBucketExpiryNotification, S14) rather than pgtype.UUID.
// upload_id (S16) is set only when CreateTransferGrant started a native
// multipart upload; a normal single-shot grant passes it as NULL.
func (q *Queries) CreateArtifactTransferGrant(ctx context.Context, arg CreateArtifactTransferGrantParams) (CreateArtifactTransferGrantRow, error) {
	row := q.db.QueryRow(ctx, createArtifactTransferGrant,
		arg.ID,
		arg.ProjectID,
		arg.BucketID,
		arg.Key,
		arg.Method,
		arg.ContentType,
		arg.MaxBytes,
		arg.DigestAlg,
		arg.Digest,
		arg.UploadID,
		arg.ExpiresAt,
	)
	var i CreateArtifactTransferGrantRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.BucketID,
		&i.Key,
		&i.Method,
		&i.ContentType,
		&i.MaxBytes,
		&i.DigestAlg,
		&i.Digest,
		&i.UploadID,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getArtifactTransferGrant = `-- name: GetArtifactTransferGrant :one
SELECT id::text AS id, project_id, bucket_id, key, method, content_type, max_bytes,
    digest_alg, digest, upload_id, expires_at, consumed_at, created_at
FROM elitea_storage.transfer_grants
WHERE id = $1::text::uuid AND project_id = $2::bigint
`

type GetArtifactTransferGrantParams struct {
	ID        string `db:"id" json:"id"`
	ProjectID int64  `db:"project_id" json:"project_id"`
}

type GetArtifactTransferGrantRow struct {
	ID          string             `db:"id" json:"id"`
	ProjectID   int64              `db:"project_id" json:"project_id"`
	BucketID    int64              `db:"bucket_id" json:"bucket_id"`
	Key         string             `db:"key" json:"key"`
	Method      string             `db:"method" json:"method"`
	ContentType string             `db:"content_type" json:"content_type"`
	MaxBytes    int64              `db:"max_bytes" json:"max_bytes"`
	DigestAlg   *string            `db:"digest_alg" json:"digest_alg"`
	Digest      []byte             `db:"digest" json:"digest"`
	UploadID    *string            `db:"upload_id" json:"upload_id"`
	ExpiresAt   pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	ConsumedAt  pgtype.Timestamptz `db:"consumed_at" json:"consumed_at"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

// Scoped by project_id, not just id: grant IDs are unguessable UUIDs, but
// every other artifact route requires a matching {projectID}, and this one
// should not be the exception that lets a caller commit a grant belonging
// to a project they only guessed the ID for.
func (q *Queries) GetArtifactTransferGrant(ctx context.Context, arg GetArtifactTransferGrantParams) (GetArtifactTransferGrantRow, error) {
	row := q.db.QueryRow(ctx, getArtifactTransferGrant, arg.ID, arg.ProjectID)
	var i GetArtifactTransferGrantRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.BucketID,
		&i.Key,
		&i.Method,
		&i.ContentType,
		&i.MaxBytes,
		&i.DigestAlg,
		&i.Digest,
		&i.UploadID,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getArtifactTransferGrantByID = `-- name: GetArtifactTransferGrantByID :one
SELECT id::text AS id, project_id, bucket_id, key, method, content_type, max_bytes,
    digest_alg, digest, upload_id, expires_at, consumed_at, created_at
FROM elitea_storage.transfer_grants
WHERE id = $1::text::uuid
`

type GetArtifactTransferGrantByIDRow struct {
	ID          string             `db:"id" json:"id"`
	ProjectID   int64              `db:"project_id" json:"project_id"`
	BucketID    int64              `db:"bucket_id" json:"bucket_id"`
	Key         string             `db:"key" json:"key"`
	Method      string             `db:"method" json:"method"`
	ContentType string             `db:"content_type" json:"content_type"`
	MaxBytes    int64              `db:"max_bytes" json:"max_bytes"`
	DigestAlg   *string            `db:"digest_alg" json:"digest_alg"`
	Digest      []byte             `db:"digest" json:"digest"`
	UploadID    *string            `db:"upload_id" json:"upload_id"`
	ExpiresAt   pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	ConsumedAt  pgtype.Timestamptz `db:"consumed_at" json:"consumed_at"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

// Unscoped by project_id, unlike GetArtifactTransferGrant above — used only
// by S16's multipart continuation endpoints (part presign, complete,
// abort), which must distinguish "grant does not exist" (404) from "grant
// exists but belongs to a different project" (403 AccessDenied): the
// plan's own S16 acceptance criterion ("a part call with another project's
// grant returns 403") requires exactly that distinction, which a
// project-scoped WHERE clause can't make — a wrong project and a
// nonexistent id both return zero rows. See handler.go's
// requireOwnedMultipartGrant for where the 403 decision actually happens.
func (q *Queries) GetArtifactTransferGrantByID(ctx context.Context, id string) (GetArtifactTransferGrantByIDRow, error) {
	row := q.db.QueryRow(ctx, getArtifactTransferGrantByID, id)
	var i GetArtifactTransferGrantByIDRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.BucketID,
		&i.Key,
		&i.Method,
		&i.ContentType,
		&i.MaxBytes,
		&i.DigestAlg,
		&i.Digest,
		&i.UploadID,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const markArtifactTransferGrantConsumed = `-- name: MarkArtifactTransferGrantConsumed :execrows
UPDATE elitea_storage.transfer_grants
SET consumed_at = now()
WHERE id = $1::text::uuid AND consumed_at IS NULL
`

// consumed_at IS NULL in the WHERE clause, not just the SET, is the actual
// single-use enforcement: 0 rows affected means either the grant does not
// exist or was already consumed. The caller (commitTransferGrant) has
// already fetched the row by this point, so 0 rows here unambiguously means
// "already consumed" — see repository.go's MarkTransferGrantConsumed.
// S16 also uses this to mark an aborted multipart grant terminal — see
// AbortMultipartUpload.
func (q *Queries) MarkArtifactTransferGrantConsumed(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, markArtifactTransferGrantConsumed, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
