// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: attachment_chunks.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAttachmentChunks = `-- name: CountAttachmentChunks :one
SELECT COUNT(*)::bigint
FROM elitea_storage.attachment_chunks
WHERE project_id = $1 AND conversation_id = $2 AND file_id = $3
`

type CountAttachmentChunksParams struct {
	ProjectID      int64  `db:"project_id" json:"project_id"`
	ConversationID string `db:"conversation_id" json:"conversation_id"`
	FileID         string `db:"file_id" json:"file_id"`
}

func (q *Queries) CountAttachmentChunks(ctx context.Context, arg CountAttachmentChunksParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAttachmentChunks, arg.ProjectID, arg.ConversationID, arg.FileID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const deleteAttachmentChunks = `-- name: DeleteAttachmentChunks :execrows
DELETE FROM elitea_storage.attachment_chunks
WHERE project_id = $1 AND conversation_id = $2 AND file_id = $3
`

type DeleteAttachmentChunksParams struct {
	ProjectID      int64  `db:"project_id" json:"project_id"`
	ConversationID string `db:"conversation_id" json:"conversation_id"`
	FileID         string `db:"file_id" json:"file_id"`
}

func (q *Queries) DeleteAttachmentChunks(ctx context.Context, arg DeleteAttachmentChunksParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAttachmentChunks, arg.ProjectID, arg.ConversationID, arg.FileID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteStaleAttachmentChunks = `-- name: DeleteStaleAttachmentChunks :execrows
DELETE FROM elitea_storage.attachment_chunks
WHERE received_at < $1
`

// Reclaims chunk rows for a chunked upload that was abandoned before its
// final chunk arrived (browser tab closed, connection lost) — the only
// other path that deletes these rows is the completed-merge path
// (DeleteAttachmentChunks above), which an abandoned upload never reaches.
// Legacy's equivalent is utils/file_utils.py's cleanup_stale_chunks, a
// 12-hour local-disk TTL swept by the elitea_core_cleanup_stale_chunks RPC.
func (q *Queries) DeleteStaleAttachmentChunks(ctx context.Context, receivedAt pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, deleteStaleAttachmentChunks, receivedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listAttachmentChunksOrdered = `-- name: ListAttachmentChunksOrdered :many
SELECT chunk_index, bytes
FROM elitea_storage.attachment_chunks
WHERE project_id = $1 AND conversation_id = $2 AND file_id = $3
ORDER BY chunk_index
`

type ListAttachmentChunksOrderedParams struct {
	ProjectID      int64  `db:"project_id" json:"project_id"`
	ConversationID string `db:"conversation_id" json:"conversation_id"`
	FileID         string `db:"file_id" json:"file_id"`
}

type ListAttachmentChunksOrderedRow struct {
	ChunkIndex int32  `db:"chunk_index" json:"chunk_index"`
	Bytes      []byte `db:"bytes" json:"bytes"`
}

// Read by the merge step once CountAttachmentChunks reaches total_chunks —
// ORDER BY chunk_index reconstructs the original byte stream regardless of
// arrival order, matching legacy's merge_chunks reading 0..total_chunks-1.
func (q *Queries) ListAttachmentChunksOrdered(ctx context.Context, arg ListAttachmentChunksOrderedParams) ([]ListAttachmentChunksOrderedRow, error) {
	rows, err := q.db.Query(ctx, listAttachmentChunksOrdered, arg.ProjectID, arg.ConversationID, arg.FileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAttachmentChunksOrderedRow{}
	for rows.Next() {
		var i ListAttachmentChunksOrderedRow
		if err := rows.Scan(&i.ChunkIndex, &i.Bytes); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAttachmentChunk = `-- name: UpsertAttachmentChunk :exec
INSERT INTO elitea_storage.attachment_chunks (
    project_id, conversation_id, file_id, chunk_index, total_chunks,
    file_name, content_type, bytes
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
ON CONFLICT (project_id, conversation_id, file_id, chunk_index) DO UPDATE SET
    bytes = EXCLUDED.bytes,
    content_type = EXCLUDED.content_type,
    received_at = now()
`

type UpsertAttachmentChunkParams struct {
	ProjectID      int64  `db:"project_id" json:"project_id"`
	ConversationID string `db:"conversation_id" json:"conversation_id"`
	FileID         string `db:"file_id" json:"file_id"`
	ChunkIndex     int32  `db:"chunk_index" json:"chunk_index"`
	TotalChunks    int32  `db:"total_chunks" json:"total_chunks"`
	FileName       string `db:"file_name" json:"file_name"`
	ContentType    string `db:"content_type" json:"content_type"`
	Bytes          []byte `db:"bytes" json:"bytes"`
}

// ON CONFLICT DO UPDATE, not DO NOTHING: a retried chunk_index (client
// timeout, network retry) must overwrite the previous bytes for that index,
// matching legacy's own local-disk behavior (writing to the same filename
// twice replaces it) — never double-counted, since the primary key already
// de-duplicates by chunk_index.
func (q *Queries) UpsertAttachmentChunk(ctx context.Context, arg UpsertAttachmentChunkParams) error {
	_, err := q.db.Exec(ctx, upsertAttachmentChunk,
		arg.ProjectID,
		arg.ConversationID,
		arg.FileID,
		arg.ChunkIndex,
		arg.TotalChunks,
		arg.FileName,
		arg.ContentType,
		arg.Bytes,
	)
	return err
}
