// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth_pat.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPATForActiveUser = `-- name: CreatePATForActiveUser :one
INSERT INTO public.auth_core__token (uuid, expires, user_id, name)
SELECT
    $1::varchar(36),
    $2::timestamp without time zone,
    owner.id,
    $3::text
FROM public.auth_core__user AS owner
WHERE owner.id = $4::integer
  AND owner.suspended = false
RETURNING
    id,
    uuid,
    expires,
    COALESCE(user_id, 0)::integer AS user_id,
    name
`

type CreatePATForActiveUserParams struct {
	Uuid    string           `db:"uuid" json:"uuid"`
	Expires pgtype.Timestamp `db:"expires" json:"expires"`
	Name    *string          `db:"name" json:"name"`
	UserID  int32            `db:"user_id" json:"user_id"`
}

type CreatePATForActiveUserRow struct {
	ID      int32            `db:"id" json:"id"`
	Uuid    *string          `db:"uuid" json:"uuid"`
	Expires pgtype.Timestamp `db:"expires" json:"expires"`
	UserID  int32            `db:"user_id" json:"user_id"`
	Name    *string          `db:"name" json:"name"`
}

func (q *Queries) CreatePATForActiveUser(ctx context.Context, arg CreatePATForActiveUserParams) (CreatePATForActiveUserRow, error) {
	row := q.db.QueryRow(ctx, createPATForActiveUser,
		arg.Uuid,
		arg.Expires,
		arg.Name,
		arg.UserID,
	)
	var i CreatePATForActiveUserRow
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Expires,
		&i.UserID,
		&i.Name,
	)
	return i, err
}

const deletePATByID = `-- name: DeletePATByID :execrows
DELETE FROM public.auth_core__token
WHERE id = $1::integer
`

func (q *Queries) DeletePATByID(ctx context.Context, id int32) (int64, error) {
	result, err := q.db.Exec(ctx, deletePATByID, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getActivePATPrincipalByUUID = `-- name: GetActivePATPrincipalByUUID :one
SELECT
    token.id AS token_id,
    owner.id AS user_id,
    COALESCE(owner.email, '')::text AS email
FROM public.auth_core__token AS token
JOIN public.auth_core__user AS owner ON owner.id = token.user_id
WHERE token.uuid = $1::text
  AND owner.suspended = false
  AND (token.expires IS NULL OR token.expires > (clock_timestamp() AT TIME ZONE 'UTC'))
`

type GetActivePATPrincipalByUUIDRow struct {
	TokenID int32  `db:"token_id" json:"token_id"`
	UserID  int32  `db:"user_id" json:"user_id"`
	Email   string `db:"email" json:"email"`
}

func (q *Queries) GetActivePATPrincipalByUUID(ctx context.Context, uuid string) (GetActivePATPrincipalByUUIDRow, error) {
	row := q.db.QueryRow(ctx, getActivePATPrincipalByUUID, uuid)
	var i GetActivePATPrincipalByUUIDRow
	err := row.Scan(&i.TokenID, &i.UserID, &i.Email)
	return i, err
}

const getOwnedPAT = `-- name: GetOwnedPAT :one
SELECT
    token.id,
    token.uuid,
    token.expires,
    COALESCE(token.user_id, 0)::integer AS user_id,
    token.name
FROM public.auth_core__token AS token
WHERE token.uuid = $1::text
  AND token.user_id = $2::integer
`

type GetOwnedPATParams struct {
	Uuid   string `db:"uuid" json:"uuid"`
	UserID int32  `db:"user_id" json:"user_id"`
}

type GetOwnedPATRow struct {
	ID      int32            `db:"id" json:"id"`
	Uuid    *string          `db:"uuid" json:"uuid"`
	Expires pgtype.Timestamp `db:"expires" json:"expires"`
	UserID  int32            `db:"user_id" json:"user_id"`
	Name    *string          `db:"name" json:"name"`
}

func (q *Queries) GetOwnedPAT(ctx context.Context, arg GetOwnedPATParams) (GetOwnedPATRow, error) {
	row := q.db.QueryRow(ctx, getOwnedPAT, arg.Uuid, arg.UserID)
	var i GetOwnedPATRow
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Expires,
		&i.UserID,
		&i.Name,
	)
	return i, err
}

const listOwnedPATs = `-- name: ListOwnedPATs :many
SELECT
    token.id,
    token.uuid,
    token.expires,
    COALESCE(token.user_id, 0)::integer AS user_id,
    token.name
FROM public.auth_core__token AS token
WHERE token.user_id = $1::integer
ORDER BY token.id
`

type ListOwnedPATsRow struct {
	ID      int32            `db:"id" json:"id"`
	Uuid    *string          `db:"uuid" json:"uuid"`
	Expires pgtype.Timestamp `db:"expires" json:"expires"`
	UserID  int32            `db:"user_id" json:"user_id"`
	Name    *string          `db:"name" json:"name"`
}

func (q *Queries) ListOwnedPATs(ctx context.Context, userID int32) ([]ListOwnedPATsRow, error) {
	rows, err := q.db.Query(ctx, listOwnedPATs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOwnedPATsRow{}
	for rows.Next() {
		var i ListOwnedPATsRow
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.Expires,
			&i.UserID,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockPATByUUID = `-- name: LockPATByUUID :one
SELECT
    token.id,
    COALESCE(token.user_id, 0)::integer AS user_id
FROM public.auth_core__token AS token
WHERE token.uuid = $1::text
FOR UPDATE
`

type LockPATByUUIDRow struct {
	ID     int32 `db:"id" json:"id"`
	UserID int32 `db:"user_id" json:"user_id"`
}

func (q *Queries) LockPATByUUID(ctx context.Context, uuid string) (LockPATByUUIDRow, error) {
	row := q.db.QueryRow(ctx, lockPATByUUID, uuid)
	var i LockPATByUUIDRow
	err := row.Scan(&i.ID, &i.UserID)
	return i, err
}
