// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth_current_user.sql

package sqlcgen

import (
	"context"
)

const getCurrentActiveAuthUser = `-- name: GetCurrentActiveAuthUser :one
SELECT id, email, name, last_login, suspended
FROM public.auth_core__user
WHERE id = $1::integer
  AND suspended = false
`

func (q *Queries) GetCurrentActiveAuthUser(ctx context.Context, userID int32) (AuthCoreUser, error) {
	row := q.db.QueryRow(ctx, getCurrentActiveAuthUser, userID)
	var i AuthCoreUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.LastLogin,
		&i.Suspended,
	)
	return i, err
}
