// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth_projects.sql

package sqlcgen

import (
	"context"
)

const listCurrentUserProjects = `-- name: ListCurrentUserProjects :many
WITH candidate_projects AS MATERIALIZED (
    SELECT
        project.id,
        project.name,
        project.owner_id,
        project.plugins,
        project.keycloak_groups,
        project.create_success,
        project.suspended
    FROM centry.project AS project
    WHERE (
        $4::text IS NULL
        OR project.name ILIKE ('%' || $4::text || '%')
    )
    ORDER BY project.id
    LIMIT $6::integer
    OFFSET $5::integer
), member_projects AS MATERIALIZED (
    SELECT DISTINCT assignment.project_id
    FROM public.auth_core__project_user_role AS assignment
    WHERE assignment.user_id = $3::integer
)
SELECT
    project.id,
    project.name,
    project.owner_id,
    project.plugins,
    project.keycloak_groups,
    project.create_success,
    project.suspended,
    project_group.id AS group_id,
    project_group.name AS group_name
FROM candidate_projects AS project
JOIN member_projects AS membership ON membership.project_id = project.id
LEFT JOIN centry.project_group_association AS association
    ON association.project_id = project.id
LEFT JOIN centry.project_group AS project_group
    ON project_group.id = association.group_id
WHERE (
    NOT $1::boolean
    OR project.id <> $2::integer
    OR EXISTS (
        SELECT 1
        FROM public.auth_core__project_user_role AS assignment
        JOIN public.auth_core__project_role AS project_role
            ON project_role.id = assignment.role_id
            AND project_role.project_id = assignment.project_id
        WHERE assignment.project_id = project.id
          AND assignment.user_id = $3::integer
          AND project_role.name = 'admin'
    )
)
ORDER BY project.id, project_group.id
`

type ListCurrentUserProjectsParams struct {
	CheckPublicRole bool    `db:"check_public_role" json:"check_public_role"`
	PublicProjectID int32   `db:"public_project_id" json:"public_project_id"`
	UserID          int32   `db:"user_id" json:"user_id"`
	Search          *string `db:"search" json:"search"`
	Offset          *int32  `db:"offset" json:"offset"`
	Limit           *int32  `db:"limit" json:"limit"`
}

type ListCurrentUserProjectsRow struct {
	ID             int32    `db:"id" json:"id"`
	Name           string   `db:"name" json:"name"`
	OwnerID        int32    `db:"owner_id" json:"owner_id"`
	Plugins        []string `db:"plugins" json:"plugins"`
	KeycloakGroups []byte   `db:"keycloak_groups" json:"keycloak_groups"`
	CreateSuccess  bool     `db:"create_success" json:"create_success"`
	Suspended      bool     `db:"suspended" json:"suspended"`
	GroupID        *int32   `db:"group_id" json:"group_id"`
	GroupName      *string  `db:"group_name" json:"group_name"`
}

func (q *Queries) ListCurrentUserProjects(ctx context.Context, arg ListCurrentUserProjectsParams) ([]ListCurrentUserProjectsRow, error) {
	rows, err := q.db.Query(ctx, listCurrentUserProjects,
		arg.CheckPublicRole,
		arg.PublicProjectID,
		arg.UserID,
		arg.Search,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCurrentUserProjectsRow{}
	for rows.Next() {
		var i ListCurrentUserProjectsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.OwnerID,
			&i.Plugins,
			&i.KeycloakGroups,
			&i.CreateSuccess,
			&i.Suspended,
			&i.GroupID,
			&i.GroupName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
