// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: configuration_lifecycle_effects.sql

package sqlcgen

import (
	"context"
)

const compareAndSwapCurrentConfigurationRenameToolkit = `-- name: CompareAndSwapCurrentConfigurationRenameToolkit :execrows
UPDATE elitea_tools
SET settings = $1::jsonb
WHERE id = $2::integer
  AND md5(settings::text) = $3::text
`

type CompareAndSwapCurrentConfigurationRenameToolkitParams struct {
	Settings        []byte `db:"settings" json:"settings"`
	ToolkitID       int32  `db:"toolkit_id" json:"toolkit_id"`
	ExpectedVersion string `db:"expected_version" json:"expected_version"`
}

func (q *Queries) CompareAndSwapCurrentConfigurationRenameToolkit(ctx context.Context, arg CompareAndSwapCurrentConfigurationRenameToolkitParams) (int64, error) {
	result, err := q.db.Exec(ctx, compareAndSwapCurrentConfigurationRenameToolkit, arg.Settings, arg.ToolkitID, arg.ExpectedVersion)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCurrentConfigurationRenameToolkit = `-- name: GetCurrentConfigurationRenameToolkit :one
WITH candidate AS MATERIALIZED (
    SELECT id,
           md5(settings::text) AS settings_version,
           octet_length(settings::text)::bigint AS settings_bytes,
           settings
    FROM elitea_tools
    WHERE id = $2::integer
    LIMIT 1
)
SELECT id,
       settings_version,
       CASE
           WHEN settings_bytes <= $1::bigint
           THEN settings
           ELSE NULL::jsonb
       END AS settings,
       settings_bytes
FROM candidate
`

type GetCurrentConfigurationRenameToolkitParams struct {
	MaxSettingsBytes int64 `db:"max_settings_bytes" json:"max_settings_bytes"`
	ToolkitID        int32 `db:"toolkit_id" json:"toolkit_id"`
}

type GetCurrentConfigurationRenameToolkitRow struct {
	ID              int32  `db:"id" json:"id"`
	SettingsVersion string `db:"settings_version" json:"settings_version"`
	Settings        []byte `db:"settings" json:"settings"`
	SettingsBytes   int64  `db:"settings_bytes" json:"settings_bytes"`
}

func (q *Queries) GetCurrentConfigurationRenameToolkit(ctx context.Context, arg GetCurrentConfigurationRenameToolkitParams) (GetCurrentConfigurationRenameToolkitRow, error) {
	row := q.db.QueryRow(ctx, getCurrentConfigurationRenameToolkit, arg.MaxSettingsBytes, arg.ToolkitID)
	var i GetCurrentConfigurationRenameToolkitRow
	err := row.Scan(
		&i.ID,
		&i.SettingsVersion,
		&i.Settings,
		&i.SettingsBytes,
	)
	return i, err
}

const listActiveCurrentProjectIDs = `-- name: ListActiveCurrentProjectIDs :many
SELECT id
FROM centry.project AS project
WHERE project.create_success IS TRUE
  AND project.suspended IS FALSE
ORDER BY id
LIMIT $1::integer
`

func (q *Queries) ListActiveCurrentProjectIDs(ctx context.Context, limitRows int32) ([]int32, error) {
	rows, err := q.db.Query(ctx, listActiveCurrentProjectIDs, limitRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int32{}
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCurrentConfigurationRenameToolkits = `-- name: ListCurrentConfigurationRenameToolkits :many
WITH candidate AS MATERIALIZED (
    SELECT id,
           octet_length(settings::text)::bigint AS settings_bytes
    FROM elitea_tools
    ORDER BY id
    LIMIT $3::integer
), bounded AS (
    SELECT id,
           settings_bytes,
           sum(settings_bytes) OVER (
               ORDER BY id
               ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
           )::bigint AS total_bytes
    FROM candidate
)
SELECT toolkit.id,
       md5(toolkit.settings::text) AS settings_version,
       CASE
           WHEN bounded.settings_bytes <= $1::bigint
            AND bounded.total_bytes <= $2::bigint
           THEN toolkit.settings
           ELSE NULL::jsonb
       END AS settings,
       bounded.settings_bytes,
       bounded.total_bytes
FROM bounded
JOIN elitea_tools AS toolkit ON toolkit.id = bounded.id
ORDER BY toolkit.id
`

type ListCurrentConfigurationRenameToolkitsParams struct {
	MaxSettingsBytes int64 `db:"max_settings_bytes" json:"max_settings_bytes"`
	MaxTotalBytes    int64 `db:"max_total_bytes" json:"max_total_bytes"`
	LimitRows        int32 `db:"limit_rows" json:"limit_rows"`
}

type ListCurrentConfigurationRenameToolkitsRow struct {
	ID              int32  `db:"id" json:"id"`
	SettingsVersion string `db:"settings_version" json:"settings_version"`
	Settings        []byte `db:"settings" json:"settings"`
	SettingsBytes   int64  `db:"settings_bytes" json:"settings_bytes"`
	TotalBytes      int64  `db:"total_bytes" json:"total_bytes"`
}

func (q *Queries) ListCurrentConfigurationRenameToolkits(ctx context.Context, arg ListCurrentConfigurationRenameToolkitsParams) ([]ListCurrentConfigurationRenameToolkitsRow, error) {
	rows, err := q.db.Query(ctx, listCurrentConfigurationRenameToolkits, arg.MaxSettingsBytes, arg.MaxTotalBytes, arg.LimitRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCurrentConfigurationRenameToolkitsRow{}
	for rows.Next() {
		var i ListCurrentConfigurationRenameToolkitsRow
		if err := rows.Scan(
			&i.ID,
			&i.SettingsVersion,
			&i.Settings,
			&i.SettingsBytes,
			&i.TotalBytes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const replaceCurrentDeletedLLMApplicationReferences = `-- name: ReplaceCurrentDeletedLLMApplicationReferences :one
WITH matched AS MATERIALIZED (
    SELECT id
    FROM application_versions
    WHERE llm_settings ->> 'model_name' = $1::text
    ORDER BY id
    LIMIT $2::integer
    FOR UPDATE
), within_limit AS MATERIALIZED (
    SELECT id
    FROM matched
    WHERE (SELECT count(*) FROM matched) <= $3::integer
), updated AS (
    UPDATE application_versions AS version
    SET llm_settings = (
        version.llm_settings::jsonb || jsonb_build_object(
            'model_name', $4::text,
            'model_project_id', $5::integer
        )
    )::json
    FROM within_limit
    WHERE version.id = within_limit.id
    RETURNING version.id
)
SELECT (SELECT count(*) FROM matched)::bigint AS matched_count,
       (SELECT count(*) FROM updated)::bigint AS updated_count
`

type ReplaceCurrentDeletedLLMApplicationReferencesParams struct {
	DeletedModelName      string `db:"deleted_model_name" json:"deleted_model_name"`
	ScanLimit             int32  `db:"scan_limit" json:"scan_limit"`
	MaxRows               int32  `db:"max_rows" json:"max_rows"`
	DefaultModelName      string `db:"default_model_name" json:"default_model_name"`
	DefaultModelProjectID int32  `db:"default_model_project_id" json:"default_model_project_id"`
}

type ReplaceCurrentDeletedLLMApplicationReferencesRow struct {
	MatchedCount int64 `db:"matched_count" json:"matched_count"`
	UpdatedCount int64 `db:"updated_count" json:"updated_count"`
}

func (q *Queries) ReplaceCurrentDeletedLLMApplicationReferences(ctx context.Context, arg ReplaceCurrentDeletedLLMApplicationReferencesParams) (ReplaceCurrentDeletedLLMApplicationReferencesRow, error) {
	row := q.db.QueryRow(ctx, replaceCurrentDeletedLLMApplicationReferences,
		arg.DeletedModelName,
		arg.ScanLimit,
		arg.MaxRows,
		arg.DefaultModelName,
		arg.DefaultModelProjectID,
	)
	var i ReplaceCurrentDeletedLLMApplicationReferencesRow
	err := row.Scan(&i.MatchedCount, &i.UpdatedCount)
	return i, err
}

const setCurrentConfigurationLifecycleStatus = `-- name: SetCurrentConfigurationLifecycleStatus :execrows

UPDATE configuration
SET status_ok = $1::boolean
WHERE project_id = $2::integer
  AND id = $3::integer
  AND uuid = $4::text::uuid
`

type SetCurrentConfigurationLifecycleStatusParams struct {
	StatusOk          bool   `db:"status_ok" json:"status_ok"`
	ProjectID         int32  `db:"project_id" json:"project_id"`
	ConfigurationID   int32  `db:"configuration_id" json:"configuration_id"`
	ConfigurationUuid string `db:"configuration_uuid" json:"configuration_uuid"`
}

// Configuration lifecycle internal effects. Unqualified tenant tables are
// intentional: every such statement runs inside an authorized project
// transaction whose local search_path is p_<project_id>.
func (q *Queries) SetCurrentConfigurationLifecycleStatus(ctx context.Context, arg SetCurrentConfigurationLifecycleStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, setCurrentConfigurationLifecycleStatus,
		arg.StatusOk,
		arg.ProjectID,
		arg.ConfigurationID,
		arg.ConfigurationUuid,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
