// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: current_tenant_context.sql

package sqlcgen

import (
	"context"
)

const getCurrentTenantSchema = `-- name: GetCurrentTenantSchema :one
SELECT current_schema()::text
`

func (q *Queries) GetCurrentTenantSchema(ctx context.Context) (string, error) {
	row := q.db.QueryRow(ctx, getCurrentTenantSchema)
	var column_1 string
	err := row.Scan(&column_1)
	return column_1, err
}

const installCurrentTenantSearchPath = `-- name: InstallCurrentTenantSearchPath :one
SELECT set_config('search_path', $1::text, TRUE)
`

func (q *Queries) InstallCurrentTenantSearchPath(ctx context.Context, searchPath string) (string, error) {
	row := q.db.QueryRow(ctx, installCurrentTenantSearchPath, searchPath)
	var set_config string
	err := row.Scan(&set_config)
	return set_config, err
}

const resolveCurrentTenantContext = `-- name: ResolveCurrentTenantContext :one
SELECT EXISTS (
           SELECT 1
           FROM centry.project
           WHERE id = $1::bigint
       ) AS project_exists,
       EXISTS (
           SELECT 1
           FROM pg_catalog.pg_namespace
           WHERE nspname = $2::text
       ) AS schema_exists
`

type ResolveCurrentTenantContextParams struct {
	ProjectID  int64  `db:"project_id" json:"project_id"`
	SchemaName string `db:"schema_name" json:"schema_name"`
}

type ResolveCurrentTenantContextRow struct {
	ProjectExists bool `db:"project_exists" json:"project_exists"`
	SchemaExists  bool `db:"schema_exists" json:"schema_exists"`
}

func (q *Queries) ResolveCurrentTenantContext(ctx context.Context, arg ResolveCurrentTenantContextParams) (ResolveCurrentTenantContextRow, error) {
	row := q.db.QueryRow(ctx, resolveCurrentTenantContext, arg.ProjectID, arg.SchemaName)
	var i ResolveCurrentTenantContextRow
	err := row.Scan(&i.ProjectExists, &i.SchemaExists)
	return i, err
}
