// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: current_configurations.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countCurrentConfigurations = `-- name: CountCurrentConfigurations :one
SELECT count(*)
FROM configuration
WHERE project_id = $1::integer
  AND (COALESCE(cardinality($2::text[]), 0) = 0 OR type = ANY($2::text[]))
  AND (COALESCE(cardinality($3::text[]), 0) = 0 OR section = ANY($3::text[]))
  AND ($4::text = '' OR label ILIKE ('%' || $4::text || '%'))
`

type CountCurrentConfigurationsParams struct {
	ProjectID  int32    `db:"project_id" json:"project_id"`
	Types      []string `db:"types" json:"types"`
	Sections   []string `db:"sections" json:"sections"`
	LabelQuery string   `db:"label_query" json:"label_query"`
}

func (q *Queries) CountCurrentConfigurations(ctx context.Context, arg CountCurrentConfigurationsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCurrentConfigurations,
		arg.ProjectID,
		arg.Types,
		arg.Sections,
		arg.LabelQuery,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countCurrentSharedConfigurations = `-- name: CountCurrentSharedConfigurations :one
SELECT count(*)
FROM configuration
WHERE project_id = $1::integer
  AND shared = true
  AND (COALESCE(cardinality($2::text[]), 0) = 0 OR type = ANY($2::text[]))
  AND (COALESCE(cardinality($3::text[]), 0) = 0 OR section = ANY($3::text[]))
`

type CountCurrentSharedConfigurationsParams struct {
	ProjectID int32    `db:"project_id" json:"project_id"`
	Types     []string `db:"types" json:"types"`
	Sections  []string `db:"sections" json:"sections"`
}

func (q *Queries) CountCurrentSharedConfigurations(ctx context.Context, arg CountCurrentSharedConfigurationsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCurrentSharedConfigurations, arg.ProjectID, arg.Types, arg.Sections)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteCurrentConfiguration = `-- name: DeleteCurrentConfiguration :one
DELETE FROM configuration
WHERE id = $1::integer
  AND project_id = $2::integer
RETURNING id
`

type DeleteCurrentConfigurationParams struct {
	ConfigurationID int32 `db:"configuration_id" json:"configuration_id"`
	ProjectID       int32 `db:"project_id" json:"project_id"`
}

func (q *Queries) DeleteCurrentConfiguration(ctx context.Context, arg DeleteCurrentConfigurationParams) (int32, error) {
	row := q.db.QueryRow(ctx, deleteCurrentConfiguration, arg.ConfigurationID, arg.ProjectID)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const getCurrentConfiguration = `-- name: GetCurrentConfiguration :one

SELECT id,
       uuid::text AS configuration_uuid,
       project_id,
       label,
       elitea_title,
       type,
       section,
       data,
       meta,
       shared,
       status_ok,
       status_logs,
       source,
       author_id,
       created_at,
       updated_at
FROM configuration
WHERE id = $1::integer
  AND project_id = $2::integer
LIMIT 1
`

type GetCurrentConfigurationParams struct {
	ConfigurationID int32 `db:"configuration_id" json:"configuration_id"`
	ProjectID       int32 `db:"project_id" json:"project_id"`
}

type GetCurrentConfigurationRow struct {
	ID                int32            `db:"id" json:"id"`
	ConfigurationUuid string           `db:"configuration_uuid" json:"configuration_uuid"`
	ProjectID         int32            `db:"project_id" json:"project_id"`
	Label             *string          `db:"label" json:"label"`
	EliteaTitle       string           `db:"elitea_title" json:"elitea_title"`
	Type              string           `db:"type" json:"type"`
	Section           string           `db:"section" json:"section"`
	Data              []byte           `db:"data" json:"data"`
	Meta              []byte           `db:"meta" json:"meta"`
	Shared            bool             `db:"shared" json:"shared"`
	StatusOk          bool             `db:"status_ok" json:"status_ok"`
	StatusLogs        *string          `db:"status_logs" json:"status_logs"`
	Source            string           `db:"source" json:"source"`
	AuthorID          *int32           `db:"author_id" json:"author_id"`
	CreatedAt         pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt         pgtype.Timestamp `db:"updated_at" json:"updated_at"`
}

// These unqualified names are intentional. Every query is executed inside a
// transaction whose local search_path is derived from the authorized project.
// This file projects the existing 16-column tenant table; it does not define a
// replacement configuration store.
func (q *Queries) GetCurrentConfiguration(ctx context.Context, arg GetCurrentConfigurationParams) (GetCurrentConfigurationRow, error) {
	row := q.db.QueryRow(ctx, getCurrentConfiguration, arg.ConfigurationID, arg.ProjectID)
	var i GetCurrentConfigurationRow
	err := row.Scan(
		&i.ID,
		&i.ConfigurationUuid,
		&i.ProjectID,
		&i.Label,
		&i.EliteaTitle,
		&i.Type,
		&i.Section,
		&i.Data,
		&i.Meta,
		&i.Shared,
		&i.StatusOk,
		&i.StatusLogs,
		&i.Source,
		&i.AuthorID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertCurrentConfiguration = `-- name: InsertCurrentConfiguration :one
INSERT INTO configuration (
    uuid, project_id, label, elitea_title, type, section, data, meta, shared,
    status_ok, status_logs, source, author_id
) VALUES (
    $1::text::uuid,
    $2::integer,
    $3::text,
    $4::text,
    $5::text,
    $6::text,
    $7::jsonb,
    $8::jsonb,
    $9::boolean,
    $10::boolean,
    $11::text,
    $12::text,
    $13::integer
)
RETURNING id,
          uuid::text AS configuration_uuid,
          project_id,
          label,
          elitea_title,
          type,
          section,
          data,
          meta,
          shared,
          status_ok,
          status_logs,
          source,
          author_id,
          created_at,
          updated_at
`

type InsertCurrentConfigurationParams struct {
	ConfigurationUuid string  `db:"configuration_uuid" json:"configuration_uuid"`
	ProjectID         int32   `db:"project_id" json:"project_id"`
	Label             *string `db:"label" json:"label"`
	EliteaTitle       string  `db:"elitea_title" json:"elitea_title"`
	ConfigurationType string  `db:"configuration_type" json:"configuration_type"`
	Section           string  `db:"section" json:"section"`
	Data              []byte  `db:"data" json:"data"`
	Meta              []byte  `db:"meta" json:"meta"`
	Shared            bool    `db:"shared" json:"shared"`
	StatusOk          bool    `db:"status_ok" json:"status_ok"`
	StatusLogs        *string `db:"status_logs" json:"status_logs"`
	Source            string  `db:"source" json:"source"`
	AuthorID          *int32  `db:"author_id" json:"author_id"`
}

type InsertCurrentConfigurationRow struct {
	ID                int32            `db:"id" json:"id"`
	ConfigurationUuid string           `db:"configuration_uuid" json:"configuration_uuid"`
	ProjectID         int32            `db:"project_id" json:"project_id"`
	Label             *string          `db:"label" json:"label"`
	EliteaTitle       string           `db:"elitea_title" json:"elitea_title"`
	Type              string           `db:"type" json:"type"`
	Section           string           `db:"section" json:"section"`
	Data              []byte           `db:"data" json:"data"`
	Meta              []byte           `db:"meta" json:"meta"`
	Shared            bool             `db:"shared" json:"shared"`
	StatusOk          bool             `db:"status_ok" json:"status_ok"`
	StatusLogs        *string          `db:"status_logs" json:"status_logs"`
	Source            string           `db:"source" json:"source"`
	AuthorID          *int32           `db:"author_id" json:"author_id"`
	CreatedAt         pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt         pgtype.Timestamp `db:"updated_at" json:"updated_at"`
}

func (q *Queries) InsertCurrentConfiguration(ctx context.Context, arg InsertCurrentConfigurationParams) (InsertCurrentConfigurationRow, error) {
	row := q.db.QueryRow(ctx, insertCurrentConfiguration,
		arg.ConfigurationUuid,
		arg.ProjectID,
		arg.Label,
		arg.EliteaTitle,
		arg.ConfigurationType,
		arg.Section,
		arg.Data,
		arg.Meta,
		arg.Shared,
		arg.StatusOk,
		arg.StatusLogs,
		arg.Source,
		arg.AuthorID,
	)
	var i InsertCurrentConfigurationRow
	err := row.Scan(
		&i.ID,
		&i.ConfigurationUuid,
		&i.ProjectID,
		&i.Label,
		&i.EliteaTitle,
		&i.Type,
		&i.Section,
		&i.Data,
		&i.Meta,
		&i.Shared,
		&i.StatusOk,
		&i.StatusLogs,
		&i.Source,
		&i.AuthorID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCurrentConfigurations = `-- name: ListCurrentConfigurations :many
SELECT id,
       uuid::text AS configuration_uuid,
       project_id,
       label,
       elitea_title,
       type,
       section,
       data,
       meta,
       shared,
       status_ok,
       status_logs,
       source,
       author_id,
       created_at,
       updated_at
FROM configuration
WHERE project_id = $1::integer
  AND (COALESCE(cardinality($2::text[]), 0) = 0 OR type = ANY($2::text[]))
  AND (COALESCE(cardinality($3::text[]), 0) = 0 OR section = ANY($3::text[]))
  AND ($4::text = '' OR label ILIKE ('%' || $4::text || '%'))
ORDER BY
  CASE WHEN $5::text = 'asc'  AND $6::text = 'id'            THEN id END ASC,
  CASE WHEN $5::text = 'desc' AND $6::text = 'id'            THEN id END DESC,
  CASE WHEN $5::text = 'asc'  AND $6::text = 'uuid'          THEN uuid END ASC,
  CASE WHEN $5::text = 'desc' AND $6::text = 'uuid'          THEN uuid END DESC,
  CASE WHEN $5::text = 'asc'  AND $6::text = 'project_id'    THEN project_id END ASC,
  CASE WHEN $5::text = 'desc' AND $6::text = 'project_id'    THEN project_id END DESC,
  CASE WHEN $5::text = 'asc'  AND $6::text = 'label'         THEN label END ASC NULLS LAST,
  CASE WHEN $5::text = 'desc' AND $6::text = 'label'         THEN label END DESC NULLS LAST,
  CASE WHEN $5::text = 'asc'  AND $6::text = 'elitea_title'  THEN elitea_title END ASC,
  CASE WHEN $5::text = 'desc' AND $6::text = 'elitea_title'  THEN elitea_title END DESC,
  CASE WHEN $5::text = 'asc'  AND $6::text = 'type'          THEN type END ASC,
  CASE WHEN $5::text = 'desc' AND $6::text = 'type'          THEN type END DESC,
  CASE WHEN $5::text = 'asc'  AND $6::text = 'section'       THEN section END ASC,
  CASE WHEN $5::text = 'desc' AND $6::text = 'section'       THEN section END DESC,
  CASE WHEN $5::text = 'asc'  AND $6::text = 'data'          THEN data END ASC,
  CASE WHEN $5::text = 'desc' AND $6::text = 'data'          THEN data END DESC,
  CASE WHEN $5::text = 'asc'  AND $6::text = 'meta'          THEN meta END ASC,
  CASE WHEN $5::text = 'desc' AND $6::text = 'meta'          THEN meta END DESC,
  CASE WHEN $5::text = 'asc'  AND $6::text = 'shared'        THEN shared END ASC,
  CASE WHEN $5::text = 'desc' AND $6::text = 'shared'        THEN shared END DESC,
  CASE WHEN $5::text = 'asc'  AND $6::text = 'status_ok'     THEN status_ok END ASC,
  CASE WHEN $5::text = 'desc' AND $6::text = 'status_ok'     THEN status_ok END DESC,
  CASE WHEN $5::text = 'asc'  AND $6::text = 'status_logs'   THEN status_logs END ASC NULLS LAST,
  CASE WHEN $5::text = 'desc' AND $6::text = 'status_logs'   THEN status_logs END DESC NULLS LAST,
  CASE WHEN $5::text = 'asc'  AND $6::text = 'source'        THEN source END ASC,
  CASE WHEN $5::text = 'desc' AND $6::text = 'source'        THEN source END DESC,
  CASE WHEN $5::text = 'asc'  AND $6::text = 'author_id'     THEN author_id END ASC NULLS LAST,
  CASE WHEN $5::text = 'desc' AND $6::text = 'author_id'     THEN author_id END DESC NULLS LAST,
  CASE WHEN $5::text = 'asc'  AND $6::text = 'created_at'    THEN created_at END ASC,
  CASE WHEN $5::text = 'desc' AND $6::text = 'created_at'    THEN created_at END DESC,
  CASE WHEN $5::text = 'asc'  AND $6::text = 'updated_at'    THEN updated_at END ASC NULLS LAST,
  CASE WHEN $5::text = 'desc' AND $6::text = 'updated_at'    THEN updated_at END DESC NULLS LAST,
  id ASC
LIMIT $8::integer
OFFSET $7::integer
`

type ListCurrentConfigurationsParams struct {
	ProjectID  int32    `db:"project_id" json:"project_id"`
	Types      []string `db:"types" json:"types"`
	Sections   []string `db:"sections" json:"sections"`
	LabelQuery string   `db:"label_query" json:"label_query"`
	SortOrder  string   `db:"sort_order" json:"sort_order"`
	SortBy     string   `db:"sort_by" json:"sort_by"`
	OffsetRows int32    `db:"offset_rows" json:"offset_rows"`
	LimitRows  int32    `db:"limit_rows" json:"limit_rows"`
}

type ListCurrentConfigurationsRow struct {
	ID                int32            `db:"id" json:"id"`
	ConfigurationUuid string           `db:"configuration_uuid" json:"configuration_uuid"`
	ProjectID         int32            `db:"project_id" json:"project_id"`
	Label             *string          `db:"label" json:"label"`
	EliteaTitle       string           `db:"elitea_title" json:"elitea_title"`
	Type              string           `db:"type" json:"type"`
	Section           string           `db:"section" json:"section"`
	Data              []byte           `db:"data" json:"data"`
	Meta              []byte           `db:"meta" json:"meta"`
	Shared            bool             `db:"shared" json:"shared"`
	StatusOk          bool             `db:"status_ok" json:"status_ok"`
	StatusLogs        *string          `db:"status_logs" json:"status_logs"`
	Source            string           `db:"source" json:"source"`
	AuthorID          *int32           `db:"author_id" json:"author_id"`
	CreatedAt         pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt         pgtype.Timestamp `db:"updated_at" json:"updated_at"`
}

func (q *Queries) ListCurrentConfigurations(ctx context.Context, arg ListCurrentConfigurationsParams) ([]ListCurrentConfigurationsRow, error) {
	rows, err := q.db.Query(ctx, listCurrentConfigurations,
		arg.ProjectID,
		arg.Types,
		arg.Sections,
		arg.LabelQuery,
		arg.SortOrder,
		arg.SortBy,
		arg.OffsetRows,
		arg.LimitRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCurrentConfigurationsRow{}
	for rows.Next() {
		var i ListCurrentConfigurationsRow
		if err := rows.Scan(
			&i.ID,
			&i.ConfigurationUuid,
			&i.ProjectID,
			&i.Label,
			&i.EliteaTitle,
			&i.Type,
			&i.Section,
			&i.Data,
			&i.Meta,
			&i.Shared,
			&i.StatusOk,
			&i.StatusLogs,
			&i.Source,
			&i.AuthorID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCurrentModelConfigurations = `-- name: ListCurrentModelConfigurations :many
SELECT id,
       project_id,
       label,
       elitea_title,
       section,
       data,
       shared
FROM configuration
WHERE project_id = $1::integer
  AND section = $2::text
  AND status_ok = true
  AND (NOT $3::boolean OR shared = true)
ORDER BY id ASC
LIMIT $4::integer
`

type ListCurrentModelConfigurationsParams struct {
	ProjectID  int32  `db:"project_id" json:"project_id"`
	Section    string `db:"section" json:"section"`
	SharedOnly bool   `db:"shared_only" json:"shared_only"`
	LimitRows  int32  `db:"limit_rows" json:"limit_rows"`
}

type ListCurrentModelConfigurationsRow struct {
	ID          int32   `db:"id" json:"id"`
	ProjectID   int32   `db:"project_id" json:"project_id"`
	Label       *string `db:"label" json:"label"`
	EliteaTitle string  `db:"elitea_title" json:"elitea_title"`
	Section     string  `db:"section" json:"section"`
	Data        []byte  `db:"data" json:"data"`
	Shared      bool    `db:"shared" json:"shared"`
}

// Raw data is intentional: the Go adapter performs type-safe, redacted
// decoding before applying section-specific response shaping. ID order gives
// duplicate candidates a deterministic baseline order.
func (q *Queries) ListCurrentModelConfigurations(ctx context.Context, arg ListCurrentModelConfigurationsParams) ([]ListCurrentModelConfigurationsRow, error) {
	rows, err := q.db.Query(ctx, listCurrentModelConfigurations,
		arg.ProjectID,
		arg.Section,
		arg.SharedOnly,
		arg.LimitRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCurrentModelConfigurationsRow{}
	for rows.Next() {
		var i ListCurrentModelConfigurationsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Label,
			&i.EliteaTitle,
			&i.Section,
			&i.Data,
			&i.Shared,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCurrentSharedConfigurations = `-- name: ListCurrentSharedConfigurations :many
SELECT id,
       uuid::text AS configuration_uuid,
       project_id,
       label,
       elitea_title,
       type,
       section,
       data,
       meta,
       shared,
       status_ok,
       status_logs,
       source,
       author_id,
       created_at,
       updated_at
FROM configuration
WHERE project_id = $1::integer
  AND shared = true
  AND (COALESCE(cardinality($2::text[]), 0) = 0 OR type = ANY($2::text[]))
  AND (COALESCE(cardinality($3::text[]), 0) = 0 OR section = ANY($3::text[]))
ORDER BY
  CASE WHEN $4::text = 'asc'  AND $5::text = 'id'            THEN id END ASC,
  CASE WHEN $4::text = 'desc' AND $5::text = 'id'            THEN id END DESC,
  CASE WHEN $4::text = 'asc'  AND $5::text = 'uuid'          THEN uuid END ASC,
  CASE WHEN $4::text = 'desc' AND $5::text = 'uuid'          THEN uuid END DESC,
  CASE WHEN $4::text = 'asc'  AND $5::text = 'project_id'    THEN project_id END ASC,
  CASE WHEN $4::text = 'desc' AND $5::text = 'project_id'    THEN project_id END DESC,
  CASE WHEN $4::text = 'asc'  AND $5::text = 'label'         THEN label END ASC NULLS LAST,
  CASE WHEN $4::text = 'desc' AND $5::text = 'label'         THEN label END DESC NULLS LAST,
  CASE WHEN $4::text = 'asc'  AND $5::text = 'elitea_title'  THEN elitea_title END ASC,
  CASE WHEN $4::text = 'desc' AND $5::text = 'elitea_title'  THEN elitea_title END DESC,
  CASE WHEN $4::text = 'asc'  AND $5::text = 'type'          THEN type END ASC,
  CASE WHEN $4::text = 'desc' AND $5::text = 'type'          THEN type END DESC,
  CASE WHEN $4::text = 'asc'  AND $5::text = 'section'       THEN section END ASC,
  CASE WHEN $4::text = 'desc' AND $5::text = 'section'       THEN section END DESC,
  CASE WHEN $4::text = 'asc'  AND $5::text = 'data'          THEN data END ASC,
  CASE WHEN $4::text = 'desc' AND $5::text = 'data'          THEN data END DESC,
  CASE WHEN $4::text = 'asc'  AND $5::text = 'meta'          THEN meta END ASC,
  CASE WHEN $4::text = 'desc' AND $5::text = 'meta'          THEN meta END DESC,
  CASE WHEN $4::text = 'asc'  AND $5::text = 'shared'        THEN shared END ASC,
  CASE WHEN $4::text = 'desc' AND $5::text = 'shared'        THEN shared END DESC,
  CASE WHEN $4::text = 'asc'  AND $5::text = 'status_ok'     THEN status_ok END ASC,
  CASE WHEN $4::text = 'desc' AND $5::text = 'status_ok'     THEN status_ok END DESC,
  CASE WHEN $4::text = 'asc'  AND $5::text = 'status_logs'   THEN status_logs END ASC NULLS LAST,
  CASE WHEN $4::text = 'desc' AND $5::text = 'status_logs'   THEN status_logs END DESC NULLS LAST,
  CASE WHEN $4::text = 'asc'  AND $5::text = 'source'        THEN source END ASC,
  CASE WHEN $4::text = 'desc' AND $5::text = 'source'        THEN source END DESC,
  CASE WHEN $4::text = 'asc'  AND $5::text = 'author_id'     THEN author_id END ASC NULLS LAST,
  CASE WHEN $4::text = 'desc' AND $5::text = 'author_id'     THEN author_id END DESC NULLS LAST,
  CASE WHEN $4::text = 'asc'  AND $5::text = 'created_at'    THEN created_at END ASC,
  CASE WHEN $4::text = 'desc' AND $5::text = 'created_at'    THEN created_at END DESC,
  CASE WHEN $4::text = 'asc'  AND $5::text = 'updated_at'    THEN updated_at END ASC NULLS LAST,
  CASE WHEN $4::text = 'desc' AND $5::text = 'updated_at'    THEN updated_at END DESC NULLS LAST,
  id ASC
LIMIT $7::integer
OFFSET $6::integer
`

type ListCurrentSharedConfigurationsParams struct {
	ProjectID  int32    `db:"project_id" json:"project_id"`
	Types      []string `db:"types" json:"types"`
	Sections   []string `db:"sections" json:"sections"`
	SortOrder  string   `db:"sort_order" json:"sort_order"`
	SortBy     string   `db:"sort_by" json:"sort_by"`
	OffsetRows int32    `db:"offset_rows" json:"offset_rows"`
	LimitRows  int32    `db:"limit_rows" json:"limit_rows"`
}

type ListCurrentSharedConfigurationsRow struct {
	ID                int32            `db:"id" json:"id"`
	ConfigurationUuid string           `db:"configuration_uuid" json:"configuration_uuid"`
	ProjectID         int32            `db:"project_id" json:"project_id"`
	Label             *string          `db:"label" json:"label"`
	EliteaTitle       string           `db:"elitea_title" json:"elitea_title"`
	Type              string           `db:"type" json:"type"`
	Section           string           `db:"section" json:"section"`
	Data              []byte           `db:"data" json:"data"`
	Meta              []byte           `db:"meta" json:"meta"`
	Shared            bool             `db:"shared" json:"shared"`
	StatusOk          bool             `db:"status_ok" json:"status_ok"`
	StatusLogs        *string          `db:"status_logs" json:"status_logs"`
	Source            string           `db:"source" json:"source"`
	AuthorID          *int32           `db:"author_id" json:"author_id"`
	CreatedAt         pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt         pgtype.Timestamp `db:"updated_at" json:"updated_at"`
}

func (q *Queries) ListCurrentSharedConfigurations(ctx context.Context, arg ListCurrentSharedConfigurationsParams) ([]ListCurrentSharedConfigurationsRow, error) {
	rows, err := q.db.Query(ctx, listCurrentSharedConfigurations,
		arg.ProjectID,
		arg.Types,
		arg.Sections,
		arg.SortOrder,
		arg.SortBy,
		arg.OffsetRows,
		arg.LimitRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCurrentSharedConfigurationsRow{}
	for rows.Next() {
		var i ListCurrentSharedConfigurationsRow
		if err := rows.Scan(
			&i.ID,
			&i.ConfigurationUuid,
			&i.ProjectID,
			&i.Label,
			&i.EliteaTitle,
			&i.Type,
			&i.Section,
			&i.Data,
			&i.Meta,
			&i.Shared,
			&i.StatusOk,
			&i.StatusLogs,
			&i.Source,
			&i.AuthorID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const replaceCurrentConfiguration = `-- name: ReplaceCurrentConfiguration :one
UPDATE configuration
SET label = $1::text,
    elitea_title = $2::text,
    data = $3::jsonb,
    meta = $4::jsonb,
    shared = $5::boolean,
    status_ok = $6::boolean,
    status_logs = $7::text,
    updated_at = now()
WHERE id = $8::integer
  AND project_id = $9::integer
RETURNING id,
          uuid::text AS configuration_uuid,
          project_id,
          label,
          elitea_title,
          type,
          section,
          data,
          meta,
          shared,
          status_ok,
          status_logs,
          source,
          author_id,
          created_at,
          updated_at
`

type ReplaceCurrentConfigurationParams struct {
	Label           *string `db:"label" json:"label"`
	EliteaTitle     string  `db:"elitea_title" json:"elitea_title"`
	Data            []byte  `db:"data" json:"data"`
	Meta            []byte  `db:"meta" json:"meta"`
	Shared          bool    `db:"shared" json:"shared"`
	StatusOk        bool    `db:"status_ok" json:"status_ok"`
	StatusLogs      *string `db:"status_logs" json:"status_logs"`
	ConfigurationID int32   `db:"configuration_id" json:"configuration_id"`
	ProjectID       int32   `db:"project_id" json:"project_id"`
}

type ReplaceCurrentConfigurationRow struct {
	ID                int32            `db:"id" json:"id"`
	ConfigurationUuid string           `db:"configuration_uuid" json:"configuration_uuid"`
	ProjectID         int32            `db:"project_id" json:"project_id"`
	Label             *string          `db:"label" json:"label"`
	EliteaTitle       string           `db:"elitea_title" json:"elitea_title"`
	Type              string           `db:"type" json:"type"`
	Section           string           `db:"section" json:"section"`
	Data              []byte           `db:"data" json:"data"`
	Meta              []byte           `db:"meta" json:"meta"`
	Shared            bool             `db:"shared" json:"shared"`
	StatusOk          bool             `db:"status_ok" json:"status_ok"`
	StatusLogs        *string          `db:"status_logs" json:"status_logs"`
	Source            string           `db:"source" json:"source"`
	AuthorID          *int32           `db:"author_id" json:"author_id"`
	CreatedAt         pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt         pgtype.Timestamp `db:"updated_at" json:"updated_at"`
}

func (q *Queries) ReplaceCurrentConfiguration(ctx context.Context, arg ReplaceCurrentConfigurationParams) (ReplaceCurrentConfigurationRow, error) {
	row := q.db.QueryRow(ctx, replaceCurrentConfiguration,
		arg.Label,
		arg.EliteaTitle,
		arg.Data,
		arg.Meta,
		arg.Shared,
		arg.StatusOk,
		arg.StatusLogs,
		arg.ConfigurationID,
		arg.ProjectID,
	)
	var i ReplaceCurrentConfigurationRow
	err := row.Scan(
		&i.ID,
		&i.ConfigurationUuid,
		&i.ProjectID,
		&i.Label,
		&i.EliteaTitle,
		&i.Type,
		&i.Section,
		&i.Data,
		&i.Meta,
		&i.Shared,
		&i.StatusOk,
		&i.StatusLogs,
		&i.Source,
		&i.AuthorID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
