// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: current_index_schedules.sql

package sqlcgen

import (
	"context"
)

const insertCurrentIndexScheduleNotification = `-- name: InsertCurrentIndexScheduleNotification :execrows
INSERT INTO centry.notifications (
    uuid,
    is_seen,
    project_id,
    user_id,
    meta,
    event_type
) VALUES (
    $1::text::uuid,
    FALSE,
    $2::integer,
    $3::integer,
    $4::jsonb,
    'index_data_changed'
)
ON CONFLICT (uuid) DO NOTHING
`

type InsertCurrentIndexScheduleNotificationParams struct {
	NotificationUuid string `db:"notification_uuid" json:"notification_uuid"`
	ProjectID        int32  `db:"project_id" json:"project_id"`
	UserID           int32  `db:"user_id" json:"user_id"`
	Meta             []byte `db:"meta" json:"meta"`
}

func (q *Queries) InsertCurrentIndexScheduleNotification(ctx context.Context, arg InsertCurrentIndexScheduleNotificationParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertCurrentIndexScheduleNotification,
		arg.NotificationUuid,
		arg.ProjectID,
		arg.UserID,
		arg.Meta,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const lockCurrentIndexScheduleToolkitMeta = `-- name: LockCurrentIndexScheduleToolkitMeta :one

SELECT meta
FROM elitea_tools
WHERE id = $1::integer
FOR UPDATE
`

// The unqualified toolkit table is intentional. These queries execute only
// inside an authorized project transaction whose local search_path is the
// exact p_<project_id> tenant schema.
func (q *Queries) LockCurrentIndexScheduleToolkitMeta(ctx context.Context, toolkitID int32) ([]byte, error) {
	row := q.db.QueryRow(ctx, lockCurrentIndexScheduleToolkitMeta, toolkitID)
	var meta []byte
	err := row.Scan(&meta)
	return meta, err
}

const updateCurrentIndexScheduleToolkitMeta = `-- name: UpdateCurrentIndexScheduleToolkitMeta :execrows
UPDATE elitea_tools
SET meta = $1::jsonb,
    updated_at = clock_timestamp()
WHERE id = $2::integer
`

type UpdateCurrentIndexScheduleToolkitMetaParams struct {
	Meta      []byte `db:"meta" json:"meta"`
	ToolkitID int32  `db:"toolkit_id" json:"toolkit_id"`
}

func (q *Queries) UpdateCurrentIndexScheduleToolkitMeta(ctx context.Context, arg UpdateCurrentIndexScheduleToolkitMetaParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateCurrentIndexScheduleToolkitMeta, arg.Meta, arg.ToolkitID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
