// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: current_configuration_mutations.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimConfigurationLifecycleEvents = `-- name: ClaimConfigurationLifecycleEvents :many
WITH authority_clock AS MATERIALIZED (
    SELECT clock_timestamp() AS observed_at
),
exhausted_locked AS MATERIALIZED (
    SELECT exhausted.event_id
    FROM elitea_runtime.configuration_lifecycle_outbox AS exhausted
    CROSS JOIN authority_clock
    WHERE exhausted.state = 'PROCESSING'
      AND exhausted.attempt_count = 1000
      AND exhausted.lease_expires_at <= authority_clock.observed_at
    ORDER BY exhausted.lease_expires_at, exhausted.event_id
    LIMIT $1::integer
    FOR UPDATE OF exhausted SKIP LOCKED
),
exhausted AS (
    UPDATE elitea_runtime.configuration_lifecycle_outbox AS outbox
    SET state = 'DEAD',
        lease_owner = NULL,
        lease_expires_at = NULL,
        delivered_at = NULL,
        dead_at = authority_clock.observed_at,
        last_error_code = 'ATTEMPTS_EXHAUSTED',
        updated_at = authority_clock.observed_at
    FROM exhausted_locked
    CROSS JOIN authority_clock
    WHERE outbox.event_id = exhausted_locked.event_id
    RETURNING outbox.event_id
),
exhaustion_barrier AS MATERIALIZED (
    SELECT count(*) AS retired_count
    FROM exhausted
),
locked AS MATERIALIZED (
    SELECT candidate.event_id
    FROM elitea_runtime.configuration_lifecycle_outbox AS candidate
    CROSS JOIN authority_clock
    CROSS JOIN exhaustion_barrier
    WHERE candidate.attempt_count < 1000
      AND (
          (
              candidate.state IN ('PENDING', 'RETRY')
              AND candidate.available_at <= authority_clock.observed_at
          )
          OR (
              candidate.state = 'PROCESSING'
              AND candidate.lease_expires_at <= authority_clock.observed_at
          )
      )
      AND NOT EXISTS (
          SELECT 1
          FROM elitea_runtime.configuration_lifecycle_outbox AS blocker
          WHERE blocker.resource_project_id = candidate.resource_project_id
            AND blocker.configuration_uuid = candidate.configuration_uuid
            AND blocker.revision < candidate.revision
            AND blocker.state IN ('PENDING', 'RETRY', 'PROCESSING', 'DEAD')
      )
    ORDER BY candidate.available_at, candidate.created_at, candidate.event_id
    LIMIT $1::integer
    FOR UPDATE OF candidate SKIP LOCKED
),
claimed AS (
    UPDATE elitea_runtime.configuration_lifecycle_outbox AS outbox
    SET state = 'PROCESSING',
        attempt_count = outbox.attempt_count + 1,
        last_attempt_at = authority_clock.observed_at,
        lease_owner = $2::text,
        lease_expires_at = authority_clock.observed_at
            + ($3::bigint * interval '1 millisecond'),
        delivered_at = NULL,
        dead_at = NULL,
        last_error_code = NULL,
        updated_at = authority_clock.observed_at
    FROM locked
    CROSS JOIN authority_clock
    WHERE outbox.event_id = locked.event_id
    RETURNING outbox.event_id::text AS event_id,
              outbox.resource_project_id,
              outbox.configuration_uuid::text AS configuration_uuid,
              outbox.revision,
              outbox.operation,
              outbox.actor_id,
              outbox.sanitized_snapshot,
              outbox.snapshot_digest,
              outbox.attempt_count,
              COALESCE(outbox.lease_owner, '') AS lease_token,
              outbox.available_at,
              outbox.created_at
)
SELECT event_id,
       resource_project_id,
       configuration_uuid,
       revision,
       operation,
       actor_id,
       sanitized_snapshot,
       snapshot_digest,
       attempt_count,
       lease_token
FROM claimed
ORDER BY available_at, created_at, event_id
`

type ClaimConfigurationLifecycleEventsParams struct {
	ClaimLimit     int32  `db:"claim_limit" json:"claim_limit"`
	LeaseToken     string `db:"lease_token" json:"lease_token"`
	LeaseTtlMillis int64  `db:"lease_ttl_millis" json:"lease_ttl_millis"`
}

type ClaimConfigurationLifecycleEventsRow struct {
	EventID           string `db:"event_id" json:"event_id"`
	ResourceProjectID int32  `db:"resource_project_id" json:"resource_project_id"`
	ConfigurationUuid string `db:"configuration_uuid" json:"configuration_uuid"`
	Revision          int64  `db:"revision" json:"revision"`
	Operation         string `db:"operation" json:"operation"`
	ActorID           int32  `db:"actor_id" json:"actor_id"`
	SanitizedSnapshot []byte `db:"sanitized_snapshot" json:"sanitized_snapshot"`
	SnapshotDigest    []byte `db:"snapshot_digest" json:"snapshot_digest"`
	AttemptCount      int32  `db:"attempt_count" json:"attempt_count"`
	LeaseToken        string `db:"lease_token" json:"lease_token"`
}

// Claim only the oldest unfinished revision for each configuration. A lower
// pending, retrying, processing, or dead revision remains an explicit ordering
// barrier. Expired processing rows are reclaimed with a new caller-owned lease
// token. Expired rows already at the attempt cap are retired in a bounded
// batch and remain dead ordering barriers. The transaction ends with this
// statement; reconciliation happens outside the database transaction.
func (q *Queries) ClaimConfigurationLifecycleEvents(ctx context.Context, arg ClaimConfigurationLifecycleEventsParams) ([]ClaimConfigurationLifecycleEventsRow, error) {
	rows, err := q.db.Query(ctx, claimConfigurationLifecycleEvents, arg.ClaimLimit, arg.LeaseToken, arg.LeaseTtlMillis)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClaimConfigurationLifecycleEventsRow{}
	for rows.Next() {
		var i ClaimConfigurationLifecycleEventsRow
		if err := rows.Scan(
			&i.EventID,
			&i.ResourceProjectID,
			&i.ConfigurationUuid,
			&i.Revision,
			&i.Operation,
			&i.ActorID,
			&i.SanitizedSnapshot,
			&i.SnapshotDigest,
			&i.AttemptCount,
			&i.LeaseToken,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestConfigurationLifecycleRevision = `-- name: GetLatestConfigurationLifecycleRevision :one
SELECT revision
FROM elitea_runtime.configuration_lifecycle_outbox
WHERE resource_project_id = $1::integer
  AND configuration_uuid = $2::text::uuid
ORDER BY revision DESC
LIMIT 1
`

type GetLatestConfigurationLifecycleRevisionParams struct {
	ProjectID         int32  `db:"project_id" json:"project_id"`
	ConfigurationUuid string `db:"configuration_uuid" json:"configuration_uuid"`
}

// The project vault row serializes configuration mutations for one project,
// so selecting the last indexed revision is sufficient inside the same
// transaction. The unique key remains the final integrity fence.
func (q *Queries) GetLatestConfigurationLifecycleRevision(ctx context.Context, arg GetLatestConfigurationLifecycleRevisionParams) (int64, error) {
	row := q.db.QueryRow(ctx, getLatestConfigurationLifecycleRevision, arg.ProjectID, arg.ConfigurationUuid)
	var revision int64
	err := row.Scan(&revision)
	return revision, err
}

const insertConfigurationLifecycleEvent = `-- name: InsertConfigurationLifecycleEvent :exec
INSERT INTO elitea_runtime.configuration_lifecycle_outbox (
    event_id,
    resource_project_id,
    configuration_uuid,
    revision,
    operation,
    actor_id,
    sanitized_snapshot,
    snapshot_digest
) VALUES (
    $1::text::uuid,
    $2::integer,
    $3::text::uuid,
    $4::bigint,
    $5::text,
    $6::integer,
    $7::json,
    $8::bytea
)
`

type InsertConfigurationLifecycleEventParams struct {
	EventID           string `db:"event_id" json:"event_id"`
	ProjectID         int32  `db:"project_id" json:"project_id"`
	ConfigurationUuid string `db:"configuration_uuid" json:"configuration_uuid"`
	Revision          int64  `db:"revision" json:"revision"`
	Operation         string `db:"operation" json:"operation"`
	ActorID           int32  `db:"actor_id" json:"actor_id"`
	SanitizedSnapshot []byte `db:"sanitized_snapshot" json:"sanitized_snapshot"`
	SnapshotDigest    []byte `db:"snapshot_digest" json:"snapshot_digest"`
}

func (q *Queries) InsertConfigurationLifecycleEvent(ctx context.Context, arg InsertConfigurationLifecycleEventParams) error {
	_, err := q.db.Exec(ctx, insertConfigurationLifecycleEvent,
		arg.EventID,
		arg.ProjectID,
		arg.ConfigurationUuid,
		arg.Revision,
		arg.Operation,
		arg.ActorID,
		arg.SanitizedSnapshot,
		arg.SnapshotDigest,
	)
	return err
}

const lockCurrentConfigurationForMutation = `-- name: LockCurrentConfigurationForMutation :one

SELECT id,
       uuid::text AS configuration_uuid,
       project_id,
       label,
       elitea_title,
       type,
       section,
       data,
       meta,
       shared,
       status_ok,
       status_logs,
       source,
       author_id,
       created_at,
       updated_at,
       false AS is_pinned
FROM configuration
WHERE id = $1::integer
  AND project_id = $2::integer
FOR UPDATE
`

type LockCurrentConfigurationForMutationParams struct {
	ConfigurationID int32 `db:"configuration_id" json:"configuration_id"`
	ProjectID       int32 `db:"project_id" json:"project_id"`
}

type LockCurrentConfigurationForMutationRow struct {
	ID                int32            `db:"id" json:"id"`
	ConfigurationUuid string           `db:"configuration_uuid" json:"configuration_uuid"`
	ProjectID         int32            `db:"project_id" json:"project_id"`
	Label             *string          `db:"label" json:"label"`
	EliteaTitle       string           `db:"elitea_title" json:"elitea_title"`
	Type              string           `db:"type" json:"type"`
	Section           string           `db:"section" json:"section"`
	Data              []byte           `db:"data" json:"data"`
	Meta              []byte           `db:"meta" json:"meta"`
	Shared            bool             `db:"shared" json:"shared"`
	StatusOk          bool             `db:"status_ok" json:"status_ok"`
	StatusLogs        *string          `db:"status_logs" json:"status_logs"`
	Source            string           `db:"source" json:"source"`
	AuthorID          *int32           `db:"author_id" json:"author_id"`
	CreatedAt         pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt         pgtype.Timestamp `db:"updated_at" json:"updated_at"`
	IsPinned          bool             `db:"is_pinned" json:"is_pinned"`
}

// The unqualified configuration relation is intentional. These queries run
// only inside a tenant transaction whose local search_path was derived from an
// already authorized positive project identity.
func (q *Queries) LockCurrentConfigurationForMutation(ctx context.Context, arg LockCurrentConfigurationForMutationParams) (LockCurrentConfigurationForMutationRow, error) {
	row := q.db.QueryRow(ctx, lockCurrentConfigurationForMutation, arg.ConfigurationID, arg.ProjectID)
	var i LockCurrentConfigurationForMutationRow
	err := row.Scan(
		&i.ID,
		&i.ConfigurationUuid,
		&i.ProjectID,
		&i.Label,
		&i.EliteaTitle,
		&i.Type,
		&i.Section,
		&i.Data,
		&i.Meta,
		&i.Shared,
		&i.StatusOk,
		&i.StatusLogs,
		&i.Source,
		&i.AuthorID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsPinned,
	)
	return i, err
}

const markConfigurationLifecycleDead = `-- name: MarkConfigurationLifecycleDead :execrows
UPDATE elitea_runtime.configuration_lifecycle_outbox AS outbox
SET state = 'DEAD',
    lease_owner = NULL,
    lease_expires_at = NULL,
    delivered_at = NULL,
    dead_at = authority_clock.observed_at,
    last_error_code = $1::text,
    updated_at = authority_clock.observed_at
FROM (SELECT clock_timestamp() AS observed_at) AS authority_clock
WHERE outbox.event_id = $2::text::uuid
  AND outbox.state = 'PROCESSING'
  AND outbox.lease_owner = $3::text
  AND outbox.lease_expires_at > authority_clock.observed_at
`

type MarkConfigurationLifecycleDeadParams struct {
	ErrorCode  string `db:"error_code" json:"error_code"`
	EventID    string `db:"event_id" json:"event_id"`
	LeaseToken string `db:"lease_token" json:"lease_token"`
}

func (q *Queries) MarkConfigurationLifecycleDead(ctx context.Context, arg MarkConfigurationLifecycleDeadParams) (int64, error) {
	result, err := q.db.Exec(ctx, markConfigurationLifecycleDead, arg.ErrorCode, arg.EventID, arg.LeaseToken)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markConfigurationLifecycleDelivered = `-- name: MarkConfigurationLifecycleDelivered :execrows
UPDATE elitea_runtime.configuration_lifecycle_outbox AS outbox
SET state = 'DELIVERED',
    lease_owner = NULL,
    lease_expires_at = NULL,
    delivered_at = authority_clock.observed_at,
    dead_at = NULL,
    last_error_code = NULL,
    updated_at = authority_clock.observed_at
FROM (SELECT clock_timestamp() AS observed_at) AS authority_clock
WHERE outbox.event_id = $1::text::uuid
  AND outbox.state = 'PROCESSING'
  AND outbox.lease_owner = $2::text
  AND outbox.lease_expires_at > authority_clock.observed_at
`

type MarkConfigurationLifecycleDeliveredParams struct {
	EventID    string `db:"event_id" json:"event_id"`
	LeaseToken string `db:"lease_token" json:"lease_token"`
}

func (q *Queries) MarkConfigurationLifecycleDelivered(ctx context.Context, arg MarkConfigurationLifecycleDeliveredParams) (int64, error) {
	result, err := q.db.Exec(ctx, markConfigurationLifecycleDelivered, arg.EventID, arg.LeaseToken)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markConfigurationLifecycleRetry = `-- name: MarkConfigurationLifecycleRetry :execrows
UPDATE elitea_runtime.configuration_lifecycle_outbox AS outbox
SET state = 'RETRY',
    available_at = authority_clock.observed_at
        + ($1::bigint * interval '1 millisecond'),
    lease_owner = NULL,
    lease_expires_at = NULL,
    delivered_at = NULL,
    dead_at = NULL,
    last_error_code = $2::text,
    updated_at = authority_clock.observed_at
FROM (SELECT clock_timestamp() AS observed_at) AS authority_clock
WHERE outbox.event_id = $3::text::uuid
  AND outbox.state = 'PROCESSING'
  AND outbox.lease_owner = $4::text
  AND outbox.lease_expires_at > authority_clock.observed_at
`

type MarkConfigurationLifecycleRetryParams struct {
	RetryDelayMillis int64  `db:"retry_delay_millis" json:"retry_delay_millis"`
	ErrorCode        string `db:"error_code" json:"error_code"`
	EventID          string `db:"event_id" json:"event_id"`
	LeaseToken       string `db:"lease_token" json:"lease_token"`
}

func (q *Queries) MarkConfigurationLifecycleRetry(ctx context.Context, arg MarkConfigurationLifecycleRetryParams) (int64, error) {
	result, err := q.db.Exec(ctx, markConfigurationLifecycleRetry,
		arg.RetryDelayMillis,
		arg.ErrorCode,
		arg.EventID,
		arg.LeaseToken,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
