// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: current_index_resolver.sql

package sqlcgen

import (
	"context"
)

const currentIndexEmbeddingModelExists = `-- name: CurrentIndexEmbeddingModelExists :one
SELECT EXISTS (
    SELECT 1
    FROM configuration
    WHERE project_id = $1::integer
      AND status_ok = true
      AND section = 'embedding'
      AND data->>'name' = $2::text
)
`

type CurrentIndexEmbeddingModelExistsParams struct {
	ProjectID int32  `db:"project_id" json:"project_id"`
	ModelName string `db:"model_name" json:"model_name"`
}

func (q *Queries) CurrentIndexEmbeddingModelExists(ctx context.Context, arg CurrentIndexEmbeddingModelExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, currentIndexEmbeddingModelExists, arg.ProjectID, arg.ModelName)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getCurrentIndexConfiguration = `-- name: GetCurrentIndexConfiguration :one
SELECT uuid::text AS configuration_uuid,
       project_id,
       type,
       data,
       shared,
       status_ok
FROM configuration
WHERE elitea_title = $1::text
LIMIT 1
`

type GetCurrentIndexConfigurationRow struct {
	ConfigurationUuid string `db:"configuration_uuid" json:"configuration_uuid"`
	ProjectID         int32  `db:"project_id" json:"project_id"`
	Type              string `db:"type" json:"type"`
	Data              []byte `db:"data" json:"data"`
	Shared            bool   `db:"shared" json:"shared"`
	StatusOk          bool   `db:"status_ok" json:"status_ok"`
}

func (q *Queries) GetCurrentIndexConfiguration(ctx context.Context, eliteaTitle string) (GetCurrentIndexConfigurationRow, error) {
	row := q.db.QueryRow(ctx, getCurrentIndexConfiguration, eliteaTitle)
	var i GetCurrentIndexConfigurationRow
	err := row.Scan(
		&i.ConfigurationUuid,
		&i.ProjectID,
		&i.Type,
		&i.Data,
		&i.Shared,
		&i.StatusOk,
	)
	return i, err
}

const getCurrentIndexLLMModel = `-- name: GetCurrentIndexLLMModel :one
SELECT project_id,
       shared,
       COALESCE(data->>'name', '')::text AS model_name,
       COALESCE(data->>'supports_reasoning', 'false')::boolean AS supports_reasoning,
       COALESCE(data->>'openai_compatible', 'false')::boolean AS openai_compatible,
       COALESCE(data->>'max_output_tokens', '0')::integer AS max_output_tokens
FROM configuration
WHERE project_id = $1::integer
  AND status_ok = true
  AND section = 'llm'
  AND data->>'name' = $2::text
ORDER BY COALESCE(data->>'max_output_tokens', '0')::integer DESC, id
LIMIT 1
`

type GetCurrentIndexLLMModelParams struct {
	ProjectID int32  `db:"project_id" json:"project_id"`
	ModelName string `db:"model_name" json:"model_name"`
}

type GetCurrentIndexLLMModelRow struct {
	ProjectID         int32  `db:"project_id" json:"project_id"`
	Shared            bool   `db:"shared" json:"shared"`
	ModelName         string `db:"model_name" json:"model_name"`
	SupportsReasoning bool   `db:"supports_reasoning" json:"supports_reasoning"`
	OpenaiCompatible  bool   `db:"openai_compatible" json:"openai_compatible"`
	MaxOutputTokens   int32  `db:"max_output_tokens" json:"max_output_tokens"`
}

func (q *Queries) GetCurrentIndexLLMModel(ctx context.Context, arg GetCurrentIndexLLMModelParams) (GetCurrentIndexLLMModelRow, error) {
	row := q.db.QueryRow(ctx, getCurrentIndexLLMModel, arg.ProjectID, arg.ModelName)
	var i GetCurrentIndexLLMModelRow
	err := row.Scan(
		&i.ProjectID,
		&i.Shared,
		&i.ModelName,
		&i.SupportsReasoning,
		&i.OpenaiCompatible,
		&i.MaxOutputTokens,
	)
	return i, err
}

const getCurrentIndexToolkit = `-- name: GetCurrentIndexToolkit :one

SELECT id, name, type, settings
FROM elitea_tools
WHERE id = $1::integer
LIMIT 1
`

type GetCurrentIndexToolkitRow struct {
	ID       int32   `db:"id" json:"id"`
	Name     *string `db:"name" json:"name"`
	Type     string  `db:"type" json:"type"`
	Settings []byte  `db:"settings" json:"settings"`
}

// These unqualified names are intentional. The repository executes every
// query inside a transaction whose local search_path is the authorized
// p_<project_id> schema.
func (q *Queries) GetCurrentIndexToolkit(ctx context.Context, toolkitID int32) (GetCurrentIndexToolkitRow, error) {
	row := q.db.QueryRow(ctx, getCurrentIndexToolkit, toolkitID)
	var i GetCurrentIndexToolkitRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Settings,
	)
	return i, err
}

const getCurrentSharedIndexConfiguration = `-- name: GetCurrentSharedIndexConfiguration :one
SELECT uuid::text AS configuration_uuid,
       project_id,
       type,
       data,
       shared,
       status_ok
FROM configuration
WHERE elitea_title = $1::text
  AND shared = true
LIMIT 1
`

type GetCurrentSharedIndexConfigurationRow struct {
	ConfigurationUuid string `db:"configuration_uuid" json:"configuration_uuid"`
	ProjectID         int32  `db:"project_id" json:"project_id"`
	Type              string `db:"type" json:"type"`
	Data              []byte `db:"data" json:"data"`
	Shared            bool   `db:"shared" json:"shared"`
	StatusOk          bool   `db:"status_ok" json:"status_ok"`
}

func (q *Queries) GetCurrentSharedIndexConfiguration(ctx context.Context, eliteaTitle string) (GetCurrentSharedIndexConfigurationRow, error) {
	row := q.db.QueryRow(ctx, getCurrentSharedIndexConfiguration, eliteaTitle)
	var i GetCurrentSharedIndexConfigurationRow
	err := row.Scan(
		&i.ConfigurationUuid,
		&i.ProjectID,
		&i.Type,
		&i.Data,
		&i.Shared,
		&i.StatusOk,
	)
	return i, err
}

const getSharedIndexLLMModel = `-- name: GetSharedIndexLLMModel :one
SELECT project_id,
       shared,
       COALESCE(data->>'name', '')::text AS model_name,
       COALESCE(data->>'supports_reasoning', 'false')::boolean AS supports_reasoning,
       COALESCE(data->>'openai_compatible', 'false')::boolean AS openai_compatible,
       COALESCE(data->>'max_output_tokens', '0')::integer AS max_output_tokens
FROM configuration
WHERE project_id = $1::integer
  AND shared = true
  AND status_ok = true
  AND section = 'llm'
  AND data->>'name' = $2::text
ORDER BY COALESCE(data->>'max_output_tokens', '0')::integer DESC, id
LIMIT 1
`

type GetSharedIndexLLMModelParams struct {
	ProjectID int32  `db:"project_id" json:"project_id"`
	ModelName string `db:"model_name" json:"model_name"`
}

type GetSharedIndexLLMModelRow struct {
	ProjectID         int32  `db:"project_id" json:"project_id"`
	Shared            bool   `db:"shared" json:"shared"`
	ModelName         string `db:"model_name" json:"model_name"`
	SupportsReasoning bool   `db:"supports_reasoning" json:"supports_reasoning"`
	OpenaiCompatible  bool   `db:"openai_compatible" json:"openai_compatible"`
	MaxOutputTokens   int32  `db:"max_output_tokens" json:"max_output_tokens"`
}

func (q *Queries) GetSharedIndexLLMModel(ctx context.Context, arg GetSharedIndexLLMModelParams) (GetSharedIndexLLMModelRow, error) {
	row := q.db.QueryRow(ctx, getSharedIndexLLMModel, arg.ProjectID, arg.ModelName)
	var i GetSharedIndexLLMModelRow
	err := row.Scan(
		&i.ProjectID,
		&i.Shared,
		&i.ModelName,
		&i.SupportsReasoning,
		&i.OpenaiCompatible,
		&i.MaxOutputTokens,
	)
	return i, err
}

const sharedIndexEmbeddingModelExists = `-- name: SharedIndexEmbeddingModelExists :one
SELECT EXISTS (
    SELECT 1
    FROM configuration
    WHERE project_id = $1::integer
      AND shared = true
      AND status_ok = true
      AND section = 'embedding'
      AND data->>'name' = $2::text
)
`

type SharedIndexEmbeddingModelExistsParams struct {
	ProjectID int32  `db:"project_id" json:"project_id"`
	ModelName string `db:"model_name" json:"model_name"`
}

func (q *Queries) SharedIndexEmbeddingModelExists(ctx context.Context, arg SharedIndexEmbeddingModelExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, sharedIndexEmbeddingModelExists, arg.ProjectID, arg.ModelName)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
