// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: current_notification_events.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const currentNotificationHighWater = `-- name: CurrentNotificationHighWater :one
SELECT COALESCE(MAX(id), 0)::bigint AS cursor
FROM centry.notifications
WHERE user_id = $1
`

func (q *Queries) CurrentNotificationHighWater(ctx context.Context, userID int32) (int64, error) {
	row := q.db.QueryRow(ctx, currentNotificationHighWater, userID)
	var cursor int64
	err := row.Scan(&cursor)
	return cursor, err
}

const listCurrentNotificationEventsAfter = `-- name: ListCurrentNotificationEventsAfter :many
SELECT id,
       uuid::text AS uuid,
       is_seen,
       project_id,
       user_id,
       meta,
       event_type,
       created_at,
       updated_at
FROM centry.notifications
WHERE user_id = $1
  AND id > $2
ORDER BY id
LIMIT $3
`

type ListCurrentNotificationEventsAfterParams struct {
	UserID      int32 `db:"user_id" json:"user_id"`
	AfterCursor int32 `db:"after_cursor" json:"after_cursor"`
	PageLimit   int32 `db:"page_limit" json:"page_limit"`
}

type ListCurrentNotificationEventsAfterRow struct {
	ID        int32            `db:"id" json:"id"`
	Uuid      string           `db:"uuid" json:"uuid"`
	IsSeen    bool             `db:"is_seen" json:"is_seen"`
	ProjectID int32            `db:"project_id" json:"project_id"`
	UserID    int32            `db:"user_id" json:"user_id"`
	Meta      []byte           `db:"meta" json:"meta"`
	EventType string           `db:"event_type" json:"event_type"`
	CreatedAt pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamp `db:"updated_at" json:"updated_at"`
}

func (q *Queries) ListCurrentNotificationEventsAfter(ctx context.Context, arg ListCurrentNotificationEventsAfterParams) ([]ListCurrentNotificationEventsAfterRow, error) {
	rows, err := q.db.Query(ctx, listCurrentNotificationEventsAfter, arg.UserID, arg.AfterCursor, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCurrentNotificationEventsAfterRow{}
	for rows.Next() {
		var i ListCurrentNotificationEventsAfterRow
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.IsSeen,
			&i.ProjectID,
			&i.UserID,
			&i.Meta,
			&i.EventType,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
