// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: current_pgvector.sql

package sqlcgen

import (
	"context"
)

const upsertCurrentProjectPgvectorConfiguration = `-- name: UpsertCurrentProjectPgvectorConfiguration :one

INSERT INTO configuration (
    uuid,
    project_id,
    label,
    elitea_title,
    type,
    section,
    data,
    meta,
    shared,
    status_ok,
    status_logs,
    source,
    author_id
) VALUES (
    $1::text::uuid,
    $2::integer,
    $3::text,
    $4::text,
    'pgvector',
    'vectorstorage',
    jsonb_build_object(
        'connection_string',
        '{{secret.pgvector_project_connstr}}'::text
    ),
    '{}'::jsonb,
    false,
    true,
    NULL,
    'system',
    NULL
)
ON CONFLICT (elitea_title) DO UPDATE
SET data = EXCLUDED.data,
    updated_at = now()
WHERE configuration.project_id = EXCLUDED.project_id
  AND configuration.type = EXCLUDED.type
  AND configuration.section = EXCLUDED.section
  AND configuration.source = EXCLUDED.source
RETURNING id
`

type UpsertCurrentProjectPgvectorConfigurationParams struct {
	ConfigurationUuid string  `db:"configuration_uuid" json:"configuration_uuid"`
	ProjectID         int32   `db:"project_id" json:"project_id"`
	Label             *string `db:"label" json:"label"`
	EliteaTitle       string  `db:"elitea_title" json:"elitea_title"`
}

// The project transaction establishes the authorized p_<project_id>
// search_path before this statement runs. The public PgVector bootstrap
// configuration is never copied into this tenant row: only the current vault
// reference is stored.
func (q *Queries) UpsertCurrentProjectPgvectorConfiguration(ctx context.Context, arg UpsertCurrentProjectPgvectorConfigurationParams) (int32, error) {
	row := q.db.QueryRow(ctx, upsertCurrentProjectPgvectorConfiguration,
		arg.ConfigurationUuid,
		arg.ProjectID,
		arg.Label,
		arg.EliteaTitle,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}
