// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: current_toolkits.sql

package sqlcgen

import (
	"context"
)

const getCurrentToolkit = `-- name: GetCurrentToolkit :one

SELECT id,
       created_at,
       updated_at,
       type,
       name,
       description,
       settings,
       author_id,
       shared_owner_id,
       shared_id,
       meta
FROM elitea_tools
WHERE id = $1::integer
LIMIT 1
`

// The unqualified table name is intentional. This query runs only inside an
// authorized project transaction whose local search_path is p_<project_id>.
func (q *Queries) GetCurrentToolkit(ctx context.Context, toolkitID int32) (EliteaTool, error) {
	row := q.db.QueryRow(ctx, getCurrentToolkit, toolkitID)
	var i EliteaTool
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Type,
		&i.Name,
		&i.Description,
		&i.Settings,
		&i.AuthorID,
		&i.SharedOwnerID,
		&i.SharedID,
		&i.Meta,
	)
	return i, err
}
