// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: current_agent_chat.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertCurrentApplicationTurn = `-- name: InsertCurrentApplicationTurn :one
WITH resolved AS MATERIALIZED (
    SELECT conversation.id AS conversation_id,
           author_participant.id AS author_participant_id,
           target_participant.id AS target_participant_id
    FROM chat_conversations AS conversation
    JOIN chat_participant_mapping AS author_mapping
      ON author_mapping.conversation_id = conversation.id
    JOIN chat_participants AS author_participant
      ON author_participant.id = author_mapping.participant_id
     AND author_participant.entity_name = 'user'
     AND (author_participant.entity_meta ->> 'id')::bigint = $1::bigint
    JOIN chat_participant_mapping AS target_mapping
      ON target_mapping.conversation_id = conversation.id
     AND target_mapping.participant_id = $2::integer
    JOIN chat_participants AS target_participant
      ON target_participant.id = target_mapping.participant_id
     AND target_participant.entity_name = 'application'
    JOIN application_versions AS application_version
      ON application_version.id = $3::integer
     AND application_version.id = (target_mapping.entity_settings ->> 'version_id')::integer
     AND application_version.application_id = $4::integer
     AND application_version.application_id = (target_participant.entity_meta ->> 'id')::integer
    WHERE conversation.uuid = $5::uuid
      AND (target_participant.entity_meta ->> 'project_id')::integer = $6::integer
      AND application_version.agent_type <> 'pipeline'
      AND COALESCE(conversation.meta -> 'internal_tools', '[]'::jsonb) = '[]'::jsonb
      AND COALESCE(
          conversation.meta #>> '{context_analytics,last_summarization,summary_content}',
          ''
      ) = ''
      AND NOT EXISTS (
          SELECT 1
          FROM chat_message_group AS pending_response
          WHERE pending_response.conversation_id = conversation.id
            AND pending_response.is_streaming
      )
      AND NOT EXISTS (
          SELECT 1
          FROM chat_message_group AS historical_group
          JOIN chat_message_items AS historical_item
            ON historical_item.message_group_id = historical_group.id
          WHERE historical_group.conversation_id = conversation.id
            AND historical_item.item_type IN (
                'attachment_message',
                'canvas_message',
                'context_message'
            )
      )
), question_group AS (
    INSERT INTO chat_message_group (
        uuid, author_participant_id, conversation_id, sent_to_id, meta,
        is_streaming, created_at
    )
    SELECT $7::uuid,
           resolved.author_participant_id,
           resolved.conversation_id,
           resolved.target_participant_id,
           $8::jsonb,
           FALSE,
           clock_timestamp()
    FROM resolved
    RETURNING id, uuid, conversation_id, sent_to_id
), question_item AS (
    INSERT INTO chat_message_items (
        uuid, item_type, order_index, meta, message_group_id
    )
    SELECT $9::uuid,
           'text_message',
           0,
           '{}'::jsonb,
           question_group.id
    FROM question_group
    RETURNING id
), question_text AS (
    INSERT INTO chat_messages_text (id, content)
    SELECT question_item.id, $10::text
    FROM question_item
), response_group AS (
    INSERT INTO chat_message_group (
        uuid, author_participant_id, conversation_id, reply_to_id, meta,
        is_streaming, created_at, task_id
    )
    SELECT $11::uuid,
           question_group.sent_to_id,
           question_group.conversation_id,
           question_group.id,
           jsonb_build_object(
               'execution_generation',
               $12::text
           ),
           TRUE,
           clock_timestamp() + interval '1 second',
           $13::text
    FROM question_group
    RETURNING id, uuid
)
SELECT response_group.id AS response_message_group_id,
       response_group.uuid AS response_message_id
FROM response_group
`

type InsertCurrentApplicationTurnParams struct {
	ActorUserID          int64       `db:"actor_user_id" json:"actor_user_id"`
	TargetParticipantID  int32       `db:"target_participant_id" json:"target_participant_id"`
	ApplicationVersionID int32       `db:"application_version_id" json:"application_version_id"`
	ApplicationID        int32       `db:"application_id" json:"application_id"`
	ConversationUuid     pgtype.UUID `db:"conversation_uuid" json:"conversation_uuid"`
	ProjectID            int32       `db:"project_id" json:"project_id"`
	QuestionID           pgtype.UUID `db:"question_id" json:"question_id"`
	QuestionMeta         []byte      `db:"question_meta" json:"question_meta"`
	QuestionItemID       pgtype.UUID `db:"question_item_id" json:"question_item_id"`
	UserInput            string      `db:"user_input" json:"user_input"`
	ResponseMessageID    pgtype.UUID `db:"response_message_id" json:"response_message_id"`
	ExecutionGeneration  string      `db:"execution_generation" json:"execution_generation"`
	ExecutionID          string      `db:"execution_id" json:"execution_id"`
}

type InsertCurrentApplicationTurnRow struct {
	ResponseMessageGroupID int32       `db:"response_message_group_id" json:"response_message_group_id"`
	ResponseMessageID      pgtype.UUID `db:"response_message_id" json:"response_message_id"`
}

func (q *Queries) InsertCurrentApplicationTurn(ctx context.Context, arg InsertCurrentApplicationTurnParams) (InsertCurrentApplicationTurnRow, error) {
	row := q.db.QueryRow(ctx, insertCurrentApplicationTurn,
		arg.ActorUserID,
		arg.TargetParticipantID,
		arg.ApplicationVersionID,
		arg.ApplicationID,
		arg.ConversationUuid,
		arg.ProjectID,
		arg.QuestionID,
		arg.QuestionMeta,
		arg.QuestionItemID,
		arg.UserInput,
		arg.ResponseMessageID,
		arg.ExecutionGeneration,
		arg.ExecutionID,
	)
	var i InsertCurrentApplicationTurnRow
	err := row.Scan(&i.ResponseMessageGroupID, &i.ResponseMessageID)
	return i, err
}

const lockCurrentAgentConversation = `-- name: LockCurrentAgentConversation :one
SELECT id
FROM chat_conversations
WHERE uuid = $1::uuid
FOR UPDATE
`

func (q *Queries) LockCurrentAgentConversation(ctx context.Context, conversationUuid pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, lockCurrentAgentConversation, conversationUuid)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const resolveCurrentApplicationTurn = `-- name: ResolveCurrentApplicationTurn :one
SELECT conversation.id AS conversation_id,
       author_participant.id AS author_participant_id,
       target_participant.id AS target_participant_id,
       (target_participant.entity_meta ->> 'id')::integer AS application_id,
       (target_participant.entity_meta ->> 'project_id')::integer AS application_project_id,
       (target_mapping.entity_settings ->> 'version_id')::integer AS application_version_id,
       COALESCE(target_mapping.entity_settings -> 'variables', '[]'::jsonb)::text AS application_variables_json,
       COALESCE(current_history.chat_history, '[]'::jsonb)::text AS chat_history_json,
       jsonb_build_object(
           'id', application_version.id,
           'application_id', application_version.application_id,
           'name', application_version.name,
           'status', application_version.status,
           'created_at', application_version.created_at,
           'agent_type', application_version.agent_type,
           'instructions', COALESCE(application_version.instructions, ''),
           'welcome_message', COALESCE(application_version.welcome_message, ''),
           'llm_settings', COALESCE(NULLIF(application_version.llm_settings::jsonb, 'null'::jsonb), '{}'::jsonb),
           'meta', COALESCE(NULLIF(application_version.meta::jsonb, 'null'::jsonb), '{}'::jsonb),
           'conversation_starters', COALESCE(NULLIF(application_version.conversation_starters::jsonb, 'null'::jsonb), '[]'::jsonb),
           'pipeline_settings', COALESCE(NULLIF(application_version.pipeline_settings::jsonb, 'null'::jsonb), '{}'::jsonb),
           'author_id', application_version.author_id,
           'tools', COALESCE((
               SELECT jsonb_agg(
                   jsonb_build_object(
                       'id', tool.id,
                       'type', tool.type,
                       'name', tool.name,
                       'description', tool.description,
                       'author_id', tool.author_id,
                       'settings', CASE
                           WHEN jsonb_typeof(tool.settings -> 'selected_tools') = 'array'
                            AND jsonb_array_length(tool.settings -> 'selected_tools') > 0
                           THEN tool.settings
                                || jsonb_build_object(
                                       'available_tools', tool.settings -> 'selected_tools'
                                   )
                                || CASE
                                       WHEN jsonb_typeof(application_tool_mapping.selected_tools) = 'array'
                                        AND jsonb_array_length(application_tool_mapping.selected_tools) > 0
                                       THEN jsonb_build_object(
                                           'selected_tools', CASE
                                               WHEN jsonb_array_length(selected_tools_intersection.value) > 0
                                               THEN selected_tools_intersection.value
                                               ELSE application_tool_mapping.selected_tools
                                           END
                                       )
                                       ELSE '{}'::jsonb
                                   END
                           WHEN jsonb_typeof(application_tool_mapping.selected_tools) = 'array'
                            AND jsonb_array_length(application_tool_mapping.selected_tools) > 0
                           THEN tool.settings || jsonb_build_object(
                               'selected_tools', application_tool_mapping.selected_tools
                           )
                           ELSE tool.settings
                       END,
                       'meta', tool.meta,
                       'created_at', tool.created_at,
                       'toolkit_name', tool.name,
                       'author', NULL,
                       'agent_type', NULL,
                       'online', NULL,
                       'icon_meta', NULL,
                       'variables', '[]'::jsonb,
                       'is_pinned', FALSE,
                       'indexes_count', NULL
                   )
                   ORDER BY application_tool_mapping.id
               )
               FROM entity_tool_mapping AS application_tool_mapping
               JOIN elitea_tools AS tool
                 ON tool.id = application_tool_mapping.tool_id
               LEFT JOIN LATERAL (
                   SELECT COALESCE(
                       jsonb_agg(selected.value ORDER BY selected.ordinality),
                       '[]'::jsonb
                   ) AS value
                   FROM jsonb_array_elements_text(
                       CASE
                           WHEN jsonb_typeof(application_tool_mapping.selected_tools) = 'array'
                           THEN application_tool_mapping.selected_tools
                           ELSE '[]'::jsonb
                       END
                   ) WITH ORDINALITY AS selected(value, ordinality)
                   WHERE jsonb_typeof(tool.settings -> 'selected_tools') = 'array'
                     AND tool.settings -> 'selected_tools' ? selected.value
               ) AS selected_tools_intersection ON TRUE
               WHERE application_tool_mapping.entity_version_id = application_version.id
                 AND application_tool_mapping.entity_id = application_version.application_id
                 AND application_tool_mapping.entity_type = 'agent'
           ), '[]'::jsonb),
           'tags', '[]'::jsonb,
           'variables', '[]'::jsonb
       )::text AS application_version_details_json
FROM chat_conversations AS conversation
JOIN chat_participant_mapping AS author_mapping
  ON author_mapping.conversation_id = conversation.id
JOIN chat_participants AS author_participant
  ON author_participant.id = author_mapping.participant_id
 AND author_participant.entity_name = 'user'
 AND (author_participant.entity_meta ->> 'id')::bigint = $1::bigint
JOIN chat_participant_mapping AS target_mapping
  ON target_mapping.conversation_id = conversation.id
 AND target_mapping.participant_id = $2::integer
JOIN chat_participants AS target_participant
  ON target_participant.id = target_mapping.participant_id
 AND target_participant.entity_name = 'application'
JOIN application_versions AS application_version
  ON application_version.id = (target_mapping.entity_settings ->> 'version_id')::integer
 AND application_version.application_id = (target_participant.entity_meta ->> 'id')::integer
LEFT JOIN LATERAL (
    SELECT jsonb_agg(
               jsonb_build_object(
                   'role', history_group.role,
                   'content', history_group.content,
                   'additional_kwargs', '{}'::jsonb
               )
               ORDER BY history_group.created_at, history_group.id
           ) AS chat_history
    FROM (
        SELECT message_group.id,
               message_group.created_at,
               CASE
                   WHEN author.entity_name = 'user' THEN 'user'
                   ELSE 'assistant'
               END AS role,
               jsonb_agg(
                   jsonb_build_object('type', 'text', 'text', message_text.content)
                   ORDER BY message_item.order_index, message_item.id
               ) FILTER (WHERE message_text.content <> '') AS content
        FROM chat_message_group AS message_group
        JOIN chat_participants AS author
          ON author.id = message_group.author_participant_id
        JOIN chat_message_items AS message_item
          ON message_item.message_group_id = message_group.id
         AND message_item.item_type = 'text_message'
        JOIN chat_messages_text AS message_text
          ON message_text.id = message_item.id
        WHERE message_group.conversation_id = conversation.id
          AND message_group.created_at < COALESCE(
              (
                  SELECT current_question.created_at
                  FROM chat_message_group AS current_question
                  WHERE current_question.conversation_id = conversation.id
                    AND current_question.uuid = $3::uuid
              ),
              statement_timestamp()
          )
        GROUP BY message_group.id, message_group.created_at, author.entity_name
    ) AS history_group
    WHERE jsonb_array_length(history_group.content) > 0
) AS current_history ON TRUE
WHERE conversation.uuid = $4::uuid
  AND (target_participant.entity_meta ->> 'project_id')::integer = $5::integer
  AND application_version.agent_type <> 'pipeline'
  AND COALESCE(conversation.meta -> 'internal_tools', '[]'::jsonb) = '[]'::jsonb
  AND COALESCE(
      conversation.meta #>> '{context_analytics,last_summarization,summary_content}',
      ''
  ) = ''
  AND NOT EXISTS (
      SELECT 1
      FROM chat_message_group AS pending_response
      WHERE pending_response.conversation_id = conversation.id
        AND pending_response.is_streaming
        AND NOT EXISTS (
            SELECT 1
            FROM chat_message_group AS retried_question
            WHERE retried_question.id = pending_response.reply_to_id
              AND retried_question.uuid = $3::uuid
        )
  )
  AND NOT EXISTS (
      SELECT 1
      FROM chat_message_group AS historical_group
      JOIN chat_message_items AS historical_item
        ON historical_item.message_group_id = historical_group.id
      WHERE historical_group.conversation_id = conversation.id
        AND historical_group.created_at < COALESCE(
            (
                SELECT current_question.created_at
                FROM chat_message_group AS current_question
                WHERE current_question.conversation_id = conversation.id
                  AND current_question.uuid = $3::uuid
            ),
            statement_timestamp()
        )
        AND historical_item.item_type IN (
            'attachment_message',
            'canvas_message',
            'context_message'
        )
  )
`

type ResolveCurrentApplicationTurnParams struct {
	ActorUserID         int64       `db:"actor_user_id" json:"actor_user_id"`
	TargetParticipantID int32       `db:"target_participant_id" json:"target_participant_id"`
	QuestionID          pgtype.UUID `db:"question_id" json:"question_id"`
	ConversationUuid    pgtype.UUID `db:"conversation_uuid" json:"conversation_uuid"`
	ProjectID           int32       `db:"project_id" json:"project_id"`
}

type ResolveCurrentApplicationTurnRow struct {
	ConversationID                int32  `db:"conversation_id" json:"conversation_id"`
	AuthorParticipantID           int32  `db:"author_participant_id" json:"author_participant_id"`
	TargetParticipantID           int32  `db:"target_participant_id" json:"target_participant_id"`
	ApplicationID                 int32  `db:"application_id" json:"application_id"`
	ApplicationProjectID          int32  `db:"application_project_id" json:"application_project_id"`
	ApplicationVersionID          int32  `db:"application_version_id" json:"application_version_id"`
	ApplicationVariablesJson      string `db:"application_variables_json" json:"application_variables_json"`
	ChatHistoryJson               string `db:"chat_history_json" json:"chat_history_json"`
	ApplicationVersionDetailsJson string `db:"application_version_details_json" json:"application_version_details_json"`
}

func (q *Queries) ResolveCurrentApplicationTurn(ctx context.Context, arg ResolveCurrentApplicationTurnParams) (ResolveCurrentApplicationTurnRow, error) {
	row := q.db.QueryRow(ctx, resolveCurrentApplicationTurn,
		arg.ActorUserID,
		arg.TargetParticipantID,
		arg.QuestionID,
		arg.ConversationUuid,
		arg.ProjectID,
	)
	var i ResolveCurrentApplicationTurnRow
	err := row.Scan(
		&i.ConversationID,
		&i.AuthorParticipantID,
		&i.TargetParticipantID,
		&i.ApplicationID,
		&i.ApplicationProjectID,
		&i.ApplicationVersionID,
		&i.ApplicationVariablesJson,
		&i.ChatHistoryJson,
		&i.ApplicationVersionDetailsJson,
	)
	return i, err
}
