// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: current_social_authors.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listCurrentProjectAuthors = `-- name: ListCurrentProjectAuthors :many
SELECT DISTINCT
    user_account.id,
    user_account.email,
    user_account.name,
    user_account.last_login,
    user_account.suspended,
    social_user.avatar
FROM public.auth_core__project_user_role AS assignment
JOIN public.auth_core__user AS user_account
    ON user_account.id = assignment.user_id
LEFT JOIN centry.social_users AS social_user
    ON social_user.user_id = user_account.id
WHERE assignment.project_id = $1::integer
  AND user_account.email IS DISTINCT FROM
      ('system_user_' || $1::integer::text || '@centry.user')
ORDER BY user_account.id
`

type ListCurrentProjectAuthorsRow struct {
	ID        int32            `db:"id" json:"id"`
	Email     *string          `db:"email" json:"email"`
	Name      *string          `db:"name" json:"name"`
	LastLogin pgtype.Timestamp `db:"last_login" json:"last_login"`
	Suspended bool             `db:"suspended" json:"suspended"`
	Avatar    *string          `db:"avatar" json:"avatar"`
}

func (q *Queries) ListCurrentProjectAuthors(ctx context.Context, projectID int32) ([]ListCurrentProjectAuthorsRow, error) {
	rows, err := q.db.Query(ctx, listCurrentProjectAuthors, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCurrentProjectAuthorsRow{}
	for rows.Next() {
		var i ListCurrentProjectAuthorsRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.LastLogin,
			&i.Suspended,
			&i.Avatar,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
