// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ApplicationVersion struct {
	ID                   int32            `db:"id" json:"id"`
	ApplicationID        int32            `db:"application_id" json:"application_id"`
	Name                 string           `db:"name" json:"name"`
	Status               string           `db:"status" json:"status"`
	AuthorID             int32            `db:"author_id" json:"author_id"`
	Uuid                 pgtype.UUID      `db:"uuid" json:"uuid"`
	CreatedAt            pgtype.Timestamp `db:"created_at" json:"created_at"`
	SharedOwnerID        *int32           `db:"shared_owner_id" json:"shared_owner_id"`
	SharedID             *int32           `db:"shared_id" json:"shared_id"`
	LlmSettings          []byte           `db:"llm_settings" json:"llm_settings"`
	Instructions         *string          `db:"instructions" json:"instructions"`
	ConversationStarters []byte           `db:"conversation_starters" json:"conversation_starters"`
	WelcomeMessage       string           `db:"welcome_message" json:"welcome_message"`
	AgentType            string           `db:"agent_type" json:"agent_type"`
	Meta                 []byte           `db:"meta" json:"meta"`
	PipelineSettings     []byte           `db:"pipeline_settings" json:"pipeline_settings"`
}

type AuthCoreGroup struct {
	ID       int32   `db:"id" json:"id"`
	ParentID *int32  `db:"parent_id" json:"parent_id"`
	Name     *string `db:"name" json:"name"`
}

type AuthCoreGroupPermission struct {
	GroupID    int32  `db:"group_id" json:"group_id"`
	ScopeID    int32  `db:"scope_id" json:"scope_id"`
	Permission string `db:"permission" json:"permission"`
}

type AuthCoreGroupProvider struct {
	GroupID     int32  `db:"group_id" json:"group_id"`
	ProviderRef string `db:"provider_ref" json:"provider_ref"`
}

type AuthCoreProjectRole struct {
	ID        int32  `db:"id" json:"id"`
	ProjectID int32  `db:"project_id" json:"project_id"`
	Name      string `db:"name" json:"name"`
}

type AuthCoreProjectRolePermission struct {
	ID         int32  `db:"id" json:"id"`
	ProjectID  int32  `db:"project_id" json:"project_id"`
	RoleID     *int32 `db:"role_id" json:"role_id"`
	Permission string `db:"permission" json:"permission"`
}

type AuthCoreProjectUserRole struct {
	ID        int32  `db:"id" json:"id"`
	ProjectID int32  `db:"project_id" json:"project_id"`
	UserID    *int32 `db:"user_id" json:"user_id"`
	RoleID    *int32 `db:"role_id" json:"role_id"`
}

type AuthCoreRole struct {
	ID   int32  `db:"id" json:"id"`
	Name string `db:"name" json:"name"`
	Mode string `db:"mode" json:"mode"`
}

type AuthCoreRolePermission struct {
	ID         int32   `db:"id" json:"id"`
	RoleID     int32   `db:"role_id" json:"role_id"`
	Permission *string `db:"permission" json:"permission"`
}

type AuthCoreScope struct {
	ID       int32   `db:"id" json:"id"`
	ParentID *int32  `db:"parent_id" json:"parent_id"`
	Name     *string `db:"name" json:"name"`
}

type AuthCoreToken struct {
	ID      int32            `db:"id" json:"id"`
	Uuid    *string          `db:"uuid" json:"uuid"`
	Expires pgtype.Timestamp `db:"expires" json:"expires"`
	UserID  *int32           `db:"user_id" json:"user_id"`
	Name    *string          `db:"name" json:"name"`
}

type AuthCoreUser struct {
	ID        int32            `db:"id" json:"id"`
	Email     *string          `db:"email" json:"email"`
	Name      *string          `db:"name" json:"name"`
	LastLogin pgtype.Timestamp `db:"last_login" json:"last_login"`
	Suspended bool             `db:"suspended" json:"suspended"`
}

type AuthCoreUserGroup struct {
	UserID  int32 `db:"user_id" json:"user_id"`
	GroupID int32 `db:"group_id" json:"group_id"`
}

type AuthCoreUserPermission struct {
	UserID     int32  `db:"user_id" json:"user_id"`
	ScopeID    int32  `db:"scope_id" json:"scope_id"`
	Permission string `db:"permission" json:"permission"`
}

type AuthCoreUserProvider struct {
	UserID      int32  `db:"user_id" json:"user_id"`
	ProviderRef string `db:"provider_ref" json:"provider_ref"`
}

type AuthCoreUserRole struct {
	ID     int32 `db:"id" json:"id"`
	UserID int32 `db:"user_id" json:"user_id"`
	RoleID int32 `db:"role_id" json:"role_id"`
}

type CentryProject struct {
	ID             int32    `db:"id" json:"id"`
	Name           string   `db:"name" json:"name"`
	OwnerID        int32    `db:"owner_id" json:"owner_id"`
	SecretsJson    []byte   `db:"secrets_json" json:"secrets_json"`
	Plugins        []string `db:"plugins" json:"plugins"`
	KeycloakGroups []byte   `db:"keycloak_groups" json:"keycloak_groups"`
	CreateSuccess  bool     `db:"create_success" json:"create_success"`
	Suspended      bool     `db:"suspended" json:"suspended"`
}

type CentryProjectGroup struct {
	ID   int32  `db:"id" json:"id"`
	Name string `db:"name" json:"name"`
}

type CentryProjectGroupAssociation struct {
	ProjectID *int32 `db:"project_id" json:"project_id"`
	GroupID   *int32 `db:"group_id" json:"group_id"`
}

type CentrySocialPin struct {
	ID        int32            `db:"id" json:"id"`
	Entity    string           `db:"entity" json:"entity"`
	UserID    int32            `db:"user_id" json:"user_id"`
	ProjectID *int32           `db:"project_id" json:"project_id"`
	EntityID  int32            `db:"entity_id" json:"entity_id"`
	CreatedAt pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamp `db:"updated_at" json:"updated_at"`
}

type CentrySocialUser struct {
	ID                       int32   `db:"id" json:"id"`
	UserID                   int32   `db:"user_id" json:"user_id"`
	Avatar                   *string `db:"avatar" json:"avatar"`
	Title                    *string `db:"title" json:"title"`
	Description              *string `db:"description" json:"description"`
	Personalization          []byte  `db:"personalization" json:"personalization"`
	DefaultContextManagement []byte  `db:"default_context_management" json:"default_context_management"`
	DefaultSummarization     []byte  `db:"default_summarization" json:"default_summarization"`
}

type Configuration struct {
	ID          int32            `db:"id" json:"id"`
	Uuid        pgtype.UUID      `db:"uuid" json:"uuid"`
	ProjectID   int32            `db:"project_id" json:"project_id"`
	Label       *string          `db:"label" json:"label"`
	EliteaTitle string           `db:"elitea_title" json:"elitea_title"`
	Type        string           `db:"type" json:"type"`
	Section     string           `db:"section" json:"section"`
	Data        []byte           `db:"data" json:"data"`
	Meta        []byte           `db:"meta" json:"meta"`
	Shared      bool             `db:"shared" json:"shared"`
	StatusOk    bool             `db:"status_ok" json:"status_ok"`
	StatusLogs  *string          `db:"status_logs" json:"status_logs"`
	Source      string           `db:"source" json:"source"`
	AuthorID    *int32           `db:"author_id" json:"author_id"`
	CreatedAt   pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamp `db:"updated_at" json:"updated_at"`
}

type EliteaRuntimeCommandOutbox struct {
	OutboxID                     string             `db:"outbox_id" json:"outbox_id"`
	ExecutionID                  string             `db:"execution_id" json:"execution_id"`
	Generation                   int64              `db:"generation" json:"generation"`
	StreamName                   string             `db:"stream_name" json:"stream_name"`
	DispatchOrdinal              int64              `db:"dispatch_ordinal" json:"dispatch_ordinal"`
	ResourceClass                string             `db:"resource_class" json:"resource_class"`
	IsolationClass               string             `db:"isolation_class" json:"isolation_class"`
	Priority                     int32              `db:"priority" json:"priority"`
	Deadline                     pgtype.Timestamptz `db:"deadline" json:"deadline"`
	LimitsRevision               string             `db:"limits_revision" json:"limits_revision"`
	Traceparent                  string             `db:"traceparent" json:"traceparent"`
	Tracestate                   string             `db:"tracestate" json:"tracestate"`
	CreatedAt                    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	PreparedSignedEnvelopeBytes  []byte             `db:"prepared_signed_envelope_bytes" json:"prepared_signed_envelope_bytes"`
	PreparedSignedEnvelopeDigest []byte             `db:"prepared_signed_envelope_digest" json:"prepared_signed_envelope_digest"`
	PreparedSignatureProfile     *int32             `db:"prepared_signature_profile" json:"prepared_signature_profile"`
	PreparedKeyID                *string            `db:"prepared_key_id" json:"prepared_key_id"`
	PreparedAt                   pgtype.Timestamptz `db:"prepared_at" json:"prepared_at"`
	PublishedAt                  pgtype.Timestamptz `db:"published_at" json:"published_at"`
	PublishedEnvelopeDigest      []byte             `db:"published_envelope_digest" json:"published_envelope_digest"`
	AuthorityGrantedAt           pgtype.Timestamptz `db:"authority_granted_at" json:"authority_granted_at"`
	PublishAttempts              int32              `db:"publish_attempts" json:"publish_attempts"`
	LastErrorCode                *string            `db:"last_error_code" json:"last_error_code"`
	RetiredAt                    pgtype.Timestamptz `db:"retired_at" json:"retired_at"`
	RetirementCode               *string            `db:"retirement_code" json:"retirement_code"`
	LastVisibilityAt             pgtype.Timestamptz `db:"last_visibility_at" json:"last_visibility_at"`
}

type EliteaRuntimeConfigurationLifecycleOutbox struct {
	EventID           pgtype.UUID        `db:"event_id" json:"event_id"`
	ResourceProjectID int32              `db:"resource_project_id" json:"resource_project_id"`
	ConfigurationUuid pgtype.UUID        `db:"configuration_uuid" json:"configuration_uuid"`
	Revision          int64              `db:"revision" json:"revision"`
	Operation         string             `db:"operation" json:"operation"`
	ActorID           int32              `db:"actor_id" json:"actor_id"`
	SanitizedSnapshot []byte             `db:"sanitized_snapshot" json:"sanitized_snapshot"`
	SnapshotDigest    []byte             `db:"snapshot_digest" json:"snapshot_digest"`
	State             string             `db:"state" json:"state"`
	AttemptCount      int32              `db:"attempt_count" json:"attempt_count"`
	AvailableAt       pgtype.Timestamptz `db:"available_at" json:"available_at"`
	LastAttemptAt     pgtype.Timestamptz `db:"last_attempt_at" json:"last_attempt_at"`
	LeaseOwner        *string            `db:"lease_owner" json:"lease_owner"`
	LeaseExpiresAt    pgtype.Timestamptz `db:"lease_expires_at" json:"lease_expires_at"`
	DeliveredAt       pgtype.Timestamptz `db:"delivered_at" json:"delivered_at"`
	DeadAt            pgtype.Timestamptz `db:"dead_at" json:"dead_at"`
	LastErrorCode     *string            `db:"last_error_code" json:"last_error_code"`
	CreatedAt         pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type EliteaRuntimeExecutionAdmissionPolicy struct {
	CapabilityID   string             `db:"capability_id" json:"capability_id"`
	MaxOutstanding int64              `db:"max_outstanding" json:"max_outstanding"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type EliteaRuntimeExecutionJob struct {
	ExecutionID             string             `db:"execution_id" json:"execution_id"`
	Generation              int64              `db:"generation" json:"generation"`
	CommandID               string             `db:"command_id" json:"command_id"`
	TenantID                string             `db:"tenant_id" json:"tenant_id"`
	ResourceProjectID       int32              `db:"resource_project_id" json:"resource_project_id"`
	ProjectionProjectID     int32              `db:"projection_project_id" json:"projection_project_id"`
	ActorID                 string             `db:"actor_id" json:"actor_id"`
	PrincipalRef            string             `db:"principal_ref" json:"principal_ref"`
	CapabilityID            string             `db:"capability_id" json:"capability_id"`
	CapabilityVersion       string             `db:"capability_version" json:"capability_version"`
	InputBundleID           string             `db:"input_bundle_id" json:"input_bundle_id"`
	RequestDigest           []byte             `db:"request_digest" json:"request_digest"`
	IdempotencyScope        string             `db:"idempotency_scope" json:"idempotency_scope"`
	IdempotencyKey          string             `db:"idempotency_key" json:"idempotency_key"`
	ConfigurationRevisionID *string            `db:"configuration_revision_id" json:"configuration_revision_id"`
	ConfigurationType       *string            `db:"configuration_type" json:"configuration_type"`
	CatalogRevision         *string            `db:"catalog_revision" json:"catalog_revision"`
	CatalogDigest           []byte             `db:"catalog_digest" json:"catalog_digest"`
	SchemaID                *string            `db:"schema_id" json:"schema_id"`
	SchemaRevision          *string            `db:"schema_revision" json:"schema_revision"`
	SchemaDigest            []byte             `db:"schema_digest" json:"schema_digest"`
	SettingsEntryID         *string            `db:"settings_entry_id" json:"settings_entry_id"`
	State                   string             `db:"state" json:"state"`
	DesiredState            string             `db:"desired_state" json:"desired_state"`
	AdmittedAt              pgtype.Timestamptz `db:"admitted_at" json:"admitted_at"`
	SettledAt               pgtype.Timestamptz `db:"settled_at" json:"settled_at"`
	TerminalErrorCode       *string            `db:"terminal_error_code" json:"terminal_error_code"`
}

type EliteaRuntimeIndexGenerationCounter struct {
	ResourceProjectID int32              `db:"resource_project_id" json:"resource_project_id"`
	ToolkitID         int32              `db:"toolkit_id" json:"toolkit_id"`
	IndexName         string             `db:"index_name" json:"index_name"`
	LastGeneration    int64              `db:"last_generation" json:"last_generation"`
	UpdatedAt         pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type EliteaRuntimeIndexIngestJob struct {
	ExecutionID                      string             `db:"execution_id" json:"execution_id"`
	Generation                       int64              `db:"generation" json:"generation"`
	IndexGeneration                  int64              `db:"index_generation" json:"index_generation"`
	CapabilityID                     string             `db:"capability_id" json:"capability_id"`
	InputBundleID                    string             `db:"input_bundle_id" json:"input_bundle_id"`
	ToolkitConfigurationEntryID      string             `db:"toolkit_configuration_entry_id" json:"toolkit_configuration_entry_id"`
	ToolParametersEntryID            string             `db:"tool_parameters_entry_id" json:"tool_parameters_entry_id"`
	LlmModelEntryID                  *string            `db:"llm_model_entry_id" json:"llm_model_entry_id"`
	LlmConfigurationEntryID          *string            `db:"llm_configuration_entry_id" json:"llm_configuration_entry_id"`
	McpTokensEntryID                 *string            `db:"mcp_tokens_entry_id" json:"mcp_tokens_entry_id"`
	ClientStreamID                   *string            `db:"client_stream_id" json:"client_stream_id"`
	ClientMessageID                  *string            `db:"client_message_id" json:"client_message_id"`
	SioEvent                         *string            `db:"sio_event" json:"sio_event"`
	IndexMetaID                      *string            `db:"index_meta_id" json:"index_meta_id"`
	IndexMetaCorrelationID           *string            `db:"index_meta_correlation_id" json:"index_meta_correlation_id"`
	IndexMetaInitializedAt           pgtype.Timestamptz `db:"index_meta_initialized_at" json:"index_meta_initialized_at"`
	IndexMetaTerminalState           *string            `db:"index_meta_terminal_state" json:"index_meta_terminal_state"`
	IndexMetaTerminalOccurredAt      pgtype.Timestamptz `db:"index_meta_terminal_occurred_at" json:"index_meta_terminal_occurred_at"`
	IndexMetaTerminalStatus          *string            `db:"index_meta_terminal_status" json:"index_meta_terminal_status"`
	IndexMetaTerminalClaimToken      *string            `db:"index_meta_terminal_claim_token" json:"index_meta_terminal_claim_token"`
	IndexMetaTerminalClaimExpiresAt  pgtype.Timestamptz `db:"index_meta_terminal_claim_expires_at" json:"index_meta_terminal_claim_expires_at"`
	IndexMetaTerminalAttemptCount    *int32             `db:"index_meta_terminal_attempt_count" json:"index_meta_terminal_attempt_count"`
	IndexMetaTerminalNextAttemptAt   pgtype.Timestamptz `db:"index_meta_terminal_next_attempt_at" json:"index_meta_terminal_next_attempt_at"`
	IndexMetaTerminalLastErrorCode   *string            `db:"index_meta_terminal_last_error_code" json:"index_meta_terminal_last_error_code"`
	IndexMetaTerminalizedAt          pgtype.Timestamptz `db:"index_meta_terminalized_at" json:"index_meta_terminalized_at"`
	IndexManualStopRequestedAt       pgtype.Timestamptz `db:"index_manual_stop_requested_at" json:"index_manual_stop_requested_at"`
	IndexManualCleanupStatus         *string            `db:"index_manual_cleanup_status" json:"index_manual_cleanup_status"`
	IndexManualCleanupClaimToken     *string            `db:"index_manual_cleanup_claim_token" json:"index_manual_cleanup_claim_token"`
	IndexManualCleanupClaimExpiresAt pgtype.Timestamptz `db:"index_manual_cleanup_claim_expires_at" json:"index_manual_cleanup_claim_expires_at"`
	IndexManualCleanupAttemptCount   *int32             `db:"index_manual_cleanup_attempt_count" json:"index_manual_cleanup_attempt_count"`
	IndexManualCleanupNextAttemptAt  pgtype.Timestamptz `db:"index_manual_cleanup_next_attempt_at" json:"index_manual_cleanup_next_attempt_at"`
	IndexManualCleanupLastErrorCode  *string            `db:"index_manual_cleanup_last_error_code" json:"index_manual_cleanup_last_error_code"`
	IndexManualCleanupResolvedAt     pgtype.Timestamptz `db:"index_manual_cleanup_resolved_at" json:"index_manual_cleanup_resolved_at"`
	ToolkitID                        int32              `db:"toolkit_id" json:"toolkit_id"`
	IndexName                        string             `db:"index_name" json:"index_name"`
	Initiator                        string             `db:"initiator" json:"initiator"`
}

type EliteaRuntimeIndexIngestResult struct {
	LogicalOutputID          string             `db:"logical_output_id" json:"logical_output_id"`
	ExecutionID              string             `db:"execution_id" json:"execution_id"`
	Generation               int64              `db:"generation" json:"generation"`
	InputBundleID            string             `db:"input_bundle_id" json:"input_bundle_id"`
	InputBundleDigest        []byte             `db:"input_bundle_digest" json:"input_bundle_digest"`
	ArtifactID               *string            `db:"artifact_id" json:"artifact_id"`
	ArtifactImmutableVersion *string            `db:"artifact_immutable_version" json:"artifact_immutable_version"`
	ArtifactStorageRecordID  *string            `db:"artifact_storage_record_id" json:"artifact_storage_record_id"`
	CompletionStatus         *string            `db:"completion_status" json:"completion_status"`
	CompletionMessage        *string            `db:"completion_message" json:"completion_message"`
	ProjectedAt              pgtype.Timestamptz `db:"projected_at" json:"projected_at"`
}

type EliteaRuntimeIndexResultArtifact struct {
	ArtifactID        string             `db:"artifact_id" json:"artifact_id"`
	ImmutableVersion  string             `db:"immutable_version" json:"immutable_version"`
	ExecutionID       string             `db:"execution_id" json:"execution_id"`
	Generation        int64              `db:"generation" json:"generation"`
	ResourceProjectID int32              `db:"resource_project_id" json:"resource_project_id"`
	MediaType         string             `db:"media_type" json:"media_type"`
	ByteLength        int64              `db:"byte_length" json:"byte_length"`
	Digest            []byte             `db:"digest" json:"digest"`
	Classification    string             `db:"classification" json:"classification"`
	StorageRecordID   string             `db:"storage_record_id" json:"storage_record_id"`
	BytesVerifiedAt   pgtype.Timestamptz `db:"bytes_verified_at" json:"bytes_verified_at"`
	MetadataCreatedAt pgtype.Timestamptz `db:"metadata_created_at" json:"metadata_created_at"`
}

type EliteaRuntimeInputBundle struct {
	InputBundleID     string             `db:"input_bundle_id" json:"input_bundle_id"`
	ImmutableVersion  string             `db:"immutable_version" json:"immutable_version"`
	MediaType         string             `db:"media_type" json:"media_type"`
	ResourceProjectID int32              `db:"resource_project_id" json:"resource_project_id"`
	ManifestDigest    []byte             `db:"manifest_digest" json:"manifest_digest"`
	ManifestSize      int64              `db:"manifest_size" json:"manifest_size"`
	ManifestBytes     []byte             `db:"manifest_bytes" json:"manifest_bytes"`
	CreatedBy         string             `db:"created_by" json:"created_by"`
	CreatedAt         pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type EliteaRuntimeInputBundleEntry struct {
	InputBundleID         string `db:"input_bundle_id" json:"input_bundle_id"`
	EntryID               string `db:"entry_id" json:"entry_id"`
	EntryVersion          string `db:"entry_version" json:"entry_version"`
	SemanticRole          string `db:"semantic_role" json:"semantic_role"`
	MediaType             string `db:"media_type" json:"media_type"`
	ContentDigest         []byte `db:"content_digest" json:"content_digest"`
	ContentSize           int64  `db:"content_size" json:"content_size"`
	ContentReference      string `db:"content_reference" json:"content_reference"`
	Classification        string `db:"classification" json:"classification"`
	RequiredGrantAudience string `db:"required_grant_audience" json:"required_grant_audience"`
	ContentBytes          []byte `db:"content_bytes" json:"content_bytes"`
}

type EliteaTool struct {
	ID            int32            `db:"id" json:"id"`
	CreatedAt     pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamp `db:"updated_at" json:"updated_at"`
	Type          string           `db:"type" json:"type"`
	Name          *string          `db:"name" json:"name"`
	Description   *string          `db:"description" json:"description"`
	Settings      []byte           `db:"settings" json:"settings"`
	AuthorID      int32            `db:"author_id" json:"author_id"`
	SharedOwnerID *int32           `db:"shared_owner_id" json:"shared_owner_id"`
	SharedID      *int32           `db:"shared_id" json:"shared_id"`
	Meta          []byte           `db:"meta" json:"meta"`
}
