// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: runtime_public_authorization.sql

package sqlcgen

import (
	"context"
)

const authorizeRuntimeValidationProject = `-- name: AuthorizeRuntimeValidationProject :one
SELECT EXISTS (
    SELECT 1
    FROM centry.project AS project
    WHERE project.id = $1::integer
      AND project.suspended = FALSE
      AND (
          project.owner_id = $2::integer
          OR EXISTS (
              SELECT 1
              FROM public.auth_core__project_user_role AS assignment
              WHERE assignment.project_id = project.id
                AND assignment.user_id = $2::integer
          )
      )
) AS authorized
`

type AuthorizeRuntimeValidationProjectParams struct {
	ProjectID int32 `db:"project_id" json:"project_id"`
	UserID    int32 `db:"user_id" json:"user_id"`
}

func (q *Queries) AuthorizeRuntimeValidationProject(ctx context.Context, arg AuthorizeRuntimeValidationProjectParams) (bool, error) {
	row := q.db.QueryRow(ctx, authorizeRuntimeValidationProject, arg.ProjectID, arg.UserID)
	var authorized bool
	err := row.Scan(&authorized)
	return authorized, err
}

const resolveRuntimeExecutionEventCapability = `-- name: ResolveRuntimeExecutionEventCapability :one
SELECT COALESCE(
    CASE WHEN COUNT(*) = 1 THEN MIN(job.capability_id) END,
    ''::text
)::text AS capability_id
FROM elitea_runtime.execution_jobs AS job
JOIN centry.project AS project
  ON project.id = job.projection_project_id
WHERE job.execution_id = $1::text
  AND job.tenant_id = ($2::integer)::text
  AND job.resource_project_id = $2::integer
  AND job.projection_project_id = $2::integer
  AND job.capability_id IN (
      'configuration.validate.v1',
      'index.ingest.v1',
      'agent.execute.application.v1'
  )
  AND project.suspended = FALSE
`

type ResolveRuntimeExecutionEventCapabilityParams struct {
	ExecutionID string `db:"execution_id" json:"execution_id"`
	ProjectID   int32  `db:"project_id" json:"project_id"`
}

func (q *Queries) ResolveRuntimeExecutionEventCapability(ctx context.Context, arg ResolveRuntimeExecutionEventCapabilityParams) (string, error) {
	row := q.db.QueryRow(ctx, resolveRuntimeExecutionEventCapability, arg.ExecutionID, arg.ProjectID)
	var capability_id string
	err := row.Scan(&capability_id)
	return capability_id, err
}
