// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: runtime_index_cancel.sql

package sqlcgen

import (
	"context"
)

const requestCurrentIndexIngestCancellation = `-- name: RequestCurrentIndexIngestCancellation :one
WITH transitioned AS (
    UPDATE elitea_runtime.execution_jobs AS job
    SET desired_state = 'CANCELLED'
    FROM elitea_runtime.index_ingest_jobs AS ingest
    WHERE job.execution_id = $1::text
      -- The current distributed-monolith tenant canonical identity is the
      -- project ID. Bind cancellation to the same tenant as its authenticated
      -- project route rather than treating a project ID as tenant authority.
      AND job.tenant_id = ($2::integer)::text
      AND job.resource_project_id = $2::integer
      AND job.projection_project_id = $2::integer
      AND job.capability_id = 'index.ingest.v1'
      AND job.desired_state = 'RUNNING'
      AND job.state IN ('PENDING', 'DISPATCHED', 'CLAIMED', 'RUNNING', 'SETTLING')
      AND ingest.execution_id = job.execution_id
      AND ingest.generation = job.generation
      AND ingest.capability_id = job.capability_id
      AND ingest.toolkit_id = $3::integer
      AND ingest.index_name = $4::text
    RETURNING job.execution_id
)
SELECT EXISTS (SELECT 1 FROM transitioned) AS transitioned
`

type RequestCurrentIndexIngestCancellationParams struct {
	ExecutionID       string `db:"execution_id" json:"execution_id"`
	ResourceProjectID int32  `db:"resource_project_id" json:"resource_project_id"`
	ToolkitID         int32  `db:"toolkit_id" json:"toolkit_id"`
	IndexName         string `db:"index_name" json:"index_name"`
}

func (q *Queries) RequestCurrentIndexIngestCancellation(ctx context.Context, arg RequestCurrentIndexIngestCancellationParams) (bool, error) {
	row := q.db.QueryRow(ctx, requestCurrentIndexIngestCancellation,
		arg.ExecutionID,
		arg.ResourceProjectID,
		arg.ToolkitID,
		arg.IndexName,
	)
	var transitioned bool
	err := row.Scan(&transitioned)
	return transitioned, err
}
