// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: runtime_index_ingest.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const allocateIndexGeneration = `-- name: AllocateIndexGeneration :one
INSERT INTO elitea_runtime.index_generation_counters (
    resource_project_id, toolkit_id, index_name, last_generation, updated_at
) VALUES (
    $1::integer,
    $2::integer,
    $3::text,
    1,
    clock_timestamp()
)
ON CONFLICT (resource_project_id, toolkit_id, index_name) DO UPDATE
SET last_generation =
        elitea_runtime.index_generation_counters.last_generation + 1,
    updated_at = clock_timestamp()
WHERE elitea_runtime.index_generation_counters.last_generation
      < 9223372036854775807
RETURNING last_generation
`

type AllocateIndexGenerationParams struct {
	ResourceProjectID int32  `db:"resource_project_id" json:"resource_project_id"`
	ToolkitID         int32  `db:"toolkit_id" json:"toolkit_id"`
	IndexName         string `db:"index_name" json:"index_name"`
}

func (q *Queries) AllocateIndexGeneration(ctx context.Context, arg AllocateIndexGenerationParams) (int64, error) {
	row := q.db.QueryRow(ctx, allocateIndexGeneration, arg.ResourceProjectID, arg.ToolkitID, arg.IndexName)
	var last_generation int64
	err := row.Scan(&last_generation)
	return last_generation, err
}

const countActiveRuntimeExecutionsUpTo = `-- name: CountActiveRuntimeExecutionsUpTo :one
SELECT count(*)
FROM (
    SELECT 1
    FROM elitea_runtime.execution_jobs
    WHERE capability_id = $1::text
      AND state IN ('PENDING', 'DISPATCHED', 'CLAIMED', 'RUNNING', 'SETTLING')
    LIMIT $2::bigint
) AS bounded_active
`

type CountActiveRuntimeExecutionsUpToParams struct {
	CapabilityID   string `db:"capability_id" json:"capability_id"`
	MaxOutstanding int64  `db:"max_outstanding" json:"max_outstanding"`
}

func (q *Queries) CountActiveRuntimeExecutionsUpTo(ctx context.Context, arg CountActiveRuntimeExecutionsUpToParams) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveRuntimeExecutionsUpTo, arg.CapabilityID, arg.MaxOutstanding)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const ensureRuntimeAdmissionPolicy = `-- name: EnsureRuntimeAdmissionPolicy :exec
INSERT INTO elitea_runtime.execution_admission_policies (
    capability_id, max_outstanding
) VALUES (
    $1::text,
    $2::bigint
)
ON CONFLICT (capability_id) DO NOTHING
`

type EnsureRuntimeAdmissionPolicyParams struct {
	CapabilityID   string `db:"capability_id" json:"capability_id"`
	MaxOutstanding int64  `db:"max_outstanding" json:"max_outstanding"`
}

func (q *Queries) EnsureRuntimeAdmissionPolicy(ctx context.Context, arg EnsureRuntimeAdmissionPolicyParams) error {
	_, err := q.db.Exec(ctx, ensureRuntimeAdmissionPolicy, arg.CapabilityID, arg.MaxOutstanding)
	return err
}

const getDurableIndexResultArtifact = `-- name: GetDurableIndexResultArtifact :one
SELECT a.artifact_id,
       a.immutable_version,
       a.media_type,
       a.byte_length,
       a.digest,
       a.classification,
       a.storage_record_id,
       a.bytes_verified_at
FROM elitea_runtime.index_result_artifacts AS a
JOIN elitea_runtime.execution_jobs AS j
  ON j.execution_id = a.execution_id
 AND j.generation = a.generation
WHERE a.artifact_id = $1::text
  AND a.immutable_version = $2::text
  AND a.execution_id = $3::text
  AND a.generation = $4::bigint
  AND a.resource_project_id = $5::integer
  AND j.tenant_id = $6::text
  AND j.resource_project_id = $5::integer
  AND j.projection_project_id = $7::integer
  AND j.command_id = $8::text
  AND j.capability_id = 'index.ingest.v1'
`

type GetDurableIndexResultArtifactParams struct {
	ArtifactID          string `db:"artifact_id" json:"artifact_id"`
	ImmutableVersion    string `db:"immutable_version" json:"immutable_version"`
	ExecutionID         string `db:"execution_id" json:"execution_id"`
	Generation          int64  `db:"generation" json:"generation"`
	ResourceProjectID   int32  `db:"resource_project_id" json:"resource_project_id"`
	TenantID            string `db:"tenant_id" json:"tenant_id"`
	ProjectionProjectID int32  `db:"projection_project_id" json:"projection_project_id"`
	CommandID           string `db:"command_id" json:"command_id"`
}

type GetDurableIndexResultArtifactRow struct {
	ArtifactID       string             `db:"artifact_id" json:"artifact_id"`
	ImmutableVersion string             `db:"immutable_version" json:"immutable_version"`
	MediaType        string             `db:"media_type" json:"media_type"`
	ByteLength       int64              `db:"byte_length" json:"byte_length"`
	Digest           []byte             `db:"digest" json:"digest"`
	Classification   string             `db:"classification" json:"classification"`
	StorageRecordID  string             `db:"storage_record_id" json:"storage_record_id"`
	BytesVerifiedAt  pgtype.Timestamptz `db:"bytes_verified_at" json:"bytes_verified_at"`
}

func (q *Queries) GetDurableIndexResultArtifact(ctx context.Context, arg GetDurableIndexResultArtifactParams) (GetDurableIndexResultArtifactRow, error) {
	row := q.db.QueryRow(ctx, getDurableIndexResultArtifact,
		arg.ArtifactID,
		arg.ImmutableVersion,
		arg.ExecutionID,
		arg.Generation,
		arg.ResourceProjectID,
		arg.TenantID,
		arg.ProjectionProjectID,
		arg.CommandID,
	)
	var i GetDurableIndexResultArtifactRow
	err := row.Scan(
		&i.ArtifactID,
		&i.ImmutableVersion,
		&i.MediaType,
		&i.ByteLength,
		&i.Digest,
		&i.Classification,
		&i.StorageRecordID,
		&i.BytesVerifiedAt,
	)
	return i, err
}

const getExpectedIndexIngestHeader = `-- name: GetExpectedIndexIngestHeader :one
SELECT j.tenant_id,
       j.resource_project_id,
       j.projection_project_id,
       j.capability_id,
       j.command_id,
       j.execution_id,
       j.generation,
       b.input_bundle_id,
       b.manifest_digest AS input_bundle_digest,
       i.toolkit_configuration_entry_id,
       i.tool_parameters_entry_id,
       i.llm_model_entry_id,
       i.llm_configuration_entry_id,
       i.mcp_tokens_entry_id,
       o.limits_revision
FROM elitea_runtime.execution_jobs AS j
JOIN elitea_runtime.index_ingest_jobs AS i
  ON i.execution_id = j.execution_id
 AND i.generation = j.generation
JOIN elitea_runtime.input_bundles AS b
  ON b.input_bundle_id = j.input_bundle_id
JOIN elitea_runtime.command_outbox AS o
  ON o.execution_id = j.execution_id
 AND o.generation = j.generation
WHERE j.execution_id = $1::text
  AND j.generation = $2::bigint
  AND j.capability_id = 'index.ingest.v1'
`

type GetExpectedIndexIngestHeaderParams struct {
	ExecutionID string `db:"execution_id" json:"execution_id"`
	Generation  int64  `db:"generation" json:"generation"`
}

type GetExpectedIndexIngestHeaderRow struct {
	TenantID                    string  `db:"tenant_id" json:"tenant_id"`
	ResourceProjectID           int32   `db:"resource_project_id" json:"resource_project_id"`
	ProjectionProjectID         int32   `db:"projection_project_id" json:"projection_project_id"`
	CapabilityID                string  `db:"capability_id" json:"capability_id"`
	CommandID                   string  `db:"command_id" json:"command_id"`
	ExecutionID                 string  `db:"execution_id" json:"execution_id"`
	Generation                  int64   `db:"generation" json:"generation"`
	InputBundleID               string  `db:"input_bundle_id" json:"input_bundle_id"`
	InputBundleDigest           []byte  `db:"input_bundle_digest" json:"input_bundle_digest"`
	ToolkitConfigurationEntryID string  `db:"toolkit_configuration_entry_id" json:"toolkit_configuration_entry_id"`
	ToolParametersEntryID       string  `db:"tool_parameters_entry_id" json:"tool_parameters_entry_id"`
	LlmModelEntryID             *string `db:"llm_model_entry_id" json:"llm_model_entry_id"`
	LlmConfigurationEntryID     *string `db:"llm_configuration_entry_id" json:"llm_configuration_entry_id"`
	McpTokensEntryID            *string `db:"mcp_tokens_entry_id" json:"mcp_tokens_entry_id"`
	LimitsRevision              string  `db:"limits_revision" json:"limits_revision"`
}

func (q *Queries) GetExpectedIndexIngestHeader(ctx context.Context, arg GetExpectedIndexIngestHeaderParams) (GetExpectedIndexIngestHeaderRow, error) {
	row := q.db.QueryRow(ctx, getExpectedIndexIngestHeader, arg.ExecutionID, arg.Generation)
	var i GetExpectedIndexIngestHeaderRow
	err := row.Scan(
		&i.TenantID,
		&i.ResourceProjectID,
		&i.ProjectionProjectID,
		&i.CapabilityID,
		&i.CommandID,
		&i.ExecutionID,
		&i.Generation,
		&i.InputBundleID,
		&i.InputBundleDigest,
		&i.ToolkitConfigurationEntryID,
		&i.ToolParametersEntryID,
		&i.LlmModelEntryID,
		&i.LlmConfigurationEntryID,
		&i.McpTokensEntryID,
		&i.LimitsRevision,
	)
	return i, err
}

const getRuntimeAdmissionByIdempotency = `-- name: GetRuntimeAdmissionByIdempotency :one
SELECT j.execution_id,
       j.command_id,
       j.generation,
       i.index_generation,
       j.request_digest,
       j.admitted_at,
       o.deadline,
       i.index_meta_id,
       i.index_meta_correlation_id,
       i.index_meta_initialized_at
FROM elitea_runtime.execution_jobs AS j
JOIN elitea_runtime.command_outbox AS o
  ON o.execution_id = j.execution_id AND o.generation = j.generation
JOIN elitea_runtime.index_ingest_jobs AS i
  ON i.execution_id = j.execution_id AND i.generation = j.generation
WHERE j.idempotency_scope = $1::text
  AND j.idempotency_key = $2::text
  AND j.capability_id = 'index.ingest.v1'
`

type GetRuntimeAdmissionByIdempotencyParams struct {
	IdempotencyScope string `db:"idempotency_scope" json:"idempotency_scope"`
	IdempotencyKey   string `db:"idempotency_key" json:"idempotency_key"`
}

type GetRuntimeAdmissionByIdempotencyRow struct {
	ExecutionID            string             `db:"execution_id" json:"execution_id"`
	CommandID              string             `db:"command_id" json:"command_id"`
	Generation             int64              `db:"generation" json:"generation"`
	IndexGeneration        int64              `db:"index_generation" json:"index_generation"`
	RequestDigest          []byte             `db:"request_digest" json:"request_digest"`
	AdmittedAt             pgtype.Timestamptz `db:"admitted_at" json:"admitted_at"`
	Deadline               pgtype.Timestamptz `db:"deadline" json:"deadline"`
	IndexMetaID            *string            `db:"index_meta_id" json:"index_meta_id"`
	IndexMetaCorrelationID *string            `db:"index_meta_correlation_id" json:"index_meta_correlation_id"`
	IndexMetaInitializedAt pgtype.Timestamptz `db:"index_meta_initialized_at" json:"index_meta_initialized_at"`
}

func (q *Queries) GetRuntimeAdmissionByIdempotency(ctx context.Context, arg GetRuntimeAdmissionByIdempotencyParams) (GetRuntimeAdmissionByIdempotencyRow, error) {
	row := q.db.QueryRow(ctx, getRuntimeAdmissionByIdempotency, arg.IdempotencyScope, arg.IdempotencyKey)
	var i GetRuntimeAdmissionByIdempotencyRow
	err := row.Scan(
		&i.ExecutionID,
		&i.CommandID,
		&i.Generation,
		&i.IndexGeneration,
		&i.RequestDigest,
		&i.AdmittedAt,
		&i.Deadline,
		&i.IndexMetaID,
		&i.IndexMetaCorrelationID,
		&i.IndexMetaInitializedAt,
	)
	return i, err
}

const hasActiveIndexIngestTarget = `-- name: HasActiveIndexIngestTarget :one
SELECT EXISTS (
    SELECT 1
    FROM elitea_runtime.execution_jobs AS j
    JOIN elitea_runtime.index_ingest_jobs AS i
      ON i.execution_id = j.execution_id
     AND i.generation = j.generation
    WHERE j.capability_id = 'index.ingest.v1'
      AND j.resource_project_id = $1::integer
      AND i.toolkit_id = $2::integer
      AND i.index_name = $3::text
      AND j.state IN ('PENDING', 'DISPATCHED', 'CLAIMED', 'RUNNING', 'SETTLING')
    LIMIT 1
)
`

type HasActiveIndexIngestTargetParams struct {
	ResourceProjectID int32  `db:"resource_project_id" json:"resource_project_id"`
	ToolkitID         int32  `db:"toolkit_id" json:"toolkit_id"`
	IndexName         string `db:"index_name" json:"index_name"`
}

func (q *Queries) HasActiveIndexIngestTarget(ctx context.Context, arg HasActiveIndexIngestTargetParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasActiveIndexIngestTarget, arg.ResourceProjectID, arg.ToolkitID, arg.IndexName)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const insertIndexIngestExecutionJob = `-- name: InsertIndexIngestExecutionJob :one
INSERT INTO elitea_runtime.execution_jobs (
    execution_id, generation, command_id, tenant_id, resource_project_id,
    projection_project_id, actor_id, principal_ref, capability_id,
    capability_version, input_bundle_id, request_digest,
    idempotency_scope, idempotency_key, state, desired_state, admitted_at
) VALUES (
    $1::text,
    $2::bigint,
    $3::text,
    $4::text,
    $5::integer,
    $6::integer,
    $7::text,
    $8::text,
    'index.ingest.v1',
    $9::text,
    $10::text,
    $11::bytea,
    $12::text,
    $13::text,
    $14::text,
    'RUNNING',
    $15::timestamptz
)
ON CONFLICT (idempotency_scope, idempotency_key) DO NOTHING
RETURNING execution_id
`

type InsertIndexIngestExecutionJobParams struct {
	ExecutionID         string             `db:"execution_id" json:"execution_id"`
	Generation          int64              `db:"generation" json:"generation"`
	CommandID           string             `db:"command_id" json:"command_id"`
	TenantID            string             `db:"tenant_id" json:"tenant_id"`
	ResourceProjectID   int32              `db:"resource_project_id" json:"resource_project_id"`
	ProjectionProjectID int32              `db:"projection_project_id" json:"projection_project_id"`
	ActorID             string             `db:"actor_id" json:"actor_id"`
	PrincipalRef        string             `db:"principal_ref" json:"principal_ref"`
	CapabilityVersion   string             `db:"capability_version" json:"capability_version"`
	InputBundleID       string             `db:"input_bundle_id" json:"input_bundle_id"`
	RequestDigest       []byte             `db:"request_digest" json:"request_digest"`
	IdempotencyScope    string             `db:"idempotency_scope" json:"idempotency_scope"`
	IdempotencyKey      string             `db:"idempotency_key" json:"idempotency_key"`
	State               string             `db:"state" json:"state"`
	AdmittedAt          pgtype.Timestamptz `db:"admitted_at" json:"admitted_at"`
}

func (q *Queries) InsertIndexIngestExecutionJob(ctx context.Context, arg InsertIndexIngestExecutionJobParams) (string, error) {
	row := q.db.QueryRow(ctx, insertIndexIngestExecutionJob,
		arg.ExecutionID,
		arg.Generation,
		arg.CommandID,
		arg.TenantID,
		arg.ResourceProjectID,
		arg.ProjectionProjectID,
		arg.ActorID,
		arg.PrincipalRef,
		arg.CapabilityVersion,
		arg.InputBundleID,
		arg.RequestDigest,
		arg.IdempotencyScope,
		arg.IdempotencyKey,
		arg.State,
		arg.AdmittedAt,
	)
	var execution_id string
	err := row.Scan(&execution_id)
	return execution_id, err
}

const insertIndexIngestJob = `-- name: InsertIndexIngestJob :exec
INSERT INTO elitea_runtime.index_ingest_jobs (
    execution_id, generation, index_generation, capability_id, input_bundle_id,
    toolkit_configuration_entry_id, tool_parameters_entry_id,
    llm_model_entry_id, llm_configuration_entry_id, mcp_tokens_entry_id,
    client_stream_id, client_message_id, sio_event,
    index_meta_id, index_meta_correlation_id,
    toolkit_id, index_name, initiator
) VALUES (
    $1::text,
    $2::bigint,
    $3::bigint,
    'index.ingest.v1',
    $4::text,
    $5::text,
    $6::text,
    $7::text,
    $8::text,
    $9::text,
    $10::text,
    $11::text,
    $12::text,
    $13::text,
    $14::text,
    $15::integer,
    $16::text,
    $17::text
)
`

type InsertIndexIngestJobParams struct {
	ExecutionID                 string  `db:"execution_id" json:"execution_id"`
	Generation                  int64   `db:"generation" json:"generation"`
	IndexGeneration             int64   `db:"index_generation" json:"index_generation"`
	InputBundleID               string  `db:"input_bundle_id" json:"input_bundle_id"`
	ToolkitConfigurationEntryID string  `db:"toolkit_configuration_entry_id" json:"toolkit_configuration_entry_id"`
	ToolParametersEntryID       string  `db:"tool_parameters_entry_id" json:"tool_parameters_entry_id"`
	LlmModelEntryID             *string `db:"llm_model_entry_id" json:"llm_model_entry_id"`
	LlmConfigurationEntryID     *string `db:"llm_configuration_entry_id" json:"llm_configuration_entry_id"`
	McpTokensEntryID            *string `db:"mcp_tokens_entry_id" json:"mcp_tokens_entry_id"`
	ClientStreamID              *string `db:"client_stream_id" json:"client_stream_id"`
	ClientMessageID             *string `db:"client_message_id" json:"client_message_id"`
	SioEvent                    *string `db:"sio_event" json:"sio_event"`
	IndexMetaID                 string  `db:"index_meta_id" json:"index_meta_id"`
	IndexMetaCorrelationID      string  `db:"index_meta_correlation_id" json:"index_meta_correlation_id"`
	ToolkitID                   int32   `db:"toolkit_id" json:"toolkit_id"`
	IndexName                   string  `db:"index_name" json:"index_name"`
	Initiator                   string  `db:"initiator" json:"initiator"`
}

func (q *Queries) InsertIndexIngestJob(ctx context.Context, arg InsertIndexIngestJobParams) error {
	_, err := q.db.Exec(ctx, insertIndexIngestJob,
		arg.ExecutionID,
		arg.Generation,
		arg.IndexGeneration,
		arg.InputBundleID,
		arg.ToolkitConfigurationEntryID,
		arg.ToolParametersEntryID,
		arg.LlmModelEntryID,
		arg.LlmConfigurationEntryID,
		arg.McpTokensEntryID,
		arg.ClientStreamID,
		arg.ClientMessageID,
		arg.SioEvent,
		arg.IndexMetaID,
		arg.IndexMetaCorrelationID,
		arg.ToolkitID,
		arg.IndexName,
		arg.Initiator,
	)
	return err
}

const insertRuntimeCommandOutbox = `-- name: InsertRuntimeCommandOutbox :exec
INSERT INTO elitea_runtime.command_outbox (
    outbox_id, execution_id, generation, stream_name, dispatch_ordinal,
    resource_class, isolation_class, priority, deadline, limits_revision,
    traceparent, tracestate, created_at, publish_attempts
) VALUES (
    $1::text,
    $2::text,
    $3::bigint,
    $4::text,
    1,
    $5::text,
    $6::text,
    $7::integer,
    $8::timestamptz,
    $9::text,
    '',
    '',
    $10::timestamptz,
    0
)
`

type InsertRuntimeCommandOutboxParams struct {
	OutboxID       string             `db:"outbox_id" json:"outbox_id"`
	ExecutionID    string             `db:"execution_id" json:"execution_id"`
	Generation     int64              `db:"generation" json:"generation"`
	StreamName     string             `db:"stream_name" json:"stream_name"`
	ResourceClass  string             `db:"resource_class" json:"resource_class"`
	IsolationClass string             `db:"isolation_class" json:"isolation_class"`
	Priority       int32              `db:"priority" json:"priority"`
	Deadline       pgtype.Timestamptz `db:"deadline" json:"deadline"`
	LimitsRevision string             `db:"limits_revision" json:"limits_revision"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

func (q *Queries) InsertRuntimeCommandOutbox(ctx context.Context, arg InsertRuntimeCommandOutboxParams) error {
	_, err := q.db.Exec(ctx, insertRuntimeCommandOutbox,
		arg.OutboxID,
		arg.ExecutionID,
		arg.Generation,
		arg.StreamName,
		arg.ResourceClass,
		arg.IsolationClass,
		arg.Priority,
		arg.Deadline,
		arg.LimitsRevision,
		arg.CreatedAt,
	)
	return err
}

const insertRuntimeInputBundle = `-- name: InsertRuntimeInputBundle :exec
INSERT INTO elitea_runtime.input_bundles (
    input_bundle_id, immutable_version, media_type, resource_project_id,
    manifest_digest, manifest_size, manifest_bytes, created_by, created_at
) VALUES (
    $1::text,
    $2::text,
    $3::text,
    $4::integer,
    $5::bytea,
    $6::bigint,
    $7::bytea,
    $8::text,
    $9::timestamptz
)
`

type InsertRuntimeInputBundleParams struct {
	InputBundleID     string             `db:"input_bundle_id" json:"input_bundle_id"`
	ImmutableVersion  string             `db:"immutable_version" json:"immutable_version"`
	MediaType         string             `db:"media_type" json:"media_type"`
	ResourceProjectID int32              `db:"resource_project_id" json:"resource_project_id"`
	ManifestDigest    []byte             `db:"manifest_digest" json:"manifest_digest"`
	ManifestSize      int64              `db:"manifest_size" json:"manifest_size"`
	ManifestBytes     []byte             `db:"manifest_bytes" json:"manifest_bytes"`
	CreatedBy         string             `db:"created_by" json:"created_by"`
	CreatedAt         pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

func (q *Queries) InsertRuntimeInputBundle(ctx context.Context, arg InsertRuntimeInputBundleParams) error {
	_, err := q.db.Exec(ctx, insertRuntimeInputBundle,
		arg.InputBundleID,
		arg.ImmutableVersion,
		arg.MediaType,
		arg.ResourceProjectID,
		arg.ManifestDigest,
		arg.ManifestSize,
		arg.ManifestBytes,
		arg.CreatedBy,
		arg.CreatedAt,
	)
	return err
}

const insertRuntimeInputBundleEntry = `-- name: InsertRuntimeInputBundleEntry :exec
INSERT INTO elitea_runtime.input_bundle_entries (
    input_bundle_id, entry_id, entry_version, semantic_role, media_type,
    content_digest, content_size, content_reference, classification,
    required_grant_audience, content_bytes
) VALUES (
    $1::text,
    $2::text,
    $3::text,
    $4::text,
    $5::text,
    $6::bytea,
    $7::bigint,
    $8::text,
    $9::text,
    $10::text,
    $11::bytea
)
`

type InsertRuntimeInputBundleEntryParams struct {
	InputBundleID         string `db:"input_bundle_id" json:"input_bundle_id"`
	EntryID               string `db:"entry_id" json:"entry_id"`
	EntryVersion          string `db:"entry_version" json:"entry_version"`
	SemanticRole          string `db:"semantic_role" json:"semantic_role"`
	MediaType             string `db:"media_type" json:"media_type"`
	ContentDigest         []byte `db:"content_digest" json:"content_digest"`
	ContentSize           int64  `db:"content_size" json:"content_size"`
	ContentReference      string `db:"content_reference" json:"content_reference"`
	Classification        string `db:"classification" json:"classification"`
	RequiredGrantAudience string `db:"required_grant_audience" json:"required_grant_audience"`
	ContentBytes          []byte `db:"content_bytes" json:"content_bytes"`
}

func (q *Queries) InsertRuntimeInputBundleEntry(ctx context.Context, arg InsertRuntimeInputBundleEntryParams) error {
	_, err := q.db.Exec(ctx, insertRuntimeInputBundleEntry,
		arg.InputBundleID,
		arg.EntryID,
		arg.EntryVersion,
		arg.SemanticRole,
		arg.MediaType,
		arg.ContentDigest,
		arg.ContentSize,
		arg.ContentReference,
		arg.Classification,
		arg.RequiredGrantAudience,
		arg.ContentBytes,
	)
	return err
}

const listExpectedIndexIngestEntries = `-- name: ListExpectedIndexIngestEntries :many
SELECT e.entry_id,
       e.entry_version,
       e.semantic_role,
       e.content_digest,
       e.classification
FROM elitea_runtime.execution_jobs AS j
JOIN elitea_runtime.index_ingest_jobs AS i
  ON i.execution_id = j.execution_id
 AND i.generation = j.generation
JOIN elitea_runtime.input_bundle_entries AS e
  ON e.input_bundle_id = j.input_bundle_id
WHERE j.execution_id = $1::text
  AND j.generation = $2::bigint
  AND j.capability_id = 'index.ingest.v1'
ORDER BY e.entry_id
`

type ListExpectedIndexIngestEntriesParams struct {
	ExecutionID string `db:"execution_id" json:"execution_id"`
	Generation  int64  `db:"generation" json:"generation"`
}

type ListExpectedIndexIngestEntriesRow struct {
	EntryID        string `db:"entry_id" json:"entry_id"`
	EntryVersion   string `db:"entry_version" json:"entry_version"`
	SemanticRole   string `db:"semantic_role" json:"semantic_role"`
	ContentDigest  []byte `db:"content_digest" json:"content_digest"`
	Classification string `db:"classification" json:"classification"`
}

func (q *Queries) ListExpectedIndexIngestEntries(ctx context.Context, arg ListExpectedIndexIngestEntriesParams) ([]ListExpectedIndexIngestEntriesRow, error) {
	rows, err := q.db.Query(ctx, listExpectedIndexIngestEntries, arg.ExecutionID, arg.Generation)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListExpectedIndexIngestEntriesRow{}
	for rows.Next() {
		var i ListExpectedIndexIngestEntriesRow
		if err := rows.Scan(
			&i.EntryID,
			&i.EntryVersion,
			&i.SemanticRole,
			&i.ContentDigest,
			&i.Classification,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const loadRuntimeAdmissionTiming = `-- name: LoadRuntimeAdmissionTiming :one
WITH authority AS MATERIALIZED (
    SELECT date_trunc('milliseconds', clock_timestamp()) AS admitted_at
)
SELECT admitted_at::timestamptz AS admitted_at,
       (admitted_at + ($1::bigint * interval '1 millisecond'))::timestamptz AS deadline
FROM authority
`

type LoadRuntimeAdmissionTimingRow struct {
	AdmittedAt pgtype.Timestamptz `db:"admitted_at" json:"admitted_at"`
	Deadline   pgtype.Timestamptz `db:"deadline" json:"deadline"`
}

func (q *Queries) LoadRuntimeAdmissionTiming(ctx context.Context, deadlineTtlMillis int64) (LoadRuntimeAdmissionTimingRow, error) {
	row := q.db.QueryRow(ctx, loadRuntimeAdmissionTiming, deadlineTtlMillis)
	var i LoadRuntimeAdmissionTimingRow
	err := row.Scan(&i.AdmittedAt, &i.Deadline)
	return i, err
}

const lockRuntimeAdmissionPolicy = `-- name: LockRuntimeAdmissionPolicy :one
SELECT max_outstanding
FROM elitea_runtime.execution_admission_policies
WHERE capability_id = $1::text
FOR UPDATE
`

func (q *Queries) LockRuntimeAdmissionPolicy(ctx context.Context, capabilityID string) (int64, error) {
	row := q.db.QueryRow(ctx, lockRuntimeAdmissionPolicy, capabilityID)
	var max_outstanding int64
	err := row.Scan(&max_outstanding)
	return max_outstanding, err
}

const markIndexMetaInitialized = `-- name: MarkIndexMetaInitialized :one
UPDATE elitea_runtime.index_ingest_jobs AS i
SET index_meta_initialized_at = COALESCE(
    i.index_meta_initialized_at,
    date_trunc('milliseconds', clock_timestamp())
)
FROM elitea_runtime.execution_jobs AS j
WHERE i.execution_id = $1::text
  AND i.generation = $2::bigint
  AND i.index_generation = $3::bigint
  AND i.capability_id = 'index.ingest.v1'
  AND i.index_meta_id = $4::text
  AND i.index_meta_correlation_id = $5::text
  AND j.execution_id = i.execution_id
  AND j.generation = i.generation
  AND j.capability_id = i.capability_id
  AND j.state = 'PENDING'
  AND j.desired_state = 'RUNNING'
RETURNING i.index_meta_initialized_at
`

type MarkIndexMetaInitializedParams struct {
	ExecutionID            string `db:"execution_id" json:"execution_id"`
	Generation             int64  `db:"generation" json:"generation"`
	IndexGeneration        int64  `db:"index_generation" json:"index_generation"`
	IndexMetaID            string `db:"index_meta_id" json:"index_meta_id"`
	IndexMetaCorrelationID string `db:"index_meta_correlation_id" json:"index_meta_correlation_id"`
}

func (q *Queries) MarkIndexMetaInitialized(ctx context.Context, arg MarkIndexMetaInitializedParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, markIndexMetaInitialized,
		arg.ExecutionID,
		arg.Generation,
		arg.IndexGeneration,
		arg.IndexMetaID,
		arg.IndexMetaCorrelationID,
	)
	var index_meta_initialized_at pgtype.Timestamptz
	err := row.Scan(&index_meta_initialized_at)
	return index_meta_initialized_at, err
}
