// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: scheduled_occurrences.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const advanceScheduledJobCursor = `-- name: AdvanceScheduledJobCursor :execrows
UPDATE elitea_runtime.scheduled_job_cursors
SET observed_through = $1,
    lease_owner = NULL,
    claim_fence = NULL,
    lease_expires_at = NULL,
    updated_at = clock_timestamp()
WHERE job_id = $2
  AND schedule_revision = $3
  AND lease_epoch = $4
  AND claim_fence = $5
`

type AdvanceScheduledJobCursorParams struct {
	ObservedThrough  pgtype.Timestamptz `db:"observed_through" json:"observed_through"`
	JobID            string             `db:"job_id" json:"job_id"`
	ScheduleRevision string             `db:"schedule_revision" json:"schedule_revision"`
	LeaseEpoch       int64              `db:"lease_epoch" json:"lease_epoch"`
	ClaimFence       []byte             `db:"claim_fence" json:"claim_fence"`
}

func (q *Queries) AdvanceScheduledJobCursor(ctx context.Context, arg AdvanceScheduledJobCursorParams) (int64, error) {
	result, err := q.db.Exec(ctx, advanceScheduledJobCursor,
		arg.ObservedThrough,
		arg.JobID,
		arg.ScheduleRevision,
		arg.LeaseEpoch,
		arg.ClaimFence,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const claimScheduledJobCursor = `-- name: ClaimScheduledJobCursor :execrows
UPDATE elitea_runtime.scheduled_job_cursors
SET schedule_revision = $1,
    observed_through = $2,
    lease_owner = $3,
    lease_epoch = $4,
    claim_fence = $5,
    lease_expires_at = $6,
    updated_at = $7
WHERE job_id = $8
`

type ClaimScheduledJobCursorParams struct {
	ScheduleRevision string             `db:"schedule_revision" json:"schedule_revision"`
	ObservedThrough  pgtype.Timestamptz `db:"observed_through" json:"observed_through"`
	LeaseOwner       *string            `db:"lease_owner" json:"lease_owner"`
	LeaseEpoch       int64              `db:"lease_epoch" json:"lease_epoch"`
	ClaimFence       []byte             `db:"claim_fence" json:"claim_fence"`
	LeaseExpiresAt   pgtype.Timestamptz `db:"lease_expires_at" json:"lease_expires_at"`
	UpdatedAt        pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	JobID            string             `db:"job_id" json:"job_id"`
}

func (q *Queries) ClaimScheduledJobCursor(ctx context.Context, arg ClaimScheduledJobCursorParams) (int64, error) {
	result, err := q.db.Exec(ctx, claimScheduledJobCursor,
		arg.ScheduleRevision,
		arg.ObservedThrough,
		arg.LeaseOwner,
		arg.LeaseEpoch,
		arg.ClaimFence,
		arg.LeaseExpiresAt,
		arg.UpdatedAt,
		arg.JobID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const claimScheduledOccurrence = `-- name: ClaimScheduledOccurrence :execrows
UPDATE elitea_runtime.scheduled_occurrences
SET lease_owner = $1,
    lease_epoch = $2,
    claim_fence = $3,
    lease_expires_at = $4,
    attempt_count = attempt_count + 1,
    updated_at = $5
WHERE invocation_id = $6
  AND state = 'PENDING'
`

type ClaimScheduledOccurrenceParams struct {
	LeaseOwner     *string            `db:"lease_owner" json:"lease_owner"`
	LeaseEpoch     int64              `db:"lease_epoch" json:"lease_epoch"`
	ClaimFence     []byte             `db:"claim_fence" json:"claim_fence"`
	LeaseExpiresAt pgtype.Timestamptz `db:"lease_expires_at" json:"lease_expires_at"`
	UpdatedAt      pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	InvocationID   string             `db:"invocation_id" json:"invocation_id"`
}

func (q *Queries) ClaimScheduledOccurrence(ctx context.Context, arg ClaimScheduledOccurrenceParams) (int64, error) {
	result, err := q.db.Exec(ctx, claimScheduledOccurrence,
		arg.LeaseOwner,
		arg.LeaseEpoch,
		arg.ClaimFence,
		arg.LeaseExpiresAt,
		arg.UpdatedAt,
		arg.InvocationID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const completeScheduledOccurrence = `-- name: CompleteScheduledOccurrence :execrows
UPDATE elitea_runtime.scheduled_occurrences
SET state = 'COMPLETED',
    outcome = $1,
    admitted_at = CASE
        WHEN $1::text = 'durably_admitted'
            THEN clock_timestamp()
        ELSE NULL
    END,
    completed_at = clock_timestamp(),
    lease_owner = NULL,
    claim_fence = NULL,
    lease_expires_at = NULL,
    last_error_code = NULL,
    updated_at = clock_timestamp()
WHERE invocation_id = $2
  AND state = 'PENDING'
  AND lease_epoch = $3
  AND claim_fence = $4
  AND outcome_mode = $5
`

type CompleteScheduledOccurrenceParams struct {
	Outcome      *string `db:"outcome" json:"outcome"`
	InvocationID string  `db:"invocation_id" json:"invocation_id"`
	LeaseEpoch   int64   `db:"lease_epoch" json:"lease_epoch"`
	ClaimFence   []byte  `db:"claim_fence" json:"claim_fence"`
	OutcomeMode  string  `db:"outcome_mode" json:"outcome_mode"`
}

func (q *Queries) CompleteScheduledOccurrence(ctx context.Context, arg CompleteScheduledOccurrenceParams) (int64, error) {
	result, err := q.db.Exec(ctx, completeScheduledOccurrence,
		arg.Outcome,
		arg.InvocationID,
		arg.LeaseEpoch,
		arg.ClaimFence,
		arg.OutcomeMode,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getScheduledJobCursorForUpdate = `-- name: GetScheduledJobCursorForUpdate :one
SELECT schedule_revision, observed_through, lease_epoch, lease_expires_at
FROM elitea_runtime.scheduled_job_cursors
WHERE job_id = $1
FOR UPDATE
`

type GetScheduledJobCursorForUpdateRow struct {
	ScheduleRevision string             `db:"schedule_revision" json:"schedule_revision"`
	ObservedThrough  pgtype.Timestamptz `db:"observed_through" json:"observed_through"`
	LeaseEpoch       int64              `db:"lease_epoch" json:"lease_epoch"`
	LeaseExpiresAt   pgtype.Timestamptz `db:"lease_expires_at" json:"lease_expires_at"`
}

func (q *Queries) GetScheduledJobCursorForUpdate(ctx context.Context, jobID string) (GetScheduledJobCursorForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getScheduledJobCursorForUpdate, jobID)
	var i GetScheduledJobCursorForUpdateRow
	err := row.Scan(
		&i.ScheduleRevision,
		&i.ObservedThrough,
		&i.LeaseEpoch,
		&i.LeaseExpiresAt,
	)
	return i, err
}

const insertScheduledJobCursor = `-- name: InsertScheduledJobCursor :exec
INSERT INTO elitea_runtime.scheduled_job_cursors (
    job_id, schedule_revision, observed_through
) VALUES (
    $1, $2, $3
)
`

type InsertScheduledJobCursorParams struct {
	JobID            string             `db:"job_id" json:"job_id"`
	ScheduleRevision string             `db:"schedule_revision" json:"schedule_revision"`
	ObservedThrough  pgtype.Timestamptz `db:"observed_through" json:"observed_through"`
}

func (q *Queries) InsertScheduledJobCursor(ctx context.Context, arg InsertScheduledJobCursorParams) error {
	_, err := q.db.Exec(ctx, insertScheduledJobCursor, arg.JobID, arg.ScheduleRevision, arg.ObservedThrough)
	return err
}

const insertScheduledOccurrence = `-- name: InsertScheduledOccurrence :exec
INSERT INTO elitea_runtime.scheduled_occurrences (
    invocation_id, job_id, schedule_revision, due_at, outcome_mode,
    next_attempt_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $4
)
ON CONFLICT (job_id, schedule_revision, due_at) DO NOTHING
`

type InsertScheduledOccurrenceParams struct {
	InvocationID     string             `db:"invocation_id" json:"invocation_id"`
	JobID            string             `db:"job_id" json:"job_id"`
	ScheduleRevision string             `db:"schedule_revision" json:"schedule_revision"`
	DueAt            pgtype.Timestamptz `db:"due_at" json:"due_at"`
	OutcomeMode      string             `db:"outcome_mode" json:"outcome_mode"`
}

func (q *Queries) InsertScheduledOccurrence(ctx context.Context, arg InsertScheduledOccurrenceParams) error {
	_, err := q.db.Exec(ctx, insertScheduledOccurrence,
		arg.InvocationID,
		arg.JobID,
		arg.ScheduleRevision,
		arg.DueAt,
		arg.OutcomeMode,
	)
	return err
}

const listClaimableScheduledOccurrences = `-- name: ListClaimableScheduledOccurrences :many
SELECT occurrence.invocation_id,
       occurrence.job_id,
       occurrence.schedule_revision,
       occurrence.due_at,
       occurrence.outcome_mode,
       occurrence.lease_epoch
FROM elitea_runtime.scheduled_occurrences AS occurrence
JOIN generate_subscripts(
    $1::text[],
    1
) AS registration(position)
  ON occurrence.job_id =
     ($1::text[])[registration.position]
 AND occurrence.schedule_revision =
     ($2::text[])[registration.position]
WHERE occurrence.state = 'PENDING'
  AND occurrence.due_at <= $3
  AND occurrence.next_attempt_at <= $3
  AND (
      occurrence.lease_expires_at IS NULL
      OR occurrence.lease_expires_at <= $3
  )
ORDER BY occurrence.due_at, occurrence.invocation_id
LIMIT $4
FOR UPDATE OF occurrence SKIP LOCKED
`

type ListClaimableScheduledOccurrencesParams struct {
	JobIds            []string           `db:"job_ids" json:"job_ids"`
	ScheduleRevisions []string           `db:"schedule_revisions" json:"schedule_revisions"`
	ObservedAt        pgtype.Timestamptz `db:"observed_at" json:"observed_at"`
	PageLimit         int32              `db:"page_limit" json:"page_limit"`
}

type ListClaimableScheduledOccurrencesRow struct {
	InvocationID     string             `db:"invocation_id" json:"invocation_id"`
	JobID            string             `db:"job_id" json:"job_id"`
	ScheduleRevision string             `db:"schedule_revision" json:"schedule_revision"`
	DueAt            pgtype.Timestamptz `db:"due_at" json:"due_at"`
	OutcomeMode      string             `db:"outcome_mode" json:"outcome_mode"`
	LeaseEpoch       int64              `db:"lease_epoch" json:"lease_epoch"`
}

func (q *Queries) ListClaimableScheduledOccurrences(ctx context.Context, arg ListClaimableScheduledOccurrencesParams) ([]ListClaimableScheduledOccurrencesRow, error) {
	rows, err := q.db.Query(ctx, listClaimableScheduledOccurrences,
		arg.JobIds,
		arg.ScheduleRevisions,
		arg.ObservedAt,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListClaimableScheduledOccurrencesRow{}
	for rows.Next() {
		var i ListClaimableScheduledOccurrencesRow
		if err := rows.Scan(
			&i.InvocationID,
			&i.JobID,
			&i.ScheduleRevision,
			&i.DueAt,
			&i.OutcomeMode,
			&i.LeaseEpoch,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releaseScheduledOccurrenceForRetry = `-- name: ReleaseScheduledOccurrenceForRetry :execrows
UPDATE elitea_runtime.scheduled_occurrences
SET lease_owner = NULL,
    claim_fence = NULL,
    lease_expires_at = NULL,
    next_attempt_at = clock_timestamp()
        + ($1::bigint * interval '1 millisecond'),
    last_error_code = $2,
    updated_at = clock_timestamp()
WHERE invocation_id = $3
  AND state = 'PENDING'
  AND lease_epoch = $4
  AND claim_fence = $5
`

type ReleaseScheduledOccurrenceForRetryParams struct {
	RetryDelayMilliseconds int64   `db:"retry_delay_milliseconds" json:"retry_delay_milliseconds"`
	LastErrorCode          *string `db:"last_error_code" json:"last_error_code"`
	InvocationID           string  `db:"invocation_id" json:"invocation_id"`
	LeaseEpoch             int64   `db:"lease_epoch" json:"lease_epoch"`
	ClaimFence             []byte  `db:"claim_fence" json:"claim_fence"`
}

func (q *Queries) ReleaseScheduledOccurrenceForRetry(ctx context.Context, arg ReleaseScheduledOccurrenceForRetryParams) (int64, error) {
	result, err := q.db.Exec(ctx, releaseScheduledOccurrenceForRetry,
		arg.RetryDelayMilliseconds,
		arg.LastErrorCode,
		arg.InvocationID,
		arg.LeaseEpoch,
		arg.ClaimFence,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const scheduledDatabaseNow = `-- name: ScheduledDatabaseNow :one
SELECT clock_timestamp()::timestamptz
`

func (q *Queries) ScheduledDatabaseNow(ctx context.Context) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, scheduledDatabaseNow)
	var column_1 pgtype.Timestamptz
	err := row.Scan(&column_1)
	return column_1, err
}

const supersedeScheduledJobRevision = `-- name: SupersedeScheduledJobRevision :exec
UPDATE elitea_runtime.scheduled_occurrences
SET state = 'SUPERSEDED',
    lease_owner = NULL,
    claim_fence = NULL,
    lease_expires_at = NULL,
    completed_at = $1,
    updated_at = $1
WHERE job_id = $2
  AND schedule_revision = $3
  AND state = 'PENDING'
`

type SupersedeScheduledJobRevisionParams struct {
	CompletedAt      pgtype.Timestamptz `db:"completed_at" json:"completed_at"`
	JobID            string             `db:"job_id" json:"job_id"`
	ScheduleRevision string             `db:"schedule_revision" json:"schedule_revision"`
}

func (q *Queries) SupersedeScheduledJobRevision(ctx context.Context, arg SupersedeScheduledJobRevisionParams) error {
	_, err := q.db.Exec(ctx, supersedeScheduledJobRevision, arg.CompletedAt, arg.JobID, arg.ScheduleRevision)
	return err
}
