package authsvc

import (
	"context"
	"errors"
	"math"
	"strings"
	"testing"

	"github.com/golang-jwt/jwt/v5"
	"github.com/jackc/pgx/v5"

	"github.com/EliteaAI/elitea-platform/services/elitea-main/internal/db/sqlcgen"
)

type activePATQueriesFunc func(context.Context, string) (sqlcgen.GetActivePATPrincipalByUUIDRow, error)

func (f activePATQueriesFunc) GetActivePATPrincipalByUUID(
	ctx context.Context,
	uuid string,
) (sqlcgen.GetActivePATPrincipalByUUIDRow, error) {
	return f(ctx, uuid)
}

func TestLocalValidatorRejectsNonBaselineHMACAlgorithmBeforeDatabaseAccess(t *testing.T) {
	secret := "test-secret"
	token := jwt.NewWithClaims(jwt.SigningMethodHS256, tokenClaims{UUID: "8ce4be49-0d10-4f05-a63f-d6d46f99a3f0"})
	encoded, err := token.SignedString([]byte(secret))
	if err != nil {
		t.Fatal(err)
	}

	validator := NewLocalValidator(nil, secret)
	_, err = validator.ValidateToken(context.Background(), encoded)
	if !errors.Is(err, ErrTokenRejected) || !strings.Contains(err.Error(), "unexpected signing method") {
		t.Fatalf("error = %v, want HS512 rejection", err)
	}
}

func TestLocalValidatorAcceptsBaselinePyJWTHS512TokenAndPreservesTypedIDs(t *testing.T) {
	const (
		secret = "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef"
		uuid   = "8ce4be49-0d10-4f05-a63f-d6d46f99a3f0"
		// Generated by PyJWT 2.12.1 using the exact current-baseline payload and HS512.
		encoded = "eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJ1dWlkIjoiOGNlNGJlNDktMGQxMC00ZjA1LWE2M2YtZDZkNDZmOTlhM2YwIiwiZXhwaXJlcyI6bnVsbH0.mrvHMef_5BEBKHViTDuciP_FOzJrW8VitsbdJmDy6kjwup5JAhCLEYJO4XW7GgwzDL3Nij5d7Lv2gXSIcfKkvA"
	)
	lookups := 0
	validator := &LocalValidator{
		secretKey: []byte(secret),
		queries: activePATQueriesFunc(func(_ context.Context, gotUUID string) (sqlcgen.GetActivePATPrincipalByUUIDRow, error) {
			lookups++
			if gotUUID != uuid {
				t.Fatalf("lookup UUID = %q, want %q", gotUUID, uuid)
			}
			return sqlcgen.GetActivePATPrincipalByUUIDRow{
				TokenID: 42,
				UserID:  7,
				Email:   "owner@example.test",
			}, nil
		}),
	}

	principal, err := validator.ValidateToken(context.Background(), encoded)
	if err != nil {
		t.Fatal(err)
	}
	if lookups != 1 {
		t.Fatalf("database lookups = %d, want 1", lookups)
	}
	if principal.ID != "7" || principal.UserID != "7" || principal.TokenID != "42" {
		t.Fatalf("principal identity = %+v", principal)
	}
	if principal.Email != "owner@example.test" || principal.AuthType != "token" {
		t.Fatalf("principal metadata = %+v", principal)
	}
	if len(principal.Roles) != 0 || len(principal.Permissions) != 0 {
		t.Fatalf("token authentication must not cache RBAC authority: %+v", principal)
	}
	if principal.TokenProjectID != nil {
		t.Fatalf("token binding = %d, want nil; a token with no binding row is unbound", *principal.TokenProjectID)
	}
}

// TestLocalValidatorReportsStoredTokenProjectBinding proves the binding reaches
// the identity from STORAGE, on the row the validator already reads, and in one
// query (ADR-0018, spec-llm-project-scope §3.2). A second lookup here would be
// an extra round trip on every authenticated request.
func TestLocalValidatorReportsStoredTokenProjectBinding(t *testing.T) {
	const (
		secret = "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef"
		uuid   = "8ce4be49-0d10-4f05-a63f-d6d46f99a3f0"
	)
	token := jwt.NewWithClaims(jwt.SigningMethodHS512, tokenClaims{UUID: uuid})
	encoded, err := token.SignedString([]byte(secret))
	if err != nil {
		t.Fatal(err)
	}

	for name, test := range map[string]struct {
		stored *int32
		want   *int64
	}{
		"bound":    {stored: int32Address(42), want: int64Address(42)},
		"unbound":  {stored: nil, want: nil},
		"zero":     {stored: int32Address(0), want: nil},
		"negative": {stored: int32Address(-1), want: nil},
		"maximumInt32": {
			stored: int32Address(math.MaxInt32),
			want:   int64Address(math.MaxInt32),
		},
	} {
		t.Run(name, func(t *testing.T) {
			lookups := 0
			validator := &LocalValidator{
				secretKey: []byte(secret),
				queries: activePATQueriesFunc(func(context.Context, string) (sqlcgen.GetActivePATPrincipalByUUIDRow, error) {
					lookups++
					return sqlcgen.GetActivePATPrincipalByUUIDRow{
						TokenID:   42,
						UserID:    7,
						Email:     "owner@example.test",
						ProjectID: test.stored,
					}, nil
				}),
			}
			principal, err := validator.ValidateToken(context.Background(), encoded)
			if err != nil {
				t.Fatal(err)
			}
			if lookups != 1 {
				t.Fatalf("database lookups = %d, want 1; the binding must not cost a second query", lookups)
			}
			switch {
			case test.want == nil && principal.TokenProjectID != nil:
				t.Fatalf("token binding = %d, want nil", *principal.TokenProjectID)
			case test.want != nil && principal.TokenProjectID == nil:
				t.Fatalf("token binding = nil, want %d", *test.want)
			case test.want != nil && *principal.TokenProjectID != *test.want:
				t.Fatalf("token binding = %d, want %d", *principal.TokenProjectID, *test.want)
			}
		})
	}
}

// TestLocalValidatorIgnoresTokenAndPrincipalNamesForBinding is spec §7
// invariant 2 as an executable check. The token name is caller-supplied free
// text of up to 768 bytes. A binding derived from it would be self-service
// authorization over another project's budget and provider credentials.
func TestLocalValidatorIgnoresTokenAndPrincipalNamesForBinding(t *testing.T) {
	const secret = "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef"
	token := jwt.NewWithClaims(
		jwt.SigningMethodHS512,
		tokenClaims{UUID: "8ce4be49-0d10-4f05-a63f-d6d46f99a3f0"},
	)
	encoded, err := token.SignedString([]byte(secret))
	if err != nil {
		t.Fatal(err)
	}
	validator := &LocalValidator{
		secretKey: []byte(secret),
		queries: activePATQueriesFunc(func(context.Context, string) (sqlcgen.GetActivePATPrincipalByUUIDRow, error) {
			return sqlcgen.GetActivePATPrincipalByUUIDRow{
				TokenID: 42,
				UserID:  7,
				Email:   ":system:project:99:@centry.user",
			}, nil
		}),
	}

	principal, err := validator.ValidateToken(context.Background(), encoded)
	if err != nil {
		t.Fatal(err)
	}
	if principal.TokenProjectID != nil {
		t.Fatalf("token binding = %d, want nil; only a stored binding may set it", *principal.TokenProjectID)
	}
	if principal.Name != "" {
		t.Fatalf("principal name = %q, want empty; the validator must not populate it", principal.Name)
	}
}

func int32Address(value int32) *int32 {
	return &value
}

func int64Address(value int64) *int64 {
	return &value
}

func TestLocalValidatorFailsClosedForInactiveOrMissingPAT(t *testing.T) {
	const secret = "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef"
	token := jwt.NewWithClaims(
		jwt.SigningMethodHS512,
		tokenClaims{UUID: "8ce4be49-0d10-4f05-a63f-d6d46f99a3f0"},
	)
	encoded, err := token.SignedString([]byte(secret))
	if err != nil {
		t.Fatal(err)
	}
	validator := &LocalValidator{
		secretKey: []byte(secret),
		queries: activePATQueriesFunc(func(context.Context, string) (sqlcgen.GetActivePATPrincipalByUUIDRow, error) {
			return sqlcgen.GetActivePATPrincipalByUUIDRow{}, pgx.ErrNoRows
		}),
	}

	_, err = validator.ValidateToken(context.Background(), encoded)
	if !errors.Is(err, ErrTokenRejected) || !strings.Contains(err.Error(), "token not found") {
		t.Fatalf("error = %v, want inactive token rejection", err)
	}
}

func TestLocalValidatorRejectsMissingConfiguration(t *testing.T) {
	validator := NewLocalValidator(nil, "")
	_, err := validator.ValidateToken(context.Background(), "not-a-token")
	if !errors.Is(err, ErrTokenValidationUnavailable) || !strings.Contains(err.Error(), "signing key is not configured") {
		t.Fatalf("error = %v, want missing key rejection", err)
	}

	validator = NewLocalValidator(nil, "configured-secret")
	token := jwt.NewWithClaims(jwt.SigningMethodHS512, tokenClaims{UUID: "8ce4be49-0d10-4f05-a63f-d6d46f99a3f0"})
	encoded, signErr := token.SignedString([]byte("configured-secret"))
	if signErr != nil {
		t.Fatal(signErr)
	}
	_, err = validator.ValidateToken(context.Background(), encoded)
	if !errors.Is(err, ErrTokenValidationUnavailable) || !strings.Contains(err.Error(), "repository is not configured") {
		t.Fatalf("error = %v, want missing repository rejection", err)
	}
}

func TestLocalValidatorBytesSnapshotsExactKey(t *testing.T) {
	key := []byte("configured-secret")
	validator := NewLocalValidatorBytes(nil, key)
	clear(key)
	token := jwt.NewWithClaims(
		jwt.SigningMethodHS512,
		tokenClaims{UUID: "8ce4be49-0d10-4f05-a63f-d6d46f99a3f0"},
	)
	encoded, err := token.SignedString([]byte("configured-secret"))
	if err != nil {
		t.Fatal(err)
	}
	_, err = validator.ValidateToken(context.Background(), encoded)
	if !errors.Is(err, ErrTokenValidationUnavailable) || !strings.Contains(err.Error(), "repository is not configured") {
		t.Fatalf("snapshotted key error = %v", err)
	}
}

func TestLocalValidatorPreservesDatabaseFailures(t *testing.T) {
	const secret = "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef"
	token := jwt.NewWithClaims(jwt.SigningMethodHS512, tokenClaims{UUID: "8ce4be49-0d10-4f05-a63f-d6d46f99a3f0"})
	encoded, err := token.SignedString([]byte(secret))
	if err != nil {
		t.Fatal(err)
	}
	want := errors.New("database unavailable")
	validator := &LocalValidator{
		secretKey: []byte(secret),
		queries: activePATQueriesFunc(func(context.Context, string) (sqlcgen.GetActivePATPrincipalByUUIDRow, error) {
			return sqlcgen.GetActivePATPrincipalByUUIDRow{}, want
		}),
	}

	_, err = validator.ValidateToken(context.Background(), encoded)
	if !errors.Is(err, ErrTokenValidationUnavailable) || !errors.Is(err, want) {
		t.Fatalf("error = %v, want unavailable plus wrapped database failure", err)
	}
}
