package authsvc

import (
	"context"
	"errors"
	"strings"
	"testing"
	"time"

	"github.com/golang-jwt/jwt/v5"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"

	"github.com/EliteaAI/elitea-platform/services/elitea-main/internal/db/sqlcgen"
)

type activePATIssuerQueriesFunc func(context.Context, int32) (sqlcgen.GetActivePATForUserRow, error)

func (f activePATIssuerQueriesFunc) GetActivePATForUser(
	ctx context.Context,
	userID int32,
) (sqlcgen.GetActivePATForUserRow, error) {
	return f(ctx, userID)
}

func TestLocalIssuerPreservesBaselinePyJWTHS512Token(t *testing.T) {
	const (
		secret = "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef"
		uuid   = "8ce4be49-0d10-4f05-a63f-d6d46f99a3f0"
		// Generated by PyJWT 2.12.1 from {"uuid": uuid, "expires": null}.
		want = "eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJ1dWlkIjoiOGNlNGJlNDktMGQxMC00ZjA1LWE2M2YtZDZkNDZmOTlhM2YwIiwiZXhwaXJlcyI6bnVsbH0.mrvHMef_5BEBKHViTDuciP_FOzJrW8VitsbdJmDy6kjwup5JAhCLEYJO4XW7GgwzDL3Nij5d7Lv2gXSIcfKkvA"
	)
	issuer := &LocalIssuer{
		secretKey: []byte(secret),
		queries: activePATIssuerQueriesFunc(func(_ context.Context, userID int32) (sqlcgen.GetActivePATForUserRow, error) {
			if userID != 7 {
				t.Fatalf("user ID = %d, want 7", userID)
			}
			return sqlcgen.GetActivePATForUserRow{
				TokenID: 42,
				Uuid:    pointer(uuid),
				UserID:  7,
				Email:   "owner@example.test",
			}, nil
		}),
	}

	got, err := issuer.IssueToken(context.Background(), 7)
	if err != nil {
		t.Fatal(err)
	}
	if got != want {
		t.Fatalf("encoded token differs from Python baseline")
	}
}

func TestLocalIssuerPreservesBaselineMinuteExpiration(t *testing.T) {
	expiration := time.Date(2026, time.July, 23, 12, 34, 59, 999, time.UTC)
	issuer := &LocalIssuer{
		secretKey: []byte("secret"),
		queries: activePATIssuerQueriesFunc(func(context.Context, int32) (sqlcgen.GetActivePATForUserRow, error) {
			return sqlcgen.GetActivePATForUserRow{
				TokenID: 1,
				Uuid:    pointer("8ce4be49-0d10-4f05-a63f-d6d46f99a3f0"),
				Expires: pgtype.Timestamp{Time: expiration, Valid: true},
				UserID:  7,
			}, nil
		}),
	}
	encoded, err := issuer.IssueToken(context.Background(), 7)
	if err != nil {
		t.Fatal(err)
	}
	claims := &tokenClaims{}
	if _, err := jwt.ParseWithClaims(encoded, claims, func(*jwt.Token) (any, error) {
		return []byte("secret"), nil
	}); err != nil {
		t.Fatal(err)
	}
	if claims.Expires == nil || *claims.Expires != "2026-07-23T12:34" {
		t.Fatalf("expires = %v", claims.Expires)
	}
}

func TestLocalIssuerFailsClosedForMissingOrInvalidPAT(t *testing.T) {
	for name, test := range map[string]struct {
		row      sqlcgen.GetActivePATForUserRow
		query    error
		want     error
		contains string
	}{
		"missing": {
			query: pgx.ErrNoRows, want: ErrTokenRejected, contains: "active PAT not found",
		},
		"database unavailable": {
			query: errors.New("database-canary"), want: ErrTokenValidationUnavailable, contains: "database-canary",
		},
		"wrong owner": {
			row: sqlcgen.GetActivePATForUserRow{
				TokenID: 1, Uuid: pointer("8ce4be49-0d10-4f05-a63f-d6d46f99a3f0"), UserID: 8,
			},
			want: ErrTokenValidationUnavailable, contains: "invalid identity data",
		},
	} {
		t.Run(name, func(t *testing.T) {
			issuer := &LocalIssuer{
				secretKey: []byte("secret"),
				queries: activePATIssuerQueriesFunc(func(context.Context, int32) (sqlcgen.GetActivePATForUserRow, error) {
					return test.row, test.query
				}),
			}
			_, err := issuer.IssueToken(context.Background(), 7)
			if !errors.Is(err, test.want) || !strings.Contains(err.Error(), test.contains) {
				t.Fatalf("error = %v, want %v containing %q", err, test.want, test.contains)
			}
		})
	}
}

func TestLocalIssuerSnapshotsSigningKey(t *testing.T) {
	key := []byte("secret")
	issuer := NewLocalIssuerBytes(nil, key)
	clear(key)
	if string(issuer.secretKey) != "secret" {
		t.Fatalf("issuer key did not survive source clearing")
	}
}

func pointer[T any](value T) *T {
	return &value
}
