# syntax=docker/dockerfile:1.7

FROM rust:1.97.1-bookworm AS builder

WORKDIR /src

COPY libs/proto ./libs/proto
COPY services/elitea-worker-rust ./services/elitea-worker-rust

WORKDIR /src/services/elitea-worker-rust
RUN --mount=type=cache,target=/usr/local/cargo/registry \
    --mount=type=cache,target=/usr/local/cargo/git \
    --mount=type=cache,target=/cargo-target \
    CARGO_TARGET_DIR=/cargo-target cargo build --locked --release && \
    cp /cargo-target/release/elitea-worker-rust /usr/local/bin/elitea-worker-rust

FROM gcr.io/distroless/cc-debian12:nonroot AS runtime

COPY --from=builder \
    /usr/local/bin/elitea-worker-rust \
    /usr/local/bin/elitea-worker-rust

USER 10001:10001
ENTRYPOINT ["/usr/local/bin/elitea-worker-rust"]
