{{- if .Values.otelCollector.enabled }}
{{- if .Values.otelCollector.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "otel-collector.serviceAccountName" . }}
  labels:
    {{- include "otel-collector.labels" . | nindent 4 }}
  {{- with .Values.otelCollector.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
