apiVersion: v1
kind: Service
metadata:
  name: {{ include "otel-collector.fullname" . }}
  labels:
    {{- include "otel-collector.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: otlp-grpc
      port: {{ .Values.service.grpcPort }}
      targetPort: otlp-grpc
      protocol: TCP
    - name: otlp-http
      port: {{ .Values.service.httpPort }}
      targetPort: otlp-http
      protocol: TCP
  selector:
    {{- include "otel-collector.selectorLabels" . | nindent 4 }}
