"""The ``fixture`` runner: real composition and upload over canned results.

``ELITEA_DEEPWIKI_RUNNER=fixture`` is for a stack that must exercise the whole
generate → land → read path — the facade's credential and callback handling,
this service's composition and artifact upload, the bucket, the wiki browser —
without the analysis engine's dependency closure, a git host or a model.
The browser journeys run against it.

It is :class:`LegacyToolRunner` with its tools injected, exactly as the P0
composition tests inject them, plus paced progress events so a client sees a
run in flight and can stop it. Everything downstream of the tool call is the
real code: the parameter merge, the egress check, composition, publishing,
upload. What is canned is only what the engine would have computed.

The canned wiki is deterministic and derived from the request, so a test can
predict the keys that land: ``{owner}--{repo}--{branch}/…``. One page carries
a mermaid block that does not parse, on purpose — it is what the quick-fix
journey repairs.
"""
from __future__ import annotations

import asyncio
import json
from typing import Any

from .legacy_runner import LegacyToolRunner

#: Progress the fixture emits before each tool answers, in order. The legacy
#: engine emitted prose like this through ``invocation_thinking``; the UI's
#: thinking log renders it verbatim.
STEPS: dict[str, tuple[str, ...]] = {
    "generate_wiki": (
        "Cloning the repository",
        "Indexing 12 files",
        "Planning the wiki structure",
        "Writing 3 pages",
        "Assembling the manifest",
    ),
    "ask": ("Searching the wiki index", "Composing the answer"),
    "deep_research": (
        "Planning the research",
        "Reading the relevant pages",
        "Writing the report",
    ),
}

BROKEN_MERMAID_PAGE = """# Request flow

The diagram below is deliberately broken: the fixture exists so the quick fix
has something to repair.

```mermaid
graph TD
  A[Client] -->
```

After the diagram.
"""


def wiki_id_for(repo_config: dict[str, Any] | None, branch: str | None) -> str:
    """The canonical ``{owner}--{repo}--{branch}`` the engine would derive."""
    repository = ""
    if isinstance(repo_config, dict):
        repository = str(repo_config.get("repository") or "")
        if not repository:
            provider = repo_config.get("provider_config")
            if isinstance(provider, dict):
                repository = str(provider.get("repository") or "")
    repository = repository.strip().strip("/") or "fixture/repository"
    return f"{repository.replace('/', '--')}--{(branch or 'main').strip() or 'main'}"


def generate_wiki(
    *,
    query: str,
    repo_config: dict[str, Any] | None = None,
    active_branch: str = "main",
    **_ignored: Any,
) -> dict[str, Any]:
    """A completed generation: manifest, structure, three pages, context."""
    wiki_id = wiki_id_for(repo_config, active_branch)
    repository = wiki_id.rsplit("--", 1)[0].replace("--", "/")
    pages = {
        "wiki_pages/overview/getting-started.md": (
            f"# Getting started\n\nGenerated by the fixture runner for `{repository}` "
            f"in answer to: {query}\n"
        ),
        "wiki_pages/architecture/request-flow.md": BROKEN_MERMAID_PAGE,
        "wiki_pages/components/storage.md": (
            "# Storage\n\nObjects live in the `wiki-artifacts` bucket, one key per page.\n"
        ),
    }
    manifest = {
        "schema_version": 1,
        "wiki_id": wiki_id,
        "wiki_title": f"{repository.rsplit('/', 1)[-1]} wiki",
        "description": "Generated by the DeepWiki fixture runner.",
        "wiki_version_id": "fixture-1",
        "created_at": "2026-01-01T00:00:00Z",
        "canonical_repo_identifier": repository,
        "repository": repository,
        "branch": active_branch or "main",
        "provider_type": "github",
        "pages": list(pages),
    }
    structure = {
        "title": manifest["wiki_title"],
        "sections": [
            {"title": "Overview", "pages": ["wiki_pages/overview/getting-started.md"]},
            {"title": "Architecture", "pages": ["wiki_pages/architecture/request-flow.md"]},
            {"title": "Components", "pages": ["wiki_pages/components/storage.md"]},
        ],
    }
    artifacts: list[dict[str, Any]] = [
        {
            "name": f"{wiki_id}/analysis/wiki_structure_fixture.json",
            "type": "application/json",
            "data": json.dumps(structure, indent=2),
        },
        *(
            {"name": f"{wiki_id}/{key}", "type": "text/markdown", "data": body}
            for key, body in pages.items()
        ),
        {
            "name": f"{wiki_id}/wiki_manifest_fixture-1.json",
            "type": "application/json",
            "data": json.dumps(manifest, indent=2),
        },
    ]
    return {
        "success": True,
        "result": f"Wiki generated: {len(pages)} pages",
        "wiki_id": wiki_id,
        "artifacts": artifacts,
        "repository_context": f"repository: {repository}\nbranch: {active_branch}\nfiles: 12\n",
    }


def ask(*, question: str, **_ignored: Any) -> dict[str, Any]:
    return {
        "success": True,
        "answer": f"Fixture answer to: {question}",
        "sources": [
            {"source": "wiki_pages/overview/getting-started.md"},
            {"source": "wiki_pages/components/storage.md"},
        ],
    }


def deep_research(*, question: str, research_type: str = "general", **_ignored: Any) -> dict[str, Any]:
    return {
        "success": True,
        "report": f"# Research report ({research_type})\n\nQuestion: {question}\n\nFindings: fixture.\n",
    }


FIXTURE_TOOLS = {
    "generate_wiki": generate_wiki,
    "ask": ask,
    "deep_research": deep_research,
}


class FixtureToolRunner(LegacyToolRunner):
    """The legacy runner over :data:`FIXTURE_TOOLS`, with paced progress."""

    name = "fixture"

    def __init__(self, settings=None, artifact_client_factory=None) -> None:
        super().__init__(
            settings=settings,
            tools=dict(FIXTURE_TOOLS),
            artifact_client_factory=artifact_client_factory,
        )
        self._step_seconds = float(getattr(settings, "fixture_step_seconds", 0.0) or 0.0)

    async def _paced(self, tool_name: str, context: Any) -> None:
        for step in STEPS.get(tool_name, ()):
            # The checkpoint is what makes Stop work mid-run: a cancelled
            # invocation raises here instead of finishing and uploading.
            await context.checkpoint()
            await context.thinking(step)
            if self._step_seconds > 0:
                await asyncio.sleep(self._step_seconds)
