#!/usr/bin/env node
/**
 * check-handlers.mjs — R-M2 enforcement (spec §6.5, unit M1).
 *
 * R-M2: "Every MSW handler lives in `src/test/msw/handlers/` and is either
 * generated by orval or derives its body from a Channel-B fixture file."
 *
 * This script walks ONLY `src/test/msw/handlers/**` — the hand-authored
 * side of R-M2's disjunction — and runs every `.ts` file's source through
 * `checkHandlerSource` (scripts/lib/mock-rules-core.mjs, unit F2), which
 * flags `HttpResponse.json(<inline object/array literal>)` (and
 * `Response.json`/`.text`/`.xml`/`.html`) bodies: a handler answering with a
 * hand-written literal instead of a fixture import.
 *
 * `src/shared/api/generated/**\/*.msw.ts` (orval's own output, "Do not edit
 * manually") is DELIBERATELY OUT OF SCOPE here — it satisfies R-M2 via the
 * disjunction's OTHER clause ("generated by orval"), not this one. Walking
 * generated code with a heuristic tuned for hand-authored files would either
 * no-op (the generated bodies are always a variable/conditional expression,
 * never an inline literal) or risk a false positive the day a future orval
 * template changes shape — see src/test/msw/handlers/index.ts's own header
 * comment for the full R-M2/R-M3 generated-vs-hand-authored design note.
 *
 * Usage: node scripts/check-handlers.mjs [--root <dir>]
 *
 * RED/GREEN (see the M1 report for the transcript): temporarily add a
 * handler with an inline `HttpResponse.json({...})` body to
 * src/test/msw/handlers/transport.ts — this script exits 1, pointing at the
 * offending line; remove it — this script exits 0 again.
 */
import { readFileSync, readdirSync, statSync } from 'node:fs';
import { dirname, join, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import process from 'node:process';

import { checkHandlerSource } from './lib/mock-rules-core.mjs';

const SCRIPT_DIR = dirname(fileURLToPath(import.meta.url));
const APP_DIR = resolve(SCRIPT_DIR, '..');
const HANDLER_FILE_RE = /\.tsx?$/;

function parseArgs(argv) {
  const args = { root: APP_DIR };
  for (let i = 0; i < argv.length; i++) {
    if (argv[i] === '--root') {
      const value = argv[i + 1];
      if (!value) throw new Error('--root requires a directory argument');
      args.root = resolve(value);
      i++;
    } else {
      throw new Error(`unknown argument: ${argv[i]}`);
    }
  }
  return args;
}

function* handlerFiles(dir) {
  let entries;
  try {
    entries = readdirSync(dir);
  } catch {
    return;
  }
  for (const entry of entries) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) {
      yield* handlerFiles(full);
    } else if (HANDLER_FILE_RE.test(entry)) {
      yield full;
    }
  }
}

function main() {
  const { root } = parseArgs(process.argv.slice(2));
  const handlersDir = join(root, 'src', 'test', 'msw', 'handlers');
  let files = 0;
  const findings = [];

  for (const file of handlerFiles(handlersDir)) {
    files++;
    const rel = relative(root, file);
    findings.push(...checkHandlerSource(rel, readFileSync(file, 'utf8')));
  }

  if (files === 0) {
    console.error(`check-handlers: found 0 files under ${relative(root, handlersDir)} — refusing to pass vacuously`);
    process.exit(2);
  }

  for (const f of findings) {
    console.error(`${f.rule} ${f.file}:${f.line} — ${f.message}`);
  }
  if (findings.length > 0) {
    console.error(`check-handlers: ${findings.length} R-M2 violation(s) in ${files} file(s) — failing`);
    process.exit(1);
  }
  console.log(`check-handlers: OK — ${files} handler file(s) under src/test/msw/handlers/ derive their bodies from fixtures (R-M2)`);
}

main();
